// <auto-generated>
// This file is generated. Do not edit manually.
// Generated at      : 2026-03-29 20:43:37
// Generated at (UTC): 2026-03-29 17:43:37
// Machine: DESKTOP-IITN2G2
// Generator: EntityCreator v1.0
// Class Name: ViewModelWriter
// </auto-generated>

#nullable enable

using System;
using System.ComponentModel.DataAnnotations;

namespace SeramikStore.Web.ViewModels.Reason
{
    public class ReasonUpdateViewModel
    {
        [Required]
        [Display(Name = "Id")]
        public int? Id { get; set; }

        [Required]
        [Display(Name = "Reasondesc")]
        public string? Reasondesc { get; set; }

        [Display(Name = "IsCustom")]
        public bool? IsCustom { get; set; }

    }
}
