// <auto-generated>
// This file is generated. Do not edit manually.
// Generated at      : 2026-01-18 15:13:10
// Generated at (UTC): 2026-01-18 12:13:10
// Machine: DESKTOP-IITN2G2
// Generator: EntityCreator v1.0
// Class Name: ServiceWriter
// </auto-generated>

using System.Collections.Generic;
using SeramikStore.Contracts.Category;
using SeramikStore.Contracts.Common;

namespace SeramikStore.Services
{
    public partial interface ICategoryService
    {
        int Create(CategoryCreateDto dto);
        void Update(CategoryUpdateDto dto);
        void Delete(int id);
        void DeleteSoft(int id);
        CategoryDto? GetById(int id);
        List<CategoryListItemDto> List();
        PagedResult<CategoryListItemDto> PagedList(int page, int pageSize);
    }
}
