// <auto-generated>
// This file is generated. Do not edit manually.
// Generated at      : 2026-04-21 14:26:25
// Generated at (UTC): 2026-04-21 11:26:25
// Machine: YAZILIM3
// Generator: EntityCreator v1.0
// Class Name: DtoWriter
// </auto-generated>

#nullable enable

using System;

namespace SeramikStore.Contracts.ProductCategory
{
    public class ProductCategoryListItemDto
    {
        public int Id { get; set; }
        public int ProductId { get; set; }
        public int CategoryId { get; set; }
    }
}
