// <auto-generated>
// This file is generated. Do not edit manually.
// Generated at      : 2026-01-18 00:41:42
// Generated at (UTC): 2026-01-17 21:41:42
// Machine: DESKTOP-IITN2G2
// Generator: EntityCreator v1.0
// Class Name: DtoWriter
// </auto-generated>

using System;

namespace SeramikStore.Contracts.Category
{
    public class CategoryCreateDto
    {
        public string Name { get; set; }
    }
}
