// <auto-generated>
// This file is generated. Do not edit manually.
// Generated at      : 2026-01-19 17:47:47
// Generated at (UTC): 2026-01-19 14:47:47
// Machine: YAZILIM3
// Generator: EntityCreator v1.0
// Class Name: DtoWriter
// </auto-generated>

using System;

namespace SeramikStore.Contracts.Category
{
    public class CategoryCreateDto
    {
        public string Name { get; set; }
    }
}
