// <auto-generated>
// This file is generated. Do not edit manually.
// Generated at      : 2026-02-27 17:18:33
// Generated at (UTC): 2026-02-27 14:18:33
// Machine: YAZILIM3
// Generator: EntityCreator v1.0
// Class Name: DtoWriter
// </auto-generated>

#nullable enable

using System;

namespace SeramikStore.Contracts.Araba
{
    public class ArabaListItemDto
    {
        public int Id { get; set; }
        public required string Model { get; set; }
        public required string Marka { get; set; }
    }
}
