// <auto-generated>
// This file is generated. Do not edit manually.
// Generated at      : 2026-04-21 14:26:25
// Generated at (UTC): 2026-04-21 11:26:25
// Machine: YAZILIM3
// Generator: EntityCreator v1.0
// Class Name: ViewModelWriter
// </auto-generated>

#nullable enable

using System;
using System.ComponentModel.DataAnnotations;

namespace SeramikStore.Web.ViewModels.ProductCategory
{
    public class ProductCategoryListViewModel
    {
        [Required]
        [Display(Name = "Id")]
        public int? Id { get; set; }

        [Required]
        [Display(Name = "ProductId")]
        public int? ProductId { get; set; }

        [Required]
        [Display(Name = "CategoryId")]
        public int? CategoryId { get; set; }

    }
}
