// <auto-generated>
// This file is generated. Do not edit manually.
// Generated at      : 2026-01-19 17:47:49
// Generated at (UTC): 2026-01-19 14:47:49
// Machine: YAZILIM3
// Generator: EntityCreator v1.0
// Class Name: ViewModelWriter
// </auto-generated>

using System;
using System.ComponentModel.DataAnnotations;

namespace SeramikStore.Web.ViewModels.Category
{
    public class CategoryUpdateViewModel
    {
        [Display(Name = "Id")]
        public int Id { get; set; }

        [Required]
        [Display(Name = "Name")]
        public string Name { get; set; }

        [Display(Name = "IsActive")]
        public bool IsActive { get; set; }

    }
}
