// <auto-generated>
// This file is generated. Do not edit manually.
// Generated at      : 2026-01-18 16:10:59
// Generated at (UTC): 2026-01-18 13:10:59
// Machine: DESKTOP-IITN2G2
// Generator: EntityCreator v1.0
// Class Name: ViewModelWriter
// </auto-generated>

using System;
using System.ComponentModel.DataAnnotations;

namespace SeramikStore.Web.ViewModels.Category
{
    public class CategoryCreateViewModel
    {
        [Required]
        [Display(Name = "Name")]
        public string Name { get; set; }

    }
}
