// <auto-generated>
// This file is generated. Do not edit manually.
// Generated at      : 2026-01-18 00:41:40
// Generated at (UTC): 2026-01-17 21:41:40
// Machine: DESKTOP-IITN2G2
// Generator: EntityCreator v1.0
// Class Name: EntityWriter
// </auto-generated>

using System;

namespace SeramikStore.Entities
{
    public class Category
    {
        // Identity
        public int Id { get; set; }
        public required string Name { get; set; }
        public bool IsActive { get; set; }
    }
}
