// <auto-generated>
// This file is generated. Do not edit manually.
// Generated at      : 2026-01-19 17:47:46
// Generated at (UTC): 2026-01-19 14:47:46
// Machine: YAZILIM3
// Generator: EntityCreator v1.0
// Class Name: EntityWriter
// </auto-generated>

using System;

namespace SeramikStore.Entities
{
    public class Category
    {
        // Identity
        public int Id { get; set; }
        public required string Name { get; set; }
        public bool IsActive { get; set; }
    }
}
