// <auto-generated>
// This file is generated. Do not edit manually.
// Generated at      : 2026-01-28 17:57:09
// Generated at (UTC): 2026-01-28 14:57:09
// Machine: YAZILIM3
// Generator: EntityCreator v1.0
// Class Name: EntityWriter
// </auto-generated>

#nullable enable

using System;

namespace SeramikStore.Entities
{
    public class Potansiyel
    {
        // Identity
        public int Id { get; set; }
        public required string Name { get; set; }
        public required string SurName { get; set; }
        public required string KnownName { get; set; }
        public required string Email { get; set; }
        public required string PhoneNumber { get; set; }
        public int Adress { get; set; }
        public DateOnly? tarih { get; set; }
        public DateTime? kayıttarihi { get; set; }
        public TimeOnly? OzelSaatBilgisi { get; set; }
        public string? SatirAciklamasi { get; set; }
        public string? GenisAciklama { get; set; }
        public decimal? Fiyat { get; set; }
        public DateTime? InsertDate { get; set; }
        public DateTime? UpdateDate { get; set; }
        public bool? IsActive { get; set; }
    }
}
