// <auto-generated>
// This file is generated. Do not edit manually.
// Generated at      : 2026-02-19 17:07:06
// Generated at (UTC): 2026-02-19 14:07:06
// Machine: YAZILIM3
// Generator: EntityCreator v1.0
// Class Name: EntityWriter
// </auto-generated>

#nullable enable

using System;

namespace SeramikStore.Entities
{
    public class Tasit
    {
        // Identity
        public int Id { get; set; }
        public required string Aciklama { get; set; }
        public int Tipi { get; set; }
        public required string PlakaKodu { get; set; }
        public string? Sehir { get; set; }
    }
}
