// <auto-generated>
// This file is generated. Do not edit manually.
// Generated at      : 2026-01-23 16:35:21
// Generated at (UTC): 2026-01-23 13:35:21
// Machine: YAZILIM3
// Generator: EntityCreator v1.0
// Class Name: EntityWriter
// </auto-generated>

#nullable enable

using System;

namespace SeramikStore.Entities
{
    public class XEROX
    {
        // Identity
        public int Id { get; set; }
        public long? BigId { get; set; }
        public Guid UniqueId { get; set; }
        public int? IntValue { get; set; }
        public short? SmallIntValue { get; set; }
        public byte? TinyIntValue { get; set; }
        public bool? BitValue { get; set; }
        public decimal? DecimalValue { get; set; }
        public decimal? NumericValue { get; set; }
        public decimal? MoneyValue { get; set; }
        public decimal? SmallMoneyValue { get; set; }
        public double? FloatValue { get; set; }
        public float? RealValue { get; set; }
        public DateOnly? DateValue { get; set; }
        public TimeOnly? TimeValue { get; set; }
        public DateTime? DateTimeValue { get; set; }
        public DateTime? SmallDateTimeValue { get; set; }
        public DateTime? DateTime2Value { get; set; }
        public DateTimeOffset? DateTimeOffsetValue { get; set; }
        public string? CharValue { get; set; }
        public string? VarCharValue { get; set; }
        public string? VarCharMaxValue { get; set; }
        public string? NCharValue { get; set; }
        public string? NVarCharValue { get; set; }
        public string? NVarCharMaxValue { get; set; }
        public string? NTextValue { get; set; }
        public byte[]? BinaryValue { get; set; }
        public byte[]? VarBinaryValue { get; set; }
        public byte[]? VarBinaryMaxValue { get; set; }
        public byte[]? ImageValue { get; set; }
        public string? XmlValue { get; set; }
        public object? SqlVariantValue { get; set; }
        public byte[] RowVersionValue { get; set; }
        public object? HierarchyIdValue { get; set; }
        public object? GeographyValue { get; set; }
        public object? GeometryValue { get; set; }
        public bool IsActive { get; set; }
        public DateTime InsertDate { get; set; }
        public DateTime? UpdateDate { get; set; }
    }
}
