using System.Text;
using System.ComponentModel.DataAnnotations;

public static class ViewModelWriter
{
    public static Dictionary<string, string> GenerateViewModels(
        string baseNamespace,
        string entity,
        List<DbColumn> cols)
    {
        return new()
        {
            [$"{entity}ViewModel.generated.cs"] =
                GenerateViewModel(baseNamespace, entity, cols),

            [$"{entity}CreateViewModel.generated.cs"] =
                GenerateCreateViewModel(baseNamespace, entity, cols),

            [$"{entity}UpdateViewModel.generated.cs"] =
                GenerateUpdateViewModel(baseNamespace, entity, cols),

            [$"{entity}ListViewModel.generated.cs"] =
                GenerateListViewModel(baseNamespace, entity, cols)
        };
    }

    // ---------------- BASE VIEW MODEL ----------------
    static string GenerateViewModel(string ns, string entity, List<DbColumn> cols)
    {
        var sb = Start(ns, $"{entity}ViewModel");
        foreach (var c in cols)
            AppendProperty(sb, c);
        return End(sb);
    }

    // ---------------- CREATE VIEW MODEL ----------------
    static string GenerateCreateViewModel(string ns, string entity, List<DbColumn> cols)
    {
        var sb = Start(ns, $"{entity}CreateViewModel");
        foreach (var c in cols.Where(c =>
                     !c.IsIdentity &&
                     !c.IsInsertDate() &&
                     !c.IsUpdateDate() &&
                     !c.IsIsActive()))
        {
            AppendProperty(sb, c);
        }
        return End(sb);
    }

    // ---------------- UPDATE VIEW MODEL ----------------
    static string GenerateUpdateViewModel(string ns, string entity, List<DbColumn> cols)
    {
        var sb = Start(ns, $"{entity}UpdateViewModel");
        foreach (var c in cols.Where(c => !c.IsInsertDate()))
            AppendProperty(sb, c);
        return End(sb);
    }

    // ---------------- LIST VIEW MODEL ----------------
    static string GenerateListViewModel(string ns, string entity, List<DbColumn> cols)
    {
        var sb = Start(ns, $"{entity}ListViewModel");
        foreach (var c in cols.Where(c => !c.IsUpdateDate()))
            AppendProperty(sb, c);
        return End(sb);
    }

    // ---------------- PROPERTY HELPER ----------------
    static void AppendProperty(StringBuilder sb, DbColumn c)
    {
        var typeInfo = SqlTypeMapper.Map(c.SqlType);

        var isNullable =
            !typeInfo.IsNeverNullable &&
            (c.IsNullable || typeInfo.IsReferenceType);

        // ===== [Required] sadece nullable olmayan reference type =====
        if (typeInfo.IsReferenceType && !isNullable)
            sb.AppendLine("        [Required]");

        sb.AppendLine($"        [Display(Name = \"{c.Name}\")]");

        var clrType = typeInfo.ClrType;

        if (isNullable && !typeInfo.IsReferenceType)
            clrType += "?";

        if (isNullable && typeInfo.IsReferenceType)
            clrType += "?";

        sb.AppendLine($"        public {clrType} {c.Name} {{ get; set; }}");
        sb.AppendLine();
    }

    // ---------------- TEMPLATE HELPERS ----------------
    static StringBuilder Start(string ns, string className)
    {
        var sb = new StringBuilder();
        EntityCreator.Helper.AppendAutoGeneratedHeader(sb, nameof(ViewModelWriter));
        sb.AppendLine("using System;");
        sb.AppendLine("using System.ComponentModel.DataAnnotations;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns}");
        sb.AppendLine("{");
        sb.AppendLine($"    public class {className}");
        sb.AppendLine("    {");
        return sb;
    }

    static string End(StringBuilder sb)
    {
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }
}
