using System.Reflection;
using System.Text;

public static class ControllerWriter
{
    public static string GenerateController(
        string controllerNamespace,
        string entity,
        string serviceNamespace,
        string viewModelNamespace,
        string contractsNamespace,
        List<DbColumn> cols)
    {
        var sb = new StringBuilder();
        EntityCreator.Helper.AppendAutoGeneratedHeader(sb, nameof(ControllerWriter));

        sb.AppendLine("using Microsoft.AspNetCore.Mvc;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine($"using {serviceNamespace};");
        sb.AppendLine($"using {contractsNamespace};");
        sb.AppendLine($"using {viewModelNamespace};");
        sb.AppendLine();

        sb.AppendLine($"namespace {controllerNamespace}");
        sb.AppendLine("{");
        sb.AppendLine($"    public partial class {entity}Controller : Controller");
        sb.AppendLine("    {");

        var serviceField = $"_{char.ToLowerInvariant(entity[0])}{entity[1..]}Service";

        //sb.AppendLine($"        private readonly I{entity}Service {serviceField};");
        //sb.AppendLine();
        //sb.AppendLine($"        public {entity}Controller(I{entity}Service service)");
        //sb.AppendLine("        {");
        //sb.AppendLine($"            {serviceField} = service;");
        //sb.AppendLine("        }");
        sb.AppendLine();

        AppendIndex(sb, entity, serviceField, cols);
        AppendDetail(sb, entity, serviceField, cols);
        AppendCreate(sb, entity, serviceField, cols);
        AppendEdit(sb, entity, serviceField, cols);
        AppendDelete(sb, entity, serviceField, cols);

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    // ================= INDEX =================
    static void AppendIndex(
        StringBuilder sb,
        string entity,
        string serviceField,
        List<DbColumn> cols)
    {
        sb.AppendLine("        public IActionResult Index()");
        sb.AppendLine("        {");
        sb.AppendLine($"            var list = {serviceField}.List();");
        sb.AppendLine($"            var vm = list.Select(x => new {entity}ListViewModel");
        sb.AppendLine("            {");

        foreach (var c in cols.Where(c =>
            !c.IsInsertDate() &&
            !c.IsUpdateDate() &&
            !c.IsIsActive()
        ))
            sb.AppendLine($"                {c.Name} = x.{c.Name},");

        sb.AppendLine("            }).ToList();");
        sb.AppendLine();
        sb.AppendLine("            return View(vm);");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    // ================= DETAIL =================
    static void AppendDetail(
        StringBuilder sb,
        string entity,
        string serviceField,
        List<DbColumn> cols)
    {
        var id = cols.First(c => c.IsIdentity);

        sb.AppendLine("        public IActionResult Detail(int id)");
        sb.AppendLine("        {");
        sb.AppendLine($"            var dto = {serviceField}.GetById(id);");
        sb.AppendLine("            if (dto == null)");
        sb.AppendLine("                return NotFound();");
        sb.AppendLine();
        sb.AppendLine($"            var vm = new {entity}ViewModel");
        sb.AppendLine("            {");
        foreach (var c in cols.Where(c =>
            !c.IsInsertDate() &&
            !c.IsUpdateDate() &&
            !c.IsIsActive()
        ))
            sb.AppendLine($"                {c.Name} = dto.{c.Name},");
        sb.AppendLine("            };");
        sb.AppendLine();
        sb.AppendLine("            return View(vm);");
        sb.AppendLine("        }");
        sb.AppendLine();
    }


    // ================= CREATE =================
    static void AppendCreate(
        StringBuilder sb,
        string entity,
        string serviceField,
        List<DbColumn> cols)
    {
        sb.AppendLine("        public IActionResult Create()");
        sb.AppendLine("        {");
        sb.AppendLine($"            return View(new {entity}CreateViewModel());");
        sb.AppendLine("        }");
        sb.AppendLine();

        sb.AppendLine("        [HttpPost]");
        sb.AppendLine("        [ValidateAntiForgeryToken]");
        sb.AppendLine($"        public IActionResult Create({entity}CreateViewModel vm)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (!ModelState.IsValid)");
        sb.AppendLine("                return View(vm);");
        sb.AppendLine();
        sb.AppendLine($"            {serviceField}.Create(new {entity}CreateDto");
        sb.AppendLine("            {");

        foreach (var c in cols.Where(c =>
                     !c.IsIdentity &&
                     !c.IsInsertDate() &&
                     !c.IsUpdateDate() &&
                     !c.IsIsActive()))
        {
            var typeInfo = SqlTypeMapper.Map(c.SqlType);

            // SQL NOT NULL ? bilinçli unwrap
            if (!c.IsNullable && !typeInfo.IsNeverNullable)
            {
                if (typeInfo.IsReferenceType)
                {
                    sb.AppendLine($"                {c.Name} = vm.{c.Name}!,");
                }
                else
                {
                    sb.AppendLine($"                {c.Name} = vm.{c.Name}!.Value,");
                }
            }
            else
            {
                // SQL NULL ? direkt geç
                sb.AppendLine($"                {c.Name} = vm.{c.Name},");
            }
        }

        sb.AppendLine("            });");
        sb.AppendLine();
        sb.AppendLine("            return RedirectToAction(nameof(Index));");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    // ================= EDIT =================
    static void AppendEdit(
        StringBuilder sb,
        string entity,
        string serviceField,
        List<DbColumn> cols)
    {
        var id = cols.First(c => c.IsIdentity);

        sb.AppendLine("        public IActionResult Edit(int id)");
        sb.AppendLine("        {");
        sb.AppendLine($"            var dto = {serviceField}.GetById(id);");
        sb.AppendLine("            if (dto == null)");
        sb.AppendLine("                return NotFound();");
        sb.AppendLine();
        sb.AppendLine($"            return View(new {entity}UpdateViewModel");
        sb.AppendLine("            {");


        foreach (var c in cols.Where(c =>
             !c.IsInsertDate() &&
             !c.IsUpdateDate() &&
             !c.IsIsActive()))
        {
            sb.AppendLine($"                {c.Name} = dto.{c.Name},");
        }

        sb.AppendLine("            });");
        sb.AppendLine("        }");
        sb.AppendLine();

        sb.AppendLine("        [HttpPost]");
        sb.AppendLine("        [ValidateAntiForgeryToken]");
        sb.AppendLine($"        public IActionResult Edit({entity}UpdateViewModel vm)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (!ModelState.IsValid)");
        sb.AppendLine("                return View(vm);");
        sb.AppendLine();
        sb.AppendLine($"            {serviceField}.Update(new {entity}UpdateDto");
        sb.AppendLine("            {");

        foreach (var c in cols.Where(c =>
             !c.IsInsertDate() &&
             !c.IsUpdateDate() &&
             !c.IsIsActive()))
        {
            
            var typeInfo = SqlTypeMapper.Map(c.SqlType);

            // SQL NOT NULL ? bilinçli unwrap
            if (!c.IsNullable && !typeInfo.IsNeverNullable)
            {
                if (typeInfo.IsReferenceType)
                {
                    sb.AppendLine($"                {c.Name} = vm.{c.Name}!,");
                }
                else
                {
                    sb.AppendLine($"                {c.Name} = vm.{c.Name}!.Value,");
                }
            }
            else
            {
                // SQL NULL ? direkt geç
                sb.AppendLine($"                {c.Name} = vm.{c.Name},");
            }




        }

        sb.AppendLine("            });");
        sb.AppendLine();
        sb.AppendLine("            return RedirectToAction(nameof(Index));");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    // ================= DELETE =================
    static void AppendDelete(
        StringBuilder sb,
        string entity,
        string serviceField,
        List<DbColumn> cols)
    {
        var id = cols.First(c => c.IsIdentity);

        sb.AppendLine("        public IActionResult Delete(int id)");
        sb.AppendLine("        {");
        sb.AppendLine($"            var dto = {serviceField}.GetById(id);");
        sb.AppendLine("            if (dto == null)");
        sb.AppendLine("                return NotFound();");
        sb.AppendLine();
        sb.AppendLine($"            var vm = new {entity}ViewModel");
        sb.AppendLine("            {");

        foreach (var c in cols.Where(c =>
            !c.IsInsertDate() &&
            !c.IsUpdateDate() &&
            !c.IsIsActive()
        ))
            sb.AppendLine($"                {c.Name} = dto.{c.Name},");

        sb.AppendLine("            };");
        sb.AppendLine();
        sb.AppendLine("            return View(vm);");
        sb.AppendLine("        }");
        sb.AppendLine();

        sb.AppendLine("        [HttpPost, ActionName(\"DeleteConfirmed\")]");
        sb.AppendLine("        [ValidateAntiForgeryToken]");
        sb.AppendLine("        public IActionResult DeleteConfirmed(int id)");
        sb.AppendLine("        {");
        sb.AppendLine($"            {serviceField}.Delete(id);");
        sb.AppendLine("            return RedirectToAction(nameof(Index));");
        sb.AppendLine("        }");
        sb.AppendLine();
    }
}
