using System.Text;

public static class ControllerWriter
{
    public static string GenerateController(
        string controllerNamespace,
        string entity,
        string serviceNamespace,
        string viewModelNamespace,
        string contractsNamespace)
    {
        var sb = new StringBuilder();

        EntityCreator.Helper.AppendAutoGeneratedHeader(sb, nameof(ControllerWriter));

        sb.AppendLine("using Microsoft.AspNetCore.Mvc;");
        sb.AppendLine($"using {serviceNamespace};");
        sb.AppendLine($"using {contractsNamespace};");
        
        sb.AppendLine($"using {viewModelNamespace};");
        sb.AppendLine();
        sb.AppendLine($"namespace {controllerNamespace}");
        sb.AppendLine("{");
        sb.AppendLine($"    public partial class {entity}Controller : Controller");
        sb.AppendLine("    {");
        sb.AppendLine($"        private readonly I{entity}Service _{entity.ToLower()}Service;");
        sb.AppendLine();
        sb.AppendLine($"        public {entity}Controller(I{entity}Service {entity.ToLower()}Service)");
        sb.AppendLine("        {");
        sb.AppendLine($"            _{entity.ToLower()}Service = {entity.ToLower()}Service;");
        sb.AppendLine("        }");
        sb.AppendLine();

        AppendIndex(sb, entity);
        AppendCreate(sb, entity);
        AppendEdit(sb, entity);
        AppendDelete(sb, entity);

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    // ================= INDEX =================
    static void AppendIndex(StringBuilder sb, string entity)
    {
        sb.AppendLine("        // LIST");
        sb.AppendLine("        public IActionResult Index()");
        sb.AppendLine("        {");
        sb.AppendLine($"            var list = _{entity.ToLower()}Service.List();");
        sb.AppendLine($"            var vm = list.Select(x => new {entity}ListViewModel");
        sb.AppendLine("            {");
        sb.AppendLine("                Id = x.Id,");
        sb.AppendLine("                Name = x.Name,");
        sb.AppendLine("                IsActive = x.IsActive");
        sb.AppendLine("            }).ToList();");
        sb.AppendLine();
        sb.AppendLine("            return View(vm);");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    // ================= CREATE =================
    static void AppendCreate(StringBuilder sb, string entity)
    {
        sb.AppendLine("        // CREATE (GET)");
        sb.AppendLine("        public IActionResult Create()");
        sb.AppendLine("        {");
        sb.AppendLine($"            return View(new {entity}CreateViewModel());");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        // CREATE (POST)");
        sb.AppendLine("        [HttpPost]");
        sb.AppendLine("        [ValidateAntiForgeryToken]");
        sb.AppendLine($"        public IActionResult Create({entity}CreateViewModel vm)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (!ModelState.IsValid)");
        sb.AppendLine("                return View(vm);");
        sb.AppendLine();
        sb.AppendLine($"            _{entity.ToLower()}Service.Create(new {entity}CreateDto");
        sb.AppendLine("            {");
        sb.AppendLine("                Name = vm.Name");
        sb.AppendLine("            });");
        sb.AppendLine();
        sb.AppendLine("            return RedirectToAction(nameof(Index));");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    // ================= EDIT =================
    static void AppendEdit(StringBuilder sb, string entity)
    {
        sb.AppendLine("        // EDIT (GET)");
        sb.AppendLine("        public IActionResult Edit(int id)");
        sb.AppendLine("        {");
        sb.AppendLine($"            var item = _{entity.ToLower()}Service.GetById(id);");
        sb.AppendLine("            if (item == null)");
        sb.AppendLine("                return NotFound();");
        sb.AppendLine();
        sb.AppendLine($"            return View(new {entity}UpdateViewModel");
        sb.AppendLine("            {");
        sb.AppendLine("                Id = item.Id,");
        sb.AppendLine("                Name = item.Name,");
        sb.AppendLine("                IsActive = item.IsActive");
        sb.AppendLine("            });");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        // EDIT (POST)");
        sb.AppendLine("        [HttpPost]");
        sb.AppendLine("        [ValidateAntiForgeryToken]");
        sb.AppendLine($"        public IActionResult Edit({entity}UpdateViewModel vm)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (!ModelState.IsValid)");
        sb.AppendLine("                return View(vm);");
        sb.AppendLine();
        sb.AppendLine($"            _{entity.ToLower()}Service.Update(new {entity}UpdateDto");
        sb.AppendLine("            {");
        sb.AppendLine("                Id = vm.Id,");
        sb.AppendLine("                Name = vm.Name,");
        sb.AppendLine("                IsActive = vm.IsActive");
        sb.AppendLine("            });");
        sb.AppendLine();
        sb.AppendLine("            return RedirectToAction(nameof(Index));");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    // ================= DELETE =================
    static void AppendDelete(StringBuilder sb, string entity)
    {
        var serviceField = $"_{entity.ToLower()}Service";

        // DELETE (GET)
        sb.AppendLine("        // DELETE (GET)");
        sb.AppendLine("        public IActionResult Delete(int id)");
        sb.AppendLine("        {");
        sb.AppendLine($"            var dto = {serviceField}.GetById(id);");
        sb.AppendLine("            if (dto == null)");
        sb.AppendLine("                return NotFound();");
        sb.AppendLine();
        sb.AppendLine($"            var vm = new {entity}ViewModel");
        sb.AppendLine("            {");
        sb.AppendLine("                Id = dto.Id,");
        sb.AppendLine("                Name = dto.Name,");
        sb.AppendLine("                IsActive = dto.IsActive");
        sb.AppendLine("            };");
        sb.AppendLine();
        sb.AppendLine("            return View(vm);");
        sb.AppendLine("        }");
        sb.AppendLine();

        // DELETE (POST)
        sb.AppendLine("        // DELETE (POST)");
        sb.AppendLine("        [HttpPost, ActionName(\"DeleteConfirmed\")]");
        sb.AppendLine("        [ValidateAntiForgeryToken]");
        sb.AppendLine("        public IActionResult DeleteConfirmed(int id)");
        sb.AppendLine("        {");
        sb.AppendLine($"            {serviceField}.Delete(id);");
        sb.AppendLine("            return RedirectToAction(nameof(Index));");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

}
