using System.Text;

public static class DtoWriter
{
    public static Dictionary<string, string> GenerateDtos(
        string baseNamespace,
        string entity,
        List<DbColumn> cols)
    {
        var result = new Dictionary<string, string>();

        result.Add($"{entity}Dto.generated.cs", GenerateDto(baseNamespace, entity, cols));
        result.Add($"{entity}CreateDto.generated.cs", GenerateCreateDto(baseNamespace, entity, cols));
        result.Add($"{entity}UpdateDto.generated.cs", GenerateUpdateDto(baseNamespace, entity, cols));
        result.Add($"{entity}ListItemDto.generated.cs", GenerateListItemDto(baseNamespace, entity, cols));

        return result;
    }

    // ---------------- DTO ----------------
    static string GenerateDto(string ns, string entity, List<DbColumn> cols)
    {
        var sb = new StringBuilder();
        EntityCreator.Helper.AppendAutoGeneratedHeader(sb, nameof(DtoWriter));
        sb.AppendLine("using System;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns}");
        sb.AppendLine("{");
        sb.AppendLine($"    public class {entity}Dto");
        sb.AppendLine("    {");

        foreach (var c in cols)
            sb.AppendLine($"        public {MapClr(c)} {c.Name} {{ get; set; }}");

        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    // ---------------- CREATE DTO ----------------
    static string GenerateCreateDto(string ns, string entity, List<DbColumn> cols)
    {
        var sb = new StringBuilder();
        EntityCreator.Helper.AppendAutoGeneratedHeader(sb, nameof(DtoWriter));
        sb.AppendLine("using System;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns}");
        sb.AppendLine("{");
        sb.AppendLine($"    public class {entity}CreateDto");
        sb.AppendLine("    {");

        foreach (var c in cols.Where(c =>
                     !c.IsIdentity &&
                     !c.IsInsertDate() &&
                     !c.IsUpdateDate() &&
                     !c.IsIsActive()))
        {
            sb.AppendLine($"        public {MapClr(c)} {c.Name} {{ get; set; }}");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    // ---------------- UPDATE DTO ----------------
    static string GenerateUpdateDto(string ns, string entity, List<DbColumn> cols)
    {
        var sb = new StringBuilder();
        EntityCreator.Helper.AppendAutoGeneratedHeader(sb, nameof(DtoWriter));
        sb.AppendLine("using System;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns}");
        sb.AppendLine("{");
        sb.AppendLine($"    public class {entity}UpdateDto");
        sb.AppendLine("    {");

        foreach (var c in cols.Where(c => !c.IsInsertDate()))
            sb.AppendLine($"        public {MapClr(c)} {c.Name} {{ get; set; }}");

        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    // ---------------- LIST ITEM DTO ----------------
    static string GenerateListItemDto(string ns, string entity, List<DbColumn> cols)
    {
        var sb = new StringBuilder();
        EntityCreator.Helper.AppendAutoGeneratedHeader(sb, nameof(DtoWriter));
        sb.AppendLine("using System;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns}");
        sb.AppendLine("{");
        sb.AppendLine($"    public class {entity}ListItemDto");
        sb.AppendLine("    {");

        foreach (var c in cols.Where(c => !c.IsUpdateDate()))
            sb.AppendLine($"        public {MapClr(c)} {c.Name} {{ get; set; }}");

        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    static string MapClr(DbColumn c) =>
        c.SqlType switch
        {
            "int" => "int",
            "bit" => "bool",
            "decimal" => "decimal",
            "datetime" => "DateTime",
            _ => "string"
        };
}
