using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace EntityCreator
{
    public class Helper
    {
        public static void AppendAutoGeneratedHeader(StringBuilder sb, string className)
        {
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// This file is generated. Do not edit manually.");
            sb.AppendLine($"// Generated at      : {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            sb.AppendLine($"// Generated at (UTC): {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss}");
            sb.AppendLine($"// Machine: {Environment.MachineName}");
            sb.AppendLine($"// Generator: EntityCreator v1.0");
            sb.AppendLine($"// Class Name: {className}");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
        }
        public static void AppendAutoGeneratedHeaderForSQL(StringBuilder sb, string className)
        {
            sb.AppendLine("-- <auto-generated>");
            sb.AppendLine("-- This file is generated. Do not edit manually.");
            sb.AppendLine($"-- Generated at      : {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            sb.AppendLine($"-- Generated at (UTC): {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss}");
            sb.AppendLine($"-- Machine: {Environment.MachineName}");
            sb.AppendLine($"-- Generator: EntityCreator v1.0");
            sb.AppendLine($"-- Class Name: {className}");
            sb.AppendLine("-- </auto-generated>");
            sb.AppendLine();
        }
    }
}
