using System.Text;
using System.ComponentModel.DataAnnotations;

public static class ViewModelWriter
{
    public static Dictionary<string, string> GenerateViewModels(
        string baseNamespace,
        string entity,
        List<DbColumn> cols)
    {
        var result = new Dictionary<string, string>();

        result.Add($"{entity}ViewModel.generated.cs",
            GenerateViewModel(baseNamespace, entity, cols));

        result.Add($"{entity}CreateViewModel.generated.cs",
            GenerateCreateViewModel(baseNamespace, entity, cols));

        result.Add($"{entity}UpdateViewModel.generated.cs",
            GenerateUpdateViewModel(baseNamespace, entity, cols));

        result.Add($"{entity}ListViewModel.generated.cs",
            GenerateListViewModel(baseNamespace, entity, cols));

        return result;
    }

    // ---------------- BASE VIEW MODEL ----------------
    static string GenerateViewModel(string ns, string entity, List<DbColumn> cols)
    {
        var sb = new StringBuilder();
        EntityCreator.Helper.AppendAutoGeneratedHeader(sb, nameof(ViewModelWriter));
        sb.AppendLine("using System;");
        sb.AppendLine("using System.ComponentModel.DataAnnotations;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns}");
        sb.AppendLine("{");
        sb.AppendLine($"    public class {entity}ViewModel");
        sb.AppendLine("    {");
        foreach (var c in cols)
            AppendProperty(sb, c);
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    // ---------------- CREATE VIEW MODEL ----------------
    static string GenerateCreateViewModel(string ns, string entity, List<DbColumn> cols)
    {
        var sb = new StringBuilder();
        EntityCreator.Helper.AppendAutoGeneratedHeader(sb, nameof(ViewModelWriter));
        sb.AppendLine("using System;");
        sb.AppendLine("using System.ComponentModel.DataAnnotations;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns}");
        sb.AppendLine("{");
        sb.AppendLine($"    public class {entity}CreateViewModel");
        sb.AppendLine("    {");

        foreach (var c in cols.Where(c =>
                     !c.IsIdentity &&
                     !c.IsInsertDate() &&
                     !c.IsUpdateDate() &&
                     !c.IsIsActive()))
        {
            AppendProperty(sb, c);
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    // ---------------- UPDATE VIEW MODEL ----------------
    static string GenerateUpdateViewModel(string ns, string entity, List<DbColumn> cols)
    {
        var sb = new StringBuilder();
        EntityCreator.Helper.AppendAutoGeneratedHeader(sb, nameof(ViewModelWriter));
        sb.AppendLine("using System;");
        sb.AppendLine("using System.ComponentModel.DataAnnotations;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns}");
        sb.AppendLine("{");
        sb.AppendLine($"    public class {entity}UpdateViewModel");
        sb.AppendLine("    {");

        foreach (var c in cols.Where(c => !c.IsInsertDate()))
            AppendProperty(sb, c);

        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    // ---------------- LIST VIEW MODEL ----------------
    static string GenerateListViewModel(string ns, string entity, List<DbColumn> cols)
    {
        var sb = new StringBuilder();
        EntityCreator.Helper.AppendAutoGeneratedHeader(sb, nameof(ViewModelWriter));
        sb.AppendLine("using System;");
        sb.AppendLine("using System.ComponentModel.DataAnnotations;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns}");
        sb.AppendLine("{");
        sb.AppendLine($"    public class {entity}ListViewModel");
        sb.AppendLine("    {");

        foreach (var c in cols.Where(c => !c.IsUpdateDate()))
            AppendProperty(sb, c);

        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    // ---------------- PROPERTY HELPER ----------------
    static void AppendProperty(StringBuilder sb, DbColumn c)
    {
        if (!c.IsNullable && MapClr(c) == "string")
            sb.AppendLine("        [Required]");

        sb.AppendLine($"        [Display(Name = \"{c.Name}\")]");
        sb.AppendLine($"        public {MapClr(c)} {c.Name} {{ get; set; }}");
        sb.AppendLine();
    }

    static string MapClr(DbColumn c) =>
        c.SqlType switch
        {
            "int" => c.IsNullable ? "int?" : "int",
            "bit" => c.IsNullable ? "bool?" : "bool",
            "decimal" => c.IsNullable ? "decimal?" : "decimal",
            "datetime" => c.IsNullable ? "DateTime?" : "DateTime",
            _ => "string"
        };
}
