using System.Text;

public static class ViewWriter
{
    public static Dictionary<string, string> GenerateViews(
        string entity,
        string viewModelNamespace,
        List<DbColumn> cols)
    {
        return new()
        {
            { "Index.cshtml",  GenerateIndex(entity, viewModelNamespace, cols) },
            { "Create.cshtml", GenerateCreate(entity, viewModelNamespace, cols) },
            { "Edit.cshtml",   GenerateEdit(entity, viewModelNamespace, cols) },
            { "Delete.cshtml", GenerateDelete(entity, viewModelNamespace, cols) },
            { "Detail.cshtml", GenerateDetails(entity, viewModelNamespace, cols) }
        };
    }

    // ================= INDEX =================
    static string GenerateIndex(string entity, string vmNs, List<DbColumn> cols)
    {
        var sb = new StringBuilder();
        EntityCreator.Helper.AppendAutoGeneratedHeaderForView(sb, nameof(ViewWriter));

        sb.AppendLine($"@model IEnumerable<{vmNs}.{entity}ListViewModel>");
        sb.AppendLine();
        sb.AppendLine($"<h2>{entity} Listesi</h2>");

        sb.AppendLine("""
<a asp-action="Create" class="btn btn-sm btn-outline-success rounded-pill px-4 mb-3">
    <i class="fa fa-file me-1"></i>New
</a>
""");

        sb.AppendLine("<table class=\"table table-bordered\">");
        sb.AppendLine("<thead><tr>");

        foreach (var c in cols)
            sb.AppendLine($"<th>{c.Name}</th>");

        sb.AppendLine("<th style=\"width:200px\"></th>");
        sb.AppendLine("</tr></thead>");
        sb.AppendLine("<tbody>");

        sb.AppendLine("@foreach (var item in Model)");
        sb.AppendLine("{");
        sb.AppendLine("<tr>");

        foreach (var c in cols)
            sb.AppendLine($"<td>@item.{c.Name}</td>");

        sb.AppendLine("""
<td class="text-nowrap">
    <a class="btn btn-sm btn-outline-warning rounded-pill px-3 me-1"
       asp-action="Edit"
       asp-route-id="@item.Id">
        <i class="fa fa-edit me-1"></i>Edit
    </a>

    <a class="btn btn-sm btn-outline-primary rounded-pill px-3 me-1"
       asp-action="Detail"
       asp-route-id="@item.Id">
        <i class="fa fa-eye me-1"></i>Detail
    </a>

    <a class="btn btn-sm btn-outline-danger rounded-pill px-3"
       asp-action="Delete"
       asp-route-id="@item.Id">
        <i class="fa fa-trash me-1"></i>Delete
    </a>
</td>
""");

        sb.AppendLine("</tr>");
        sb.AppendLine("}");
        sb.AppendLine("</tbody></table>");

        return sb.ToString();
    }

    // ================= CREATE =================
    static string GenerateCreate(string entity, string vmNs, List<DbColumn> cols)
    {
        var sb = new StringBuilder();
        EntityCreator.Helper.AppendAutoGeneratedHeaderForView(sb, nameof(ViewWriter));

        sb.AppendLine($"@model {vmNs}.{entity}CreateViewModel");
        sb.AppendLine();
        sb.AppendLine($"<h2>{entity} Yeni</h2>");

        sb.AppendLine("""
<form asp-action="Create" method="post">
    @Html.AntiForgeryToken()
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
""");

        foreach (var c in cols.Where(c =>
                     !c.IsIdentity &&
                     !c.IsInsertDate() &&
                     !c.IsUpdateDate() &&
                     !c.IsIsActive()))
        {
            sb.AppendLine($"""
    <div class="mb-3">
        <label asp-for="{c.Name}" class="form-label"></label>
        <input asp-for="{c.Name}" class="form-control" />
        <span asp-validation-for="{c.Name}" class="text-danger"></span>
    </div>
""");
        }

        sb.AppendLine("""
    <button type="submit" class="btn btn-sm btn-outline-success rounded-pill px-4 me-2">
        <i class="fa fa-save me-1"></i>Save
    </button>

    <a asp-action="Index" class="btn btn-sm btn-outline-dark rounded-pill px-4">
        <i class="fa fa-times me-1"></i>Cancel
    </a>
</form>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}
""");

        return sb.ToString();
    }

    // ================= EDIT =================
    static string GenerateEdit(string entity, string vmNs, List<DbColumn> cols)
    {
        var sb = new StringBuilder();
        EntityCreator.Helper.AppendAutoGeneratedHeaderForView(sb, nameof(ViewWriter));

        sb.AppendLine($"@model {vmNs}.{entity}UpdateViewModel");
        sb.AppendLine();
        sb.AppendLine($"<h2>{entity} Düzenle</h2>");

        sb.AppendLine("""
<form asp-action="Edit" method="post">
    @Html.AntiForgeryToken()
    <input type="hidden" asp-for="Id" />
""");

        foreach (var c in cols.Where(c =>
                     !c.IsIdentity &&
                     !c.IsInsertDate() &&
                     !c.IsUpdateDate() &&
                     !c.IsIsActive() &&
                     c.Name != "Id"))
        {
            sb.AppendLine($"""
    <div class="mb-3">
        <label asp-for="{c.Name}" class="form-label"></label>
        <input asp-for="{c.Name}" class="form-control" />
        <span asp-validation-for="{c.Name}" class="text-danger"></span>
    </div>
""");
        }

        sb.AppendLine("""
    <button type="submit" class="btn btn-sm btn-outline-success rounded-pill px-4 me-2">
        <i class="fa fa-save me-1"></i>Save
    </button>

    <a asp-action="Index" class="btn btn-sm btn-outline-dark rounded-pill px-4">
        <i class="fa fa-times me-1"></i>Cancel
    </a>
</form>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}
""");

        return sb.ToString();
    }

    // ================= DELETE =================
    static string GenerateDelete(string entity, string vmNs, List<DbColumn> cols)
    {
        var sb = new StringBuilder();
        EntityCreator.Helper.AppendAutoGeneratedHeaderForView(sb, nameof(ViewWriter));

        sb.AppendLine($"@model {vmNs}.{entity}ViewModel");
        sb.AppendLine();
        sb.AppendLine($"<h2>{entity} Sil</h2>");

        sb.AppendLine("""
<div class="alert alert-danger">
    Silmek istediğinize emin misiniz?
</div>

<dl class="row">
""");

        foreach (var c in cols)
        {
            sb.AppendLine($"""
    <dt class="col-sm-3">{c.Name}</dt>
    <dd class="col-sm-9">@Model.{c.Name}</dd>
""");
        }

        sb.AppendLine("""
</dl>

<form asp-action="DeleteConfirmed" method="post">
    @Html.AntiForgeryToken()
    <input type="hidden" asp-for="Id" />

    <button type="submit" class="btn btn-sm btn-outline-danger rounded-pill px-4 me-2">
        <i class="fa fa-trash me-1"></i>Delete
    </button>

    <a asp-action="Index" class="btn btn-sm btn-outline-dark rounded-pill px-4">
        <i class="fa fa-times me-1"></i>Cancel
    </a>
</form>
""");

        return sb.ToString();
    }

    // ================= DETAILS =================
    static string GenerateDetails(string entity, string vmNs, List<DbColumn> cols)
    {
        var sb = new StringBuilder();
        EntityCreator.Helper.AppendAutoGeneratedHeaderForView(sb, nameof(ViewWriter));

        sb.AppendLine($"@model {vmNs}.{entity}ViewModel");
        sb.AppendLine();
        sb.AppendLine($"<h2>{entity} Detay</h2>");
        sb.AppendLine("<dl class=\"row\">");

        foreach (var c in cols.Where(c =>
                     !c.IsIdentity &&
                     !c.IsInsertDate() &&
                     !c.IsUpdateDate() &&
                     !c.IsIsActive()))
        {
            sb.AppendLine($"""
    <dt class="col-sm-3">{c.Name}</dt>
    <dd class="col-sm-9">@Model.{c.Name}</dd>
""");
        }

        sb.AppendLine("""
</dl>

<a asp-action="Index" class="btn btn-sm btn-outline-primary rounded-pill px-4">
    <i class="fa fa-arrow-left me-1"></i>Back
</a>
""");

        return sb.ToString();
    }
}
