using System.Text;

public static class ViewWriter
{
    public static Dictionary<string, string> GenerateViews(
        string entity,
        string viewModelNamespace,
        List<DbColumn> cols)
    {
        var result = new Dictionary<string, string>();
        result.Add("Index.cshtml", GenerateIndex(entity, viewModelNamespace, cols));
        result.Add("Create.cshtml", GenerateCreate(entity, viewModelNamespace, cols));
        result.Add("Edit.cshtml", GenerateEdit(entity, viewModelNamespace, cols));
        result.Add("Delete.cshtml", GenerateDelete(entity, viewModelNamespace, cols));
        result.Add("Detail.cshtml", GenerateDetails(entity, viewModelNamespace, cols));
        return result;
    }

    // ================= INDEX =================
    static string GenerateIndex(string entity, string vmNs, List<DbColumn> cols)
    {
        var sb = new StringBuilder();
        EntityCreator.Helper.AppendAutoGeneratedHeaderForView(sb, nameof(ViewWriter));
        sb.AppendLine($"@model IEnumerable<{vmNs}.{entity}ListViewModel>");
        sb.AppendLine();
        sb.AppendLine($"<h2>{entity} Listesi</h2>");
        sb.AppendLine("<a asp-action=\"Create\" class=\"btn btn-primary mb-2\">Yeni Ekle</a>");
        sb.AppendLine("<table class=\"table table-bordered\">");
        sb.AppendLine("    <thead>");
        sb.AppendLine("        <tr>");

        foreach (var c in cols)
            sb.AppendLine($"            <th>{c.Name}</th>");

        sb.AppendLine("            <th></th>");
        sb.AppendLine("        </tr>");
        sb.AppendLine("    </thead>");
        sb.AppendLine("    <tbody>");
        sb.AppendLine("    @foreach (var item in Model)");
        sb.AppendLine("    {");
        sb.AppendLine("        <tr>");

        foreach (var c in cols)
            sb.AppendLine($"            <td>@item.{c.Name}</td>");

        sb.AppendLine("            <td>");
        sb.AppendLine("                <a asp-action=\"Edit\" asp-route-id=\"@item.Id\">Edit</a> |");
        sb.AppendLine("                <a asp-action=\"Detail\" asp-route-id=\"@item.Id\">Detail</a> |");
        sb.AppendLine("                <a asp-action=\"Delete\" asp-route-id=\"@item.Id\">Delete</a>");
        sb.AppendLine("            </td>");
        sb.AppendLine("        </tr>");
        sb.AppendLine("    }");
        sb.AppendLine("    </tbody>");
        sb.AppendLine("</table>");
        return sb.ToString();
    }

    // ================= CREATE =================
    static string GenerateCreate(string entity, string vmNs, List<DbColumn> cols)
    {
        var sb = new StringBuilder();
        EntityCreator.Helper.AppendAutoGeneratedHeaderForView(sb, nameof(ViewWriter));
        sb.AppendLine($"@model {vmNs}.{entity}CreateViewModel");
        sb.AppendLine();
        sb.AppendLine($"<h2>{entity} Yarat</h2>");
        sb.AppendLine("<form asp-action=\"Create\" method=\"post\">");
        sb.AppendLine("    @Html.AntiForgeryToken()");
        sb.AppendLine("    <div asp-validation-summary=\"ModelOnly\" class=\"text-danger\"></div>");

        foreach (var c in cols.Where(c =>
                     !c.IsIdentity &&
                     !c.IsInsertDate() &&
                     !c.IsUpdateDate() &&
                     !c.IsIsActive()))
        {
            sb.AppendLine("    <div class=\"form-group\">");
            sb.AppendLine($"        <label asp-for=\"{c.Name}\"></label>");
            sb.AppendLine($"        <input asp-for=\"{c.Name}\" class=\"form-control\" />");
            sb.AppendLine($"        <span asp-validation-for=\"{c.Name}\" class=\"text-danger\"></span>");
            sb.AppendLine("    </div>");
        }

        sb.AppendLine("    <button type=\"submit\" class=\"btn btn-success\">Kaydet</button>");
        sb.AppendLine("</form>");
        sb.AppendLine();
        sb.AppendLine("@section Scripts {");
        sb.AppendLine("    @{ await Html.RenderPartialAsync(\"_ValidationScriptsPartial\"); }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    // ================= EDIT =================
    static string GenerateEdit(string entity, string vmNs, List<DbColumn> cols)
    {
        var sb = new StringBuilder();
        EntityCreator.Helper.AppendAutoGeneratedHeaderForView(sb, nameof(ViewWriter));
        sb.AppendLine($"@model {vmNs}.{entity}UpdateViewModel");
        sb.AppendLine();
        sb.AppendLine($"<h2>{entity} Düzenle</h2>");
        sb.AppendLine("<form asp-action=\"Edit\" method=\"post\">");
        sb.AppendLine("    @Html.AntiForgeryToken()");
        sb.AppendLine("    <input type=\"hidden\" asp-for=\"Id\" />");

        foreach (var c in cols.Where(c =>
                     !c.IsIdentity &&
                     !c.IsInsertDate() &&
                     !c.IsUpdateDate() &&
                     !c.IsIsActive()))
        {
            if (c.Name == "Id") continue;

            sb.AppendLine("    <div class=\"form-group\">");
            sb.AppendLine($"        <label asp-for=\"{c.Name}\"></label>");
            sb.AppendLine($"        <input asp-for=\"{c.Name}\" class=\"form-control\" />");
            sb.AppendLine($"        <span asp-validation-for=\"{c.Name}\" class=\"text-danger\"></span>");
            sb.AppendLine("    </div>");
        }

        sb.AppendLine("    <button type=\"submit\" class=\"btn btn-success\">Kaydet</button>");
        sb.AppendLine("    <a asp-action=\"Index\" class=\"btn btn-secondary\">İptal</a>");
        sb.AppendLine("</form>");
        sb.AppendLine();
        sb.AppendLine("@section Scripts {");
        sb.AppendLine("    @{ await Html.RenderPartialAsync(\"_ValidationScriptsPartial\"); }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    // ================= DELETE =================
    static string GenerateDelete(string entity, string vmNs, List<DbColumn> cols)
    {
        var sb = new StringBuilder();
        EntityCreator.Helper.AppendAutoGeneratedHeaderForView(sb, nameof(ViewWriter));
        sb.AppendLine($"@model {vmNs}.{entity}ViewModel");
        sb.AppendLine();
        sb.AppendLine($"<h2>{entity} Sil</h2>");
        sb.AppendLine("<div class=\"alert alert-danger\">Silmek istediğinize emin misiniz?</div>");
        sb.AppendLine("<dl class=\"row\">");

        foreach (var c in cols)
        {
            sb.AppendLine($"    <dt class=\"col-sm-3\">{c.Name}</dt>");
            sb.AppendLine($"    <dd class=\"col-sm-9\">@Model.{c.Name}</dd>");
        }

        sb.AppendLine("</dl>");
        sb.AppendLine("<form asp-action=\"DeleteConfirmed\" method=\"post\">");
        sb.AppendLine("    @Html.AntiForgeryToken()");
        sb.AppendLine("    <input type=\"hidden\" asp-for=\"Id\" />");
        sb.AppendLine("    <button type=\"submit\" class=\"btn btn-danger\">Sil</button>");
        sb.AppendLine("    <a asp-action=\"Index\" class=\"btn btn-secondary\">İptal</a>");
        sb.AppendLine("</form>");
        return sb.ToString();
    }

    // ================= DETAILS =================
    static string GenerateDetails(string entity, string vmNs, List<DbColumn> cols)
    {
        var sb = new StringBuilder();
        EntityCreator.Helper.AppendAutoGeneratedHeaderForView(sb, nameof(ViewWriter));
        sb.AppendLine($"@model {vmNs}.{entity}ViewModel");
        sb.AppendLine();
        sb.AppendLine($"<h2>{entity} Detay</h2>");
        sb.AppendLine("<dl class=\"row\">");

        foreach (var c in cols.Where(c =>
                     !c.IsIdentity &&
                     !c.IsInsertDate() &&
                     !c.IsUpdateDate() &&
                     !c.IsIsActive()))
        {
            sb.AppendLine($"    <dt class=\"col-sm-3\">{c.Name}</dt>");
            sb.AppendLine($"    <dd class=\"col-sm-9\">@Model.{c.Name}</dd>");
        }

        sb.AppendLine("</dl>");
        sb.AppendLine("<a asp-action=\"Index\" class=\"btn btn-secondary\">Geri</a>");
        return sb.ToString();
    }
}
