-- <auto-generated>
-- This file is generated. Do not edit manually.
-- Generated at      : 2026-02-27 17:18:33
-- Generated at (UTC): 2026-02-27 14:18:33
-- Machine: YAZILIM3
-- Generator: EntityCreator v1.0
-- Class Name: SpWriter
-- </auto-generated>

CREATE OR ALTER PROCEDURE [dbo].[sp_Araba_Insert]
    @Model nvarchar(50),
    @Marka nvarchar(50)
AS
BEGIN
    SET NOCOUNT ON;

    INSERT INTO [dbo].[Araba]
    ([Model], [Marka])
    VALUES
    (@Model, @Marka);

    SELECT SCOPE_IDENTITY() AS NewId;
END

GO

-- <auto-generated>
-- This file is generated. Do not edit manually.
-- Generated at      : 2026-02-27 17:18:33
-- Generated at (UTC): 2026-02-27 14:18:33
-- Machine: YAZILIM3
-- Generator: EntityCreator v1.0
-- Class Name: SpWriter
-- </auto-generated>

CREATE OR ALTER PROCEDURE [dbo].[sp_Araba_Update]
    @Id int,
    @Model nvarchar(50),
    @Marka nvarchar(50)
AS
BEGIN
    SET NOCOUNT ON;

    UPDATE [dbo].[Araba]
    SET
        [Model] = @Model,
        [Marka] = @Marka
    WHERE [Id] = @Id;
END

GO

-- <auto-generated>
-- This file is generated. Do not edit manually.
-- Generated at      : 2026-02-27 17:18:33
-- Generated at (UTC): 2026-02-27 14:18:33
-- Machine: YAZILIM3
-- Generator: EntityCreator v1.0
-- Class Name: SpWriter
-- </auto-generated>

CREATE OR ALTER PROCEDURE [dbo].[sp_Araba_Delete]
    @Id int
AS
BEGIN
    SET NOCOUNT ON;

    DELETE FROM [dbo].[Araba]
    WHERE [Id] = @Id;
END

GO


GO

-- <auto-generated>
-- This file is generated. Do not edit manually.
-- Generated at      : 2026-02-27 17:18:33
-- Generated at (UTC): 2026-02-27 14:18:33
-- Machine: YAZILIM3
-- Generator: EntityCreator v1.0
-- Class Name: SpWriter
-- </auto-generated>

CREATE OR ALTER PROCEDURE [dbo].[sp_Araba_GetById]
    @Id int
AS
BEGIN
    SET NOCOUNT ON;

    SELECT Id,Model,Marka
    FROM [dbo].[Araba]
    WHERE [Id] = @Id
END

GO

-- <auto-generated>
-- This file is generated. Do not edit manually.
-- Generated at      : 2026-02-27 17:18:33
-- Generated at (UTC): 2026-02-27 14:18:33
-- Machine: YAZILIM3
-- Generator: EntityCreator v1.0
-- Class Name: SpWriter
-- </auto-generated>

CREATE OR ALTER PROCEDURE [dbo].[sp_Araba_List]
AS
BEGIN
    SET NOCOUNT ON;

    SELECT Id,Model,Marka
    FROM [dbo].[Araba]
END

GO

-- <auto-generated>
-- This file is generated. Do not edit manually.
-- Generated at      : 2026-02-27 17:18:33
-- Generated at (UTC): 2026-02-27 14:18:33
-- Machine: YAZILIM3
-- Generator: EntityCreator v1.0
-- Class Name: SpWriter
-- </auto-generated>

CREATE OR ALTER PROCEDURE [dbo].[sp_Araba_PagedList]
    @Page INT,
    @PageSize INT
AS
BEGIN
    SET NOCOUNT ON;

    SELECT Id,Model,Marka
    FROM [dbo].[Araba]
    ORDER BY [Id] DESC
    OFFSET (@Page - 1) * @PageSize ROWS
    FETCH NEXT @PageSize ROWS ONLY;

    SELECT COUNT(1) AS TotalCount
    FROM [dbo].[Araba]
END

