-- <auto-generated>
-- This file is generated. Do not edit manually.
-- Generated at      : 2026-02-13 16:12:55
-- Generated at (UTC): 2026-02-13 13:12:55
-- Machine: YAZILIM3
-- Generator: EntityCreator v1.0
-- Class Name: SpWriter
-- </auto-generated>

CREATE OR ALTER PROCEDURE [dbo].[sp_Cart_Insert]
    @ProductId int,
    @ProductCode nvarchar(50),
    @ProductName nvarchar(255),
    @UnitPrice decimal(9,2),
    @Quantity int,
    @TotalAmount decimal(9,2),
    @UserId int = NULL,
    @cart_id_token nvarchar(200) = NULL,
    @CurrencyCode nvarchar(10)
AS
BEGIN
    SET NOCOUNT ON;

    INSERT INTO [dbo].[Cart]
    ([ProductId], [ProductCode], [ProductName], [UnitPrice], [Quantity], [TotalAmount], [UserId], [InsertDate], [IsActive], [cart_id_token], [CurrencyCode])
    VALUES
    (@ProductId, @ProductCode, @ProductName, @UnitPrice, @Quantity, @TotalAmount, @UserId, GETDATE(), 1, @cart_id_token, @CurrencyCode);

    SELECT SCOPE_IDENTITY() AS NewId;
END

GO

-- <auto-generated>
-- This file is generated. Do not edit manually.
-- Generated at      : 2026-02-13 16:12:55
-- Generated at (UTC): 2026-02-13 13:12:55
-- Machine: YAZILIM3
-- Generator: EntityCreator v1.0
-- Class Name: SpWriter
-- </auto-generated>

CREATE OR ALTER PROCEDURE [dbo].[sp_Cart_Update]
    @Id int,
    @ProductId int,
    @ProductCode nvarchar(50),
    @ProductName nvarchar(255),
    @UnitPrice decimal(9,2),
    @Quantity int,
    @TotalAmount decimal(9,2),
    @UserId int = NULL,
    @cart_id_token nvarchar(200) = NULL,
    @CurrencyCode nvarchar(10)
AS
BEGIN
    SET NOCOUNT ON;

    UPDATE [dbo].[Cart]
    SET
        [ProductId] = @ProductId,
        [ProductCode] = @ProductCode,
        [ProductName] = @ProductName,
        [UnitPrice] = @UnitPrice,
        [Quantity] = @Quantity,
        [TotalAmount] = @TotalAmount,
        [UserId] = @UserId,
        [UpdateDate] = GETDATE(),
        [cart_id_token] = @cart_id_token,
        [CurrencyCode] = @CurrencyCode
    WHERE [Id] = @Id;
END

GO

-- <auto-generated>
-- This file is generated. Do not edit manually.
-- Generated at      : 2026-02-13 16:12:55
-- Generated at (UTC): 2026-02-13 13:12:55
-- Machine: YAZILIM3
-- Generator: EntityCreator v1.0
-- Class Name: SpWriter
-- </auto-generated>

CREATE OR ALTER PROCEDURE [dbo].[sp_Cart_Delete]
    @Id int
AS
BEGIN
    SET NOCOUNT ON;

    DELETE FROM [dbo].[Cart]
    WHERE [Id] = @Id;
END

GO

-- <auto-generated>
-- This file is generated. Do not edit manually.
-- Generated at      : 2026-02-13 16:12:55
-- Generated at (UTC): 2026-02-13 13:12:55
-- Machine: YAZILIM3
-- Generator: EntityCreator v1.0
-- Class Name: SpWriter
-- </auto-generated>

CREATE OR ALTER PROCEDURE [dbo].[sp_Cart_DeleteSoft]
    @Id int
AS
BEGIN
    SET NOCOUNT ON;

    UPDATE [dbo].[Cart]
    SET [IsActive] = 0
    WHERE [Id] = @Id;
END

GO

-- <auto-generated>
-- This file is generated. Do not edit manually.
-- Generated at      : 2026-02-13 16:12:55
-- Generated at (UTC): 2026-02-13 13:12:55
-- Machine: YAZILIM3
-- Generator: EntityCreator v1.0
-- Class Name: SpWriter
-- </auto-generated>

CREATE OR ALTER PROCEDURE [dbo].[sp_Cart_GetById]
    @Id int
AS
BEGIN
    SET NOCOUNT ON;

    SELECT Id,ProductId,ProductCode,ProductName,UnitPrice,Quantity,TotalAmount,UserId,cart_id_token,CurrencyCode
    FROM [dbo].[Cart]
    WHERE [Id] = @Id
      AND IsActive = 1
END

GO

-- <auto-generated>
-- This file is generated. Do not edit manually.
-- Generated at      : 2026-02-13 16:12:55
-- Generated at (UTC): 2026-02-13 13:12:55
-- Machine: YAZILIM3
-- Generator: EntityCreator v1.0
-- Class Name: SpWriter
-- </auto-generated>

CREATE OR ALTER PROCEDURE [dbo].[sp_Cart_List]
AS
BEGIN
    SET NOCOUNT ON;

    SELECT Id,ProductId,ProductCode,ProductName,UnitPrice,Quantity,TotalAmount,UserId,cart_id_token,CurrencyCode
    FROM [dbo].[Cart]
    WHERE IsActive = 1
END

GO

-- <auto-generated>
-- This file is generated. Do not edit manually.
-- Generated at      : 2026-02-13 16:12:55
-- Generated at (UTC): 2026-02-13 13:12:55
-- Machine: YAZILIM3
-- Generator: EntityCreator v1.0
-- Class Name: SpWriter
-- </auto-generated>

CREATE OR ALTER PROCEDURE [dbo].[sp_Cart_PagedList]
    @Page INT,
    @PageSize INT
AS
BEGIN
    SET NOCOUNT ON;

    SELECT Id,ProductId,ProductCode,ProductName,UnitPrice,Quantity,TotalAmount,UserId,cart_id_token,CurrencyCode
    FROM [dbo].[Cart]
    WHERE IsActive = 1
    ORDER BY [Id] DESC
    OFFSET (@Page - 1) * @PageSize ROWS
    FETCH NEXT @PageSize ROWS ONLY;

    SELECT COUNT(1) AS TotalCount
    FROM [dbo].[Cart]
    WHERE IsActive = 1
END

