-- <auto-generated>
-- This file is generated. Do not edit manually.
-- Generated at      : 2026-01-18 00:41:38
-- Generated at (UTC): 2026-01-17 21:41:38
-- Machine: DESKTOP-IITN2G2
-- Generator: EntityCreator v1.0
-- Class Name: SpWriter
-- </auto-generated>

CREATE OR ALTER PROCEDURE [dbo].[sp_Category_Insert]
    @Name nvarchar(50)
AS
BEGIN
    SET NOCOUNT ON;

    INSERT INTO [dbo].[Category]
    ([Name], [IsActive])
    VALUES
    (@Name, 1);

    SELECT SCOPE_IDENTITY() AS NewId;
END

GO

-- <auto-generated>
-- This file is generated. Do not edit manually.
-- Generated at      : 2026-01-18 00:41:38
-- Generated at (UTC): 2026-01-17 21:41:38
-- Machine: DESKTOP-IITN2G2
-- Generator: EntityCreator v1.0
-- Class Name: SpWriter
-- </auto-generated>

CREATE OR ALTER PROCEDURE [dbo].[sp_Category_Update]
    @Id int,
    @Name nvarchar(50)
AS
BEGIN
    SET NOCOUNT ON;

    UPDATE [dbo].[Category]
    SET
        [Name] = @Name
    WHERE [Id] = @Id;
END

GO

-- <auto-generated>
-- This file is generated. Do not edit manually.
-- Generated at      : 2026-01-18 00:41:38
-- Generated at (UTC): 2026-01-17 21:41:38
-- Machine: DESKTOP-IITN2G2
-- Generator: EntityCreator v1.0
-- Class Name: SpWriter
-- </auto-generated>

CREATE OR ALTER PROCEDURE [dbo].[sp_Category_Delete]
    @Id int
AS
BEGIN
    SET NOCOUNT ON;

    DELETE FROM [dbo].[Category]
    WHERE [Id] = @Id;
END

GO

-- <auto-generated>
-- This file is generated. Do not edit manually.
-- Generated at      : 2026-01-18 00:41:38
-- Generated at (UTC): 2026-01-17 21:41:38
-- Machine: DESKTOP-IITN2G2
-- Generator: EntityCreator v1.0
-- Class Name: SpWriter
-- </auto-generated>

CREATE OR ALTER PROCEDURE [dbo].[sp_Category_DeleteSoft]
    @Id int
AS
BEGIN
    SET NOCOUNT ON;

    UPDATE [dbo].[Category]
    SET [IsActive] = 0
    WHERE [Id] = @Id;
END

GO

-- <auto-generated>
-- This file is generated. Do not edit manually.
-- Generated at      : 2026-01-18 00:41:38
-- Generated at (UTC): 2026-01-17 21:41:38
-- Machine: DESKTOP-IITN2G2
-- Generator: EntityCreator v1.0
-- Class Name: SpWriter
-- </auto-generated>

CREATE OR ALTER PROCEDURE [dbo].[sp_Category_GetById]
    @Id int
AS
BEGIN
    SET NOCOUNT ON;

    SELECT * FROM [dbo].[Category]
    WHERE [Id] = @Id
      AND IsActive = 1
END

GO

-- <auto-generated>
-- This file is generated. Do not edit manually.
-- Generated at      : 2026-01-18 00:41:38
-- Generated at (UTC): 2026-01-17 21:41:38
-- Machine: DESKTOP-IITN2G2
-- Generator: EntityCreator v1.0
-- Class Name: SpWriter
-- </auto-generated>

CREATE OR ALTER PROCEDURE [dbo].[sp_Category_List]
AS
BEGIN
    SET NOCOUNT ON;

    SELECT * FROM [dbo].[Category]
    WHERE IsActive = 1
END

GO

-- <auto-generated>
-- This file is generated. Do not edit manually.
-- Generated at      : 2026-01-18 00:41:38
-- Generated at (UTC): 2026-01-17 21:41:38
-- Machine: DESKTOP-IITN2G2
-- Generator: EntityCreator v1.0
-- Class Name: SpWriter
-- </auto-generated>

CREATE OR ALTER PROCEDURE [dbo].[sp_Category_PagedList]
    @Page INT,
    @PageSize INT
AS
BEGIN
    SET NOCOUNT ON;

    SELECT * FROM [dbo].[Category]
    WHERE IsActive = 1
    ORDER BY [Id] DESC
    OFFSET (@Page - 1) * @PageSize ROWS
    FETCH NEXT @PageSize ROWS ONLY;

    SELECT COUNT(1) AS TotalCount
    FROM [dbo].[Category]
    WHERE IsActive = 1
END

