-- <auto-generated>
-- This file is generated. Do not edit manually.
-- Generated at      : 2026-01-24 21:15:32
-- Generated at (UTC): 2026-01-24 18:15:32
-- Machine: DESKTOP-IITN2G2
-- Generator: EntityCreator v1.0
-- Class Name: SpWriter
-- </auto-generated>

CREATE OR ALTER PROCEDURE [dbo].[sp_PERON_Insert]
    @DOLUBigId bigint,
    @DOLUUniqueId uniqueidentifier = NULL,
    @DOLUIntValue int,
    @DOLUSmallIntValue smallint,
    @DOLUTinyIntValue tinyint,
    @DOLUBitValue bit,
    @DOLUDecimalValue decimal(18,2) = NULL,
    @DOLUNumericValue numeric(10,4) = NULL,
    @DOLUMoneyValue money,
    @DOLUSmallMoneyValue smallmoney,
    @DOLUFloatValue float,
    @DOLURealValue real,
    @DOLUDateValue date,
    @DOLUTimeValue time = NULL,
    @DOLUDateTimeValue datetime,
    @DOLUSmallDateTimeValue smalldatetime,
    @DOLUDateTime2Value datetime2,
    @DOLUDateTimeOffsetValue datetimeoffset,
    @DOLUCharValue char(10),
    @DOLUVarCharValue varchar(100),
    @DOLUVarCharMaxValue varchar(MAX),
    @DOLUNCharValue nchar(10),
    @DOLUNVarCharValue nvarchar(100),
    @DOLUNVarCharMaxValue nvarchar(MAX),
    @DOLUNTextValue ntext,
    @DOLUBinaryValue binary,
    @DOLUVarBinaryValue varbinary,
    @DOLUVarBinaryMaxValue varbinary,
    @DOLUImageValue image,
    @DOLUXmlValue xml,
    @DOLUSqlVariantValue sql_variant,
    @DOLURowVersionValue timestamp,
    @DOLUHierarchyIdValue hierarchyid,
    @DOLUGeographyValue geography,
    @DOLUGeometryValue geometry,
    @DOLUIsActive bit,
    @DOLUInsertDate datetime2,
    @DOLUUpdateDate datetime2,
    @NALBigId bigint = NULL,
    @NALUniqueId uniqueidentifier = NULL,
    @NALIntValue int = NULL,
    @NALSmallIntValue smallint = NULL,
    @NALTinyIntValue tinyint = NULL,
    @NALBitValue bit = NULL,
    @NALDecimalValue decimal(18,2) = NULL,
    @NALNumericValue numeric(10,4) = NULL,
    @NALMoneyValue money = NULL,
    @NALSmallMoneyValue smallmoney = NULL,
    @NALFloatValue float = NULL,
    @NALRealValue real = NULL,
    @NALDateValue date = NULL,
    @NALTimeValue time = NULL,
    @NALDateTimeValue datetime = NULL,
    @NALSmallDateTimeValue smalldatetime = NULL,
    @NALDateTime2Value datetime2 = NULL,
    @NALDateTimeOffsetValue datetimeoffset = NULL,
    @NALCharValue char(10) = NULL,
    @NALVarCharValue varchar(100) = NULL,
    @NALVarCharMaxValue varchar(MAX) = NULL,
    @NALNCharValue nchar(10) = NULL,
    @NALNVarCharValue nvarchar(100) = NULL,
    @NALNVarCharMaxValue nvarchar(MAX) = NULL,
    @NALNTextValue ntext = NULL,
    @NALBinaryValue binary = NULL,
    @NALVarBinaryValue varbinary = NULL,
    @NALVarBinaryMaxValue varbinary = NULL,
    @NALImageValue image = NULL,
    @NALXmlValue xml = NULL,
    @NALSqlVariantValue sql_variant = NULL,
    @NALHierarchyIdValue hierarchyid = NULL,
    @NALGeographyValue geography = NULL,
    @NALGeometryValue geometry = NULL,
    @NALIsActive bit = NULL,
    @NALInsertDate datetime2 = NULL,
    @NALUpdateDate datetime2 = NULL
AS
BEGIN
    SET NOCOUNT ON;

    INSERT INTO [dbo].[PERON]
    ([DOLUBigId], [DOLUUniqueId], [DOLUIntValue], [DOLUSmallIntValue], [DOLUTinyIntValue], [DOLUBitValue], [DOLUDecimalValue], [DOLUNumericValue], [DOLUMoneyValue], [DOLUSmallMoneyValue], [DOLUFloatValue], [DOLURealValue], [DOLUDateValue], [DOLUTimeValue], [DOLUDateTimeValue], [DOLUSmallDateTimeValue], [DOLUDateTime2Value], [DOLUDateTimeOffsetValue], [DOLUCharValue], [DOLUVarCharValue], [DOLUVarCharMaxValue], [DOLUNCharValue], [DOLUNVarCharValue], [DOLUNVarCharMaxValue], [DOLUNTextValue], [DOLUBinaryValue], [DOLUVarBinaryValue], [DOLUVarBinaryMaxValue], [DOLUImageValue], [DOLUXmlValue], [DOLUSqlVariantValue], [DOLURowVersionValue], [DOLUHierarchyIdValue], [DOLUGeographyValue], [DOLUGeometryValue], [DOLUIsActive], [DOLUInsertDate], [DOLUUpdateDate], [NALBigId], [NALUniqueId], [NALIntValue], [NALSmallIntValue], [NALTinyIntValue], [NALBitValue], [NALDecimalValue], [NALNumericValue], [NALMoneyValue], [NALSmallMoneyValue], [NALFloatValue], [NALRealValue], [NALDateValue], [NALTimeValue], [NALDateTimeValue], [NALSmallDateTimeValue], [NALDateTime2Value], [NALDateTimeOffsetValue], [NALCharValue], [NALVarCharValue], [NALVarCharMaxValue], [NALNCharValue], [NALNVarCharValue], [NALNVarCharMaxValue], [NALNTextValue], [NALBinaryValue], [NALVarBinaryValue], [NALVarBinaryMaxValue], [NALImageValue], [NALXmlValue], [NALSqlVariantValue], [NALHierarchyIdValue], [NALGeographyValue], [NALGeometryValue], [NALIsActive], [NALInsertDate], [NALUpdateDate])
    VALUES
    (@DOLUBigId, @DOLUUniqueId, @DOLUIntValue, @DOLUSmallIntValue, @DOLUTinyIntValue, @DOLUBitValue, @DOLUDecimalValue, @DOLUNumericValue, @DOLUMoneyValue, @DOLUSmallMoneyValue, @DOLUFloatValue, @DOLURealValue, @DOLUDateValue, @DOLUTimeValue, @DOLUDateTimeValue, @DOLUSmallDateTimeValue, @DOLUDateTime2Value, @DOLUDateTimeOffsetValue, @DOLUCharValue, @DOLUVarCharValue, @DOLUVarCharMaxValue, @DOLUNCharValue, @DOLUNVarCharValue, @DOLUNVarCharMaxValue, @DOLUNTextValue, @DOLUBinaryValue, @DOLUVarBinaryValue, @DOLUVarBinaryMaxValue, @DOLUImageValue, @DOLUXmlValue, @DOLUSqlVariantValue, @DOLURowVersionValue, @DOLUHierarchyIdValue, @DOLUGeographyValue, @DOLUGeometryValue, @DOLUIsActive, @DOLUInsertDate, @DOLUUpdateDate, @NALBigId, @NALUniqueId, @NALIntValue, @NALSmallIntValue, @NALTinyIntValue, @NALBitValue, @NALDecimalValue, @NALNumericValue, @NALMoneyValue, @NALSmallMoneyValue, @NALFloatValue, @NALRealValue, @NALDateValue, @NALTimeValue, @NALDateTimeValue, @NALSmallDateTimeValue, @NALDateTime2Value, @NALDateTimeOffsetValue, @NALCharValue, @NALVarCharValue, @NALVarCharMaxValue, @NALNCharValue, @NALNVarCharValue, @NALNVarCharMaxValue, @NALNTextValue, @NALBinaryValue, @NALVarBinaryValue, @NALVarBinaryMaxValue, @NALImageValue, @NALXmlValue, @NALSqlVariantValue, @NALHierarchyIdValue, @NALGeographyValue, @NALGeometryValue, @NALIsActive, @NALInsertDate, @NALUpdateDate);

    SELECT SCOPE_IDENTITY() AS NewId;
END

GO

-- <auto-generated>
-- This file is generated. Do not edit manually.
-- Generated at      : 2026-01-24 21:15:32
-- Generated at (UTC): 2026-01-24 18:15:32
-- Machine: DESKTOP-IITN2G2
-- Generator: EntityCreator v1.0
-- Class Name: SpWriter
-- </auto-generated>

CREATE OR ALTER PROCEDURE [dbo].[sp_PERON_Update]
    @DOLUId int,
    @DOLUBigId bigint,
    @DOLUUniqueId uniqueidentifier = NULL,
    @DOLUIntValue int,
    @DOLUSmallIntValue smallint,
    @DOLUTinyIntValue tinyint,
    @DOLUBitValue bit,
    @DOLUDecimalValue decimal(18,2) = NULL,
    @DOLUNumericValue numeric(10,4) = NULL,
    @DOLUMoneyValue money,
    @DOLUSmallMoneyValue smallmoney,
    @DOLUFloatValue float,
    @DOLURealValue real,
    @DOLUDateValue date,
    @DOLUTimeValue time = NULL,
    @DOLUDateTimeValue datetime,
    @DOLUSmallDateTimeValue smalldatetime,
    @DOLUDateTime2Value datetime2,
    @DOLUDateTimeOffsetValue datetimeoffset,
    @DOLUCharValue char(10),
    @DOLUVarCharValue varchar(100),
    @DOLUVarCharMaxValue varchar(MAX),
    @DOLUNCharValue nchar(10),
    @DOLUNVarCharValue nvarchar(100),
    @DOLUNVarCharMaxValue nvarchar(MAX),
    @DOLUNTextValue ntext,
    @DOLUBinaryValue binary,
    @DOLUVarBinaryValue varbinary,
    @DOLUVarBinaryMaxValue varbinary,
    @DOLUImageValue image,
    @DOLUXmlValue xml,
    @DOLUSqlVariantValue sql_variant,
    @DOLURowVersionValue timestamp,
    @DOLUHierarchyIdValue hierarchyid,
    @DOLUGeographyValue geography,
    @DOLUGeometryValue geometry,
    @DOLUIsActive bit,
    @DOLUInsertDate datetime2,
    @DOLUUpdateDate datetime2,
    @NALBigId bigint = NULL,
    @NALUniqueId uniqueidentifier = NULL,
    @NALIntValue int = NULL,
    @NALSmallIntValue smallint = NULL,
    @NALTinyIntValue tinyint = NULL,
    @NALBitValue bit = NULL,
    @NALDecimalValue decimal(18,2) = NULL,
    @NALNumericValue numeric(10,4) = NULL,
    @NALMoneyValue money = NULL,
    @NALSmallMoneyValue smallmoney = NULL,
    @NALFloatValue float = NULL,
    @NALRealValue real = NULL,
    @NALDateValue date = NULL,
    @NALTimeValue time = NULL,
    @NALDateTimeValue datetime = NULL,
    @NALSmallDateTimeValue smalldatetime = NULL,
    @NALDateTime2Value datetime2 = NULL,
    @NALDateTimeOffsetValue datetimeoffset = NULL,
    @NALCharValue char(10) = NULL,
    @NALVarCharValue varchar(100) = NULL,
    @NALVarCharMaxValue varchar(MAX) = NULL,
    @NALNCharValue nchar(10) = NULL,
    @NALNVarCharValue nvarchar(100) = NULL,
    @NALNVarCharMaxValue nvarchar(MAX) = NULL,
    @NALNTextValue ntext = NULL,
    @NALBinaryValue binary = NULL,
    @NALVarBinaryValue varbinary = NULL,
    @NALVarBinaryMaxValue varbinary = NULL,
    @NALImageValue image = NULL,
    @NALXmlValue xml = NULL,
    @NALSqlVariantValue sql_variant = NULL,
    @NALHierarchyIdValue hierarchyid = NULL,
    @NALGeographyValue geography = NULL,
    @NALGeometryValue geometry = NULL,
    @NALIsActive bit = NULL,
    @NALInsertDate datetime2 = NULL,
    @NALUpdateDate datetime2 = NULL
AS
BEGIN
    SET NOCOUNT ON;

    UPDATE [dbo].[PERON]
    SET
        [DOLUBigId] = @DOLUBigId,
        [DOLUUniqueId] = @DOLUUniqueId,
        [DOLUIntValue] = @DOLUIntValue,
        [DOLUSmallIntValue] = @DOLUSmallIntValue,
        [DOLUTinyIntValue] = @DOLUTinyIntValue,
        [DOLUBitValue] = @DOLUBitValue,
        [DOLUDecimalValue] = @DOLUDecimalValue,
        [DOLUNumericValue] = @DOLUNumericValue,
        [DOLUMoneyValue] = @DOLUMoneyValue,
        [DOLUSmallMoneyValue] = @DOLUSmallMoneyValue,
        [DOLUFloatValue] = @DOLUFloatValue,
        [DOLURealValue] = @DOLURealValue,
        [DOLUDateValue] = @DOLUDateValue,
        [DOLUTimeValue] = @DOLUTimeValue,
        [DOLUDateTimeValue] = @DOLUDateTimeValue,
        [DOLUSmallDateTimeValue] = @DOLUSmallDateTimeValue,
        [DOLUDateTime2Value] = @DOLUDateTime2Value,
        [DOLUDateTimeOffsetValue] = @DOLUDateTimeOffsetValue,
        [DOLUCharValue] = @DOLUCharValue,
        [DOLUVarCharValue] = @DOLUVarCharValue,
        [DOLUVarCharMaxValue] = @DOLUVarCharMaxValue,
        [DOLUNCharValue] = @DOLUNCharValue,
        [DOLUNVarCharValue] = @DOLUNVarCharValue,
        [DOLUNVarCharMaxValue] = @DOLUNVarCharMaxValue,
        [DOLUNTextValue] = @DOLUNTextValue,
        [DOLUBinaryValue] = @DOLUBinaryValue,
        [DOLUVarBinaryValue] = @DOLUVarBinaryValue,
        [DOLUVarBinaryMaxValue] = @DOLUVarBinaryMaxValue,
        [DOLUImageValue] = @DOLUImageValue,
        [DOLUXmlValue] = @DOLUXmlValue,
        [DOLUSqlVariantValue] = @DOLUSqlVariantValue,
        [DOLURowVersionValue] = @DOLURowVersionValue,
        [DOLUHierarchyIdValue] = @DOLUHierarchyIdValue,
        [DOLUGeographyValue] = @DOLUGeographyValue,
        [DOLUGeometryValue] = @DOLUGeometryValue,
        [DOLUIsActive] = @DOLUIsActive,
        [DOLUInsertDate] = @DOLUInsertDate,
        [DOLUUpdateDate] = @DOLUUpdateDate,
        [NALBigId] = @NALBigId,
        [NALUniqueId] = @NALUniqueId,
        [NALIntValue] = @NALIntValue,
        [NALSmallIntValue] = @NALSmallIntValue,
        [NALTinyIntValue] = @NALTinyIntValue,
        [NALBitValue] = @NALBitValue,
        [NALDecimalValue] = @NALDecimalValue,
        [NALNumericValue] = @NALNumericValue,
        [NALMoneyValue] = @NALMoneyValue,
        [NALSmallMoneyValue] = @NALSmallMoneyValue,
        [NALFloatValue] = @NALFloatValue,
        [NALRealValue] = @NALRealValue,
        [NALDateValue] = @NALDateValue,
        [NALTimeValue] = @NALTimeValue,
        [NALDateTimeValue] = @NALDateTimeValue,
        [NALSmallDateTimeValue] = @NALSmallDateTimeValue,
        [NALDateTime2Value] = @NALDateTime2Value,
        [NALDateTimeOffsetValue] = @NALDateTimeOffsetValue,
        [NALCharValue] = @NALCharValue,
        [NALVarCharValue] = @NALVarCharValue,
        [NALVarCharMaxValue] = @NALVarCharMaxValue,
        [NALNCharValue] = @NALNCharValue,
        [NALNVarCharValue] = @NALNVarCharValue,
        [NALNVarCharMaxValue] = @NALNVarCharMaxValue,
        [NALNTextValue] = @NALNTextValue,
        [NALBinaryValue] = @NALBinaryValue,
        [NALVarBinaryValue] = @NALVarBinaryValue,
        [NALVarBinaryMaxValue] = @NALVarBinaryMaxValue,
        [NALImageValue] = @NALImageValue,
        [NALXmlValue] = @NALXmlValue,
        [NALSqlVariantValue] = @NALSqlVariantValue,
        [NALHierarchyIdValue] = @NALHierarchyIdValue,
        [NALGeographyValue] = @NALGeographyValue,
        [NALGeometryValue] = @NALGeometryValue,
        [NALIsActive] = @NALIsActive,
        [NALInsertDate] = @NALInsertDate,
        [NALUpdateDate] = @NALUpdateDate
    WHERE [DOLUId] = @DOLUId;
END

GO

-- <auto-generated>
-- This file is generated. Do not edit manually.
-- Generated at      : 2026-01-24 21:15:32
-- Generated at (UTC): 2026-01-24 18:15:32
-- Machine: DESKTOP-IITN2G2
-- Generator: EntityCreator v1.0
-- Class Name: SpWriter
-- </auto-generated>

CREATE OR ALTER PROCEDURE [dbo].[sp_PERON_Delete]
    @DOLUId int
AS
BEGIN
    SET NOCOUNT ON;

    DELETE FROM [dbo].[PERON]
    WHERE [DOLUId] = @DOLUId;
END

GO


GO

-- <auto-generated>
-- This file is generated. Do not edit manually.
-- Generated at      : 2026-01-24 21:15:32
-- Generated at (UTC): 2026-01-24 18:15:32
-- Machine: DESKTOP-IITN2G2
-- Generator: EntityCreator v1.0
-- Class Name: SpWriter
-- </auto-generated>

CREATE OR ALTER PROCEDURE [dbo].[sp_PERON_GetById]
    @DOLUId int
AS
BEGIN
    SET NOCOUNT ON;

    SELECT * FROM [dbo].[PERON]
    WHERE [DOLUId] = @DOLUId
END

GO

-- <auto-generated>
-- This file is generated. Do not edit manually.
-- Generated at      : 2026-01-24 21:15:32
-- Generated at (UTC): 2026-01-24 18:15:32
-- Machine: DESKTOP-IITN2G2
-- Generator: EntityCreator v1.0
-- Class Name: SpWriter
-- </auto-generated>

CREATE OR ALTER PROCEDURE [dbo].[sp_PERON_List]
AS
BEGIN
    SET NOCOUNT ON;

    SELECT * FROM [dbo].[PERON]
END

GO

-- <auto-generated>
-- This file is generated. Do not edit manually.
-- Generated at      : 2026-01-24 21:15:32
-- Generated at (UTC): 2026-01-24 18:15:32
-- Machine: DESKTOP-IITN2G2
-- Generator: EntityCreator v1.0
-- Class Name: SpWriter
-- </auto-generated>

CREATE OR ALTER PROCEDURE [dbo].[sp_PERON_PagedList]
    @Page INT,
    @PageSize INT
AS
BEGIN
    SET NOCOUNT ON;

    SELECT * FROM [dbo].[PERON]
    ORDER BY [DOLUId] DESC
    OFFSET (@Page - 1) * @PageSize ROWS
    FETCH NEXT @PageSize ROWS ONLY;

    SELECT COUNT(1) AS TotalCount
    FROM [dbo].[PERON]
END

