-- <auto-generated>
-- This file is generated. Do not edit manually.
-- Generated at      : 2026-01-29 09:02:51
-- Generated at (UTC): 2026-01-29 06:02:51
-- Machine: YAZILIM3
-- Generator: EntityCreator v1.0
-- Class Name: SpWriter
-- </auto-generated>

CREATE OR ALTER PROCEDURE [dbo].[sp_Potansiyel_Insert]
    @Name nvarchar(50),
    @SurName nvarchar(50),
    @KnownName nvarchar(50),
    @Email nvarchar(100),
    @PhoneNumber nvarchar(50),
    @Adress int,
    @tarih date = NULL,
    @kayıttarihi datetime = NULL,
    @OzelSaatBilgisi time = NULL,
    @SatirAciklamasi nvarchar(10) = NULL,
    @GenisAciklama nvarchar(MAX) = NULL,
    @Fiyat decimal(9,2) = NULL
AS
BEGIN
    SET NOCOUNT ON;

    INSERT INTO [dbo].[Potansiyel]
    ([Name], [SurName], [KnownName], [Email], [PhoneNumber], [Adress], [tarih], [kayıttarihi], [OzelSaatBilgisi], [SatirAciklamasi], [GenisAciklama], [Fiyat], [InsertDate], [IsActive])
    VALUES
    (@Name, @SurName, @KnownName, @Email, @PhoneNumber, @Adress, @tarih, @kayıttarihi, @OzelSaatBilgisi, @SatirAciklamasi, @GenisAciklama, @Fiyat, GETDATE(), 1);

    SELECT SCOPE_IDENTITY() AS NewId;
END

GO

-- <auto-generated>
-- This file is generated. Do not edit manually.
-- Generated at      : 2026-01-29 09:02:51
-- Generated at (UTC): 2026-01-29 06:02:51
-- Machine: YAZILIM3
-- Generator: EntityCreator v1.0
-- Class Name: SpWriter
-- </auto-generated>

CREATE OR ALTER PROCEDURE [dbo].[sp_Potansiyel_Update]
    @Id int,
    @Name nvarchar(50),
    @SurName nvarchar(50),
    @KnownName nvarchar(50),
    @Email nvarchar(100),
    @PhoneNumber nvarchar(50),
    @Adress int,
    @tarih date = NULL,
    @kayıttarihi datetime = NULL,
    @OzelSaatBilgisi time = NULL,
    @SatirAciklamasi nvarchar(10) = NULL,
    @GenisAciklama nvarchar(MAX) = NULL,
    @Fiyat decimal(9,2) = NULL
AS
BEGIN
    SET NOCOUNT ON;

    UPDATE [dbo].[Potansiyel]
    SET
        [Name] = @Name,
        [SurName] = @SurName,
        [KnownName] = @KnownName,
        [Email] = @Email,
        [PhoneNumber] = @PhoneNumber,
        [Adress] = @Adress,
        [tarih] = @tarih,
        [kayıttarihi] = @kayıttarihi,
        [OzelSaatBilgisi] = @OzelSaatBilgisi,
        [SatirAciklamasi] = @SatirAciklamasi,
        [GenisAciklama] = @GenisAciklama,
        [Fiyat] = @Fiyat,
        [UpdateDate] = GETDATE()
    WHERE [Id] = @Id;
END

GO

-- <auto-generated>
-- This file is generated. Do not edit manually.
-- Generated at      : 2026-01-29 09:02:51
-- Generated at (UTC): 2026-01-29 06:02:51
-- Machine: YAZILIM3
-- Generator: EntityCreator v1.0
-- Class Name: SpWriter
-- </auto-generated>

CREATE OR ALTER PROCEDURE [dbo].[sp_Potansiyel_Delete]
    @Id int
AS
BEGIN
    SET NOCOUNT ON;

    DELETE FROM [dbo].[Potansiyel]
    WHERE [Id] = @Id;
END

GO

-- <auto-generated>
-- This file is generated. Do not edit manually.
-- Generated at      : 2026-01-29 09:02:51
-- Generated at (UTC): 2026-01-29 06:02:51
-- Machine: YAZILIM3
-- Generator: EntityCreator v1.0
-- Class Name: SpWriter
-- </auto-generated>

CREATE OR ALTER PROCEDURE [dbo].[sp_Potansiyel_DeleteSoft]
    @Id int
AS
BEGIN
    SET NOCOUNT ON;

    UPDATE [dbo].[Potansiyel]
    SET [IsActive] = 0
    WHERE [Id] = @Id;
END

GO

-- <auto-generated>
-- This file is generated. Do not edit manually.
-- Generated at      : 2026-01-29 09:02:51
-- Generated at (UTC): 2026-01-29 06:02:51
-- Machine: YAZILIM3
-- Generator: EntityCreator v1.0
-- Class Name: SpWriter
-- </auto-generated>

CREATE OR ALTER PROCEDURE [dbo].[sp_Potansiyel_GetById]
    @Id int
AS
BEGIN
    SET NOCOUNT ON;

    SELECT Id,Name,SurName,KnownName,Email,PhoneNumber,Adress,tarih,kayıttarihi,OzelSaatBilgisi,SatirAciklamasi,GenisAciklama,Fiyat
    FROM [dbo].[Potansiyel]
    WHERE [Id] = @Id
      AND IsActive = 1
END

GO

-- <auto-generated>
-- This file is generated. Do not edit manually.
-- Generated at      : 2026-01-29 09:02:51
-- Generated at (UTC): 2026-01-29 06:02:51
-- Machine: YAZILIM3
-- Generator: EntityCreator v1.0
-- Class Name: SpWriter
-- </auto-generated>

CREATE OR ALTER PROCEDURE [dbo].[sp_Potansiyel_List]
AS
BEGIN
    SET NOCOUNT ON;

    SELECT Id,Name,SurName,KnownName,Email,PhoneNumber,Adress,tarih,kayıttarihi,OzelSaatBilgisi,SatirAciklamasi,GenisAciklama,Fiyat
    FROM [dbo].[Potansiyel]
    WHERE IsActive = 1
END

GO

-- <auto-generated>
-- This file is generated. Do not edit manually.
-- Generated at      : 2026-01-29 09:02:51
-- Generated at (UTC): 2026-01-29 06:02:51
-- Machine: YAZILIM3
-- Generator: EntityCreator v1.0
-- Class Name: SpWriter
-- </auto-generated>

CREATE OR ALTER PROCEDURE [dbo].[sp_Potansiyel_PagedList]
    @Page INT,
    @PageSize INT
AS
BEGIN
    SET NOCOUNT ON;

    SELECT Id,Name,SurName,KnownName,Email,PhoneNumber,Adress,tarih,kayıttarihi,OzelSaatBilgisi,SatirAciklamasi,GenisAciklama,Fiyat
    FROM [dbo].[Potansiyel]
    WHERE IsActive = 1
    ORDER BY [Id] DESC
    OFFSET (@Page - 1) * @PageSize ROWS
    FETCH NEXT @PageSize ROWS ONLY;

    SELECT COUNT(1) AS TotalCount
    FROM [dbo].[Potansiyel]
    WHERE IsActive = 1
END

