-- <auto-generated>
-- This file is generated. Do not edit manually.
-- Generated at      : 2026-01-26 18:51:00
-- Generated at (UTC): 2026-01-26 15:51:00
-- Machine: YAZILIM3
-- Generator: EntityCreator v1.0
-- Class Name: SpWriter
-- </auto-generated>

CREATE OR ALTER PROCEDURE [dbo].[sp_Potansiyel_Insert]
    @Name nvarchar(50),
    @SurName nvarchar(50),
    @KnownName nvarchar(50),
    @Email nvarchar(100),
    @PhoneNumber nvarchar(50),
    @Adress int,
    @tarih date = NULL,
    @kayıttarihi datetime = NULL,
    @saat time = NULL,
    @satir nvarchar(10) = NULL,
    @max nvarchar(MAX) = NULL,
    @resim image = NULL
AS
BEGIN
    SET NOCOUNT ON;

    INSERT INTO [dbo].[Potansiyel]
    ([Name], [SurName], [KnownName], [Email], [PhoneNumber], [IsActive], [Adress], [tarih], [kayıttarihi], [saat], [satir], [max], [resim])
    VALUES
    (@Name, @SurName, @KnownName, @Email, @PhoneNumber, 1, @Adress, @tarih, @kayıttarihi, @saat, @satir, @max, @resim);

    SELECT SCOPE_IDENTITY() AS NewId;
END

GO

-- <auto-generated>
-- This file is generated. Do not edit manually.
-- Generated at      : 2026-01-26 18:51:00
-- Generated at (UTC): 2026-01-26 15:51:00
-- Machine: YAZILIM3
-- Generator: EntityCreator v1.0
-- Class Name: SpWriter
-- </auto-generated>

CREATE OR ALTER PROCEDURE [dbo].[sp_Potansiyel_Update]
    @Id int,
    @Name nvarchar(50),
    @SurName nvarchar(50),
    @KnownName nvarchar(50),
    @Email nvarchar(100),
    @PhoneNumber nvarchar(50),
    @Adress int,
    @tarih date = NULL,
    @kayıttarihi datetime = NULL,
    @saat time = NULL,
    @satir nvarchar(10) = NULL,
    @max nvarchar(MAX) = NULL,
    @resim image = NULL
AS
BEGIN
    SET NOCOUNT ON;

    UPDATE [dbo].[Potansiyel]
    SET
        [Name] = @Name,
        [SurName] = @SurName,
        [KnownName] = @KnownName,
        [Email] = @Email,
        [PhoneNumber] = @PhoneNumber,
        [Adress] = @Adress,
        [tarih] = @tarih,
        [kayıttarihi] = @kayıttarihi,
        [saat] = @saat,
        [satir] = @satir,
        [max] = @max,
        [resim] = @resim
    WHERE [Id] = @Id;
END

GO

-- <auto-generated>
-- This file is generated. Do not edit manually.
-- Generated at      : 2026-01-26 18:51:00
-- Generated at (UTC): 2026-01-26 15:51:00
-- Machine: YAZILIM3
-- Generator: EntityCreator v1.0
-- Class Name: SpWriter
-- </auto-generated>

CREATE OR ALTER PROCEDURE [dbo].[sp_Potansiyel_Delete]
    @Id int
AS
BEGIN
    SET NOCOUNT ON;

    DELETE FROM [dbo].[Potansiyel]
    WHERE [Id] = @Id;
END

GO

-- <auto-generated>
-- This file is generated. Do not edit manually.
-- Generated at      : 2026-01-26 18:51:00
-- Generated at (UTC): 2026-01-26 15:51:00
-- Machine: YAZILIM3
-- Generator: EntityCreator v1.0
-- Class Name: SpWriter
-- </auto-generated>

CREATE OR ALTER PROCEDURE [dbo].[sp_Potansiyel_DeleteSoft]
    @Id int
AS
BEGIN
    SET NOCOUNT ON;

    UPDATE [dbo].[Potansiyel]
    SET [IsActive] = 0
    WHERE [Id] = @Id;
END

GO

-- <auto-generated>
-- This file is generated. Do not edit manually.
-- Generated at      : 2026-01-26 18:51:00
-- Generated at (UTC): 2026-01-26 15:51:00
-- Machine: YAZILIM3
-- Generator: EntityCreator v1.0
-- Class Name: SpWriter
-- </auto-generated>

CREATE OR ALTER PROCEDURE [dbo].[sp_Potansiyel_GetById]
    @Id int
AS
BEGIN
    SET NOCOUNT ON;

    SELECT * FROM [dbo].[Potansiyel]
    WHERE [Id] = @Id
      AND IsActive = 1
END

GO

-- <auto-generated>
-- This file is generated. Do not edit manually.
-- Generated at      : 2026-01-26 18:51:00
-- Generated at (UTC): 2026-01-26 15:51:00
-- Machine: YAZILIM3
-- Generator: EntityCreator v1.0
-- Class Name: SpWriter
-- </auto-generated>

CREATE OR ALTER PROCEDURE [dbo].[sp_Potansiyel_List]
AS
BEGIN
    SET NOCOUNT ON;

    SELECT * FROM [dbo].[Potansiyel]
    WHERE IsActive = 1
END

GO

-- <auto-generated>
-- This file is generated. Do not edit manually.
-- Generated at      : 2026-01-26 18:51:00
-- Generated at (UTC): 2026-01-26 15:51:00
-- Machine: YAZILIM3
-- Generator: EntityCreator v1.0
-- Class Name: SpWriter
-- </auto-generated>

CREATE OR ALTER PROCEDURE [dbo].[sp_Potansiyel_PagedList]
    @Page INT,
    @PageSize INT
AS
BEGIN
    SET NOCOUNT ON;

    SELECT * FROM [dbo].[Potansiyel]
    WHERE IsActive = 1
    ORDER BY [Id] DESC
    OFFSET (@Page - 1) * @PageSize ROWS
    FETCH NEXT @PageSize ROWS ONLY;

    SELECT COUNT(1) AS TotalCount
    FROM [dbo].[Potansiyel]
    WHERE IsActive = 1
END

