-- <auto-generated>
-- This file is generated. Do not edit manually.
-- Generated at      : 2026-04-21 14:26:25
-- Generated at (UTC): 2026-04-21 11:26:25
-- Machine: YAZILIM3
-- Generator: EntityCreator v1.0
-- Class Name: SpWriter
-- </auto-generated>

CREATE OR ALTER PROCEDURE [dbo].[sp_ProductCategory_Insert]
    @ProductId int,
    @CategoryId int
AS
BEGIN
    SET NOCOUNT ON;

    INSERT INTO [dbo].[ProductCategory]
    ([ProductId], [CategoryId])
    VALUES
    (@ProductId, @CategoryId);

    SELECT SCOPE_IDENTITY() AS NewId;
END

GO

-- <auto-generated>
-- This file is generated. Do not edit manually.
-- Generated at      : 2026-04-21 14:26:25
-- Generated at (UTC): 2026-04-21 11:26:25
-- Machine: YAZILIM3
-- Generator: EntityCreator v1.0
-- Class Name: SpWriter
-- </auto-generated>

CREATE OR ALTER PROCEDURE [dbo].[sp_ProductCategory_Update]
    @Id int,
    @ProductId int,
    @CategoryId int
AS
BEGIN
    SET NOCOUNT ON;

    UPDATE [dbo].[ProductCategory]
    SET
        [ProductId] = @ProductId,
        [CategoryId] = @CategoryId
    WHERE [Id] = @Id;
END

GO

-- <auto-generated>
-- This file is generated. Do not edit manually.
-- Generated at      : 2026-04-21 14:26:25
-- Generated at (UTC): 2026-04-21 11:26:25
-- Machine: YAZILIM3
-- Generator: EntityCreator v1.0
-- Class Name: SpWriter
-- </auto-generated>

CREATE OR ALTER PROCEDURE [dbo].[sp_ProductCategory_Delete]
    @Id int
AS
BEGIN
    SET NOCOUNT ON;

    DELETE FROM [dbo].[ProductCategory]
    WHERE [Id] = @Id;
END

GO


GO

-- <auto-generated>
-- This file is generated. Do not edit manually.
-- Generated at      : 2026-04-21 14:26:25
-- Generated at (UTC): 2026-04-21 11:26:25
-- Machine: YAZILIM3
-- Generator: EntityCreator v1.0
-- Class Name: SpWriter
-- </auto-generated>

CREATE OR ALTER PROCEDURE [dbo].[sp_ProductCategory_GetById]
    @Id int
AS
BEGIN
    SET NOCOUNT ON;

    SELECT Id,ProductId,CategoryId
    FROM [dbo].[ProductCategory]
    WHERE [Id] = @Id
END

GO

-- <auto-generated>
-- This file is generated. Do not edit manually.
-- Generated at      : 2026-04-21 14:26:25
-- Generated at (UTC): 2026-04-21 11:26:25
-- Machine: YAZILIM3
-- Generator: EntityCreator v1.0
-- Class Name: SpWriter
-- </auto-generated>

CREATE OR ALTER PROCEDURE [dbo].[sp_ProductCategory_List]
AS
BEGIN
    SET NOCOUNT ON;

    SELECT Id,ProductId,CategoryId
    FROM [dbo].[ProductCategory]
END

GO

-- <auto-generated>
-- This file is generated. Do not edit manually.
-- Generated at      : 2026-04-21 14:26:25
-- Generated at (UTC): 2026-04-21 11:26:25
-- Machine: YAZILIM3
-- Generator: EntityCreator v1.0
-- Class Name: SpWriter
-- </auto-generated>

CREATE OR ALTER PROCEDURE [dbo].[sp_ProductCategory_PagedList]
    @Page INT,
    @PageSize INT
AS
BEGIN
    SET NOCOUNT ON;

    SELECT Id,ProductId,CategoryId
    FROM [dbo].[ProductCategory]
    ORDER BY [Id] DESC
    OFFSET (@Page - 1) * @PageSize ROWS
    FETCH NEXT @PageSize ROWS ONLY;

    SELECT COUNT(1) AS TotalCount
    FROM [dbo].[ProductCategory]
END

