-- <auto-generated>
-- This file is generated. Do not edit manually.
-- Generated at      : 2026-03-29 20:43:36
-- Generated at (UTC): 2026-03-29 17:43:36
-- Machine: DESKTOP-IITN2G2
-- Generator: EntityCreator v1.0
-- Class Name: SpWriter
-- </auto-generated>

CREATE OR ALTER PROCEDURE [dbo].[sp_Reason_Insert]
    @Reasondesc nvarchar(100),
    @IsCustom bit = NULL
AS
BEGIN
    SET NOCOUNT ON;

    INSERT INTO [dbo].[Reason]
    ([Reasondesc], [IsActive], [IsCustom])
    VALUES
    (@Reasondesc, 1, @IsCustom);

    SELECT SCOPE_IDENTITY() AS NewId;
END

GO

-- <auto-generated>
-- This file is generated. Do not edit manually.
-- Generated at      : 2026-03-29 20:43:36
-- Generated at (UTC): 2026-03-29 17:43:36
-- Machine: DESKTOP-IITN2G2
-- Generator: EntityCreator v1.0
-- Class Name: SpWriter
-- </auto-generated>

CREATE OR ALTER PROCEDURE [dbo].[sp_Reason_Update]
    @Id int,
    @Reasondesc nvarchar(100),
    @IsCustom bit = NULL
AS
BEGIN
    SET NOCOUNT ON;

    UPDATE [dbo].[Reason]
    SET
        [Reasondesc] = @Reasondesc,
        [IsCustom] = @IsCustom
    WHERE [Id] = @Id;
END

GO

-- <auto-generated>
-- This file is generated. Do not edit manually.
-- Generated at      : 2026-03-29 20:43:36
-- Generated at (UTC): 2026-03-29 17:43:36
-- Machine: DESKTOP-IITN2G2
-- Generator: EntityCreator v1.0
-- Class Name: SpWriter
-- </auto-generated>

CREATE OR ALTER PROCEDURE [dbo].[sp_Reason_Delete]
    @Id int
AS
BEGIN
    SET NOCOUNT ON;

    DELETE FROM [dbo].[Reason]
    WHERE [Id] = @Id;
END

GO

-- <auto-generated>
-- This file is generated. Do not edit manually.
-- Generated at      : 2026-03-29 20:43:36
-- Generated at (UTC): 2026-03-29 17:43:36
-- Machine: DESKTOP-IITN2G2
-- Generator: EntityCreator v1.0
-- Class Name: SpWriter
-- </auto-generated>

CREATE OR ALTER PROCEDURE [dbo].[sp_Reason_DeleteSoft]
    @Id int
AS
BEGIN
    SET NOCOUNT ON;

    UPDATE [dbo].[Reason]
    SET [IsActive] = 0
    WHERE [Id] = @Id;
END

GO

-- <auto-generated>
-- This file is generated. Do not edit manually.
-- Generated at      : 2026-03-29 20:43:36
-- Generated at (UTC): 2026-03-29 17:43:36
-- Machine: DESKTOP-IITN2G2
-- Generator: EntityCreator v1.0
-- Class Name: SpWriter
-- </auto-generated>

CREATE OR ALTER PROCEDURE [dbo].[sp_Reason_GetById]
    @Id int
AS
BEGIN
    SET NOCOUNT ON;

    SELECT Id,Reasondesc,IsCustom
    FROM [dbo].[Reason]
    WHERE [Id] = @Id
      AND IsActive = 1
END

GO

-- <auto-generated>
-- This file is generated. Do not edit manually.
-- Generated at      : 2026-03-29 20:43:36
-- Generated at (UTC): 2026-03-29 17:43:36
-- Machine: DESKTOP-IITN2G2
-- Generator: EntityCreator v1.0
-- Class Name: SpWriter
-- </auto-generated>

CREATE OR ALTER PROCEDURE [dbo].[sp_Reason_List]
AS
BEGIN
    SET NOCOUNT ON;

    SELECT Id,Reasondesc,IsCustom
    FROM [dbo].[Reason]
    WHERE IsActive = 1
END

GO

-- <auto-generated>
-- This file is generated. Do not edit manually.
-- Generated at      : 2026-03-29 20:43:36
-- Generated at (UTC): 2026-03-29 17:43:36
-- Machine: DESKTOP-IITN2G2
-- Generator: EntityCreator v1.0
-- Class Name: SpWriter
-- </auto-generated>

CREATE OR ALTER PROCEDURE [dbo].[sp_Reason_PagedList]
    @Page INT,
    @PageSize INT
AS
BEGIN
    SET NOCOUNT ON;

    SELECT Id,Reasondesc,IsCustom
    FROM [dbo].[Reason]
    WHERE IsActive = 1
    ORDER BY [Id] DESC
    OFFSET (@Page - 1) * @PageSize ROWS
    FETCH NEXT @PageSize ROWS ONLY;

    SELECT COUNT(1) AS TotalCount
    FROM [dbo].[Reason]
    WHERE IsActive = 1
END

