-- <auto-generated>
-- This file is generated. Do not edit manually.
-- Generated at      : 2026-02-19 17:07:06
-- Generated at (UTC): 2026-02-19 14:07:06
-- Machine: YAZILIM3
-- Generator: EntityCreator v1.0
-- Class Name: SpWriter
-- </auto-generated>

CREATE OR ALTER PROCEDURE [dbo].[sp_Tasit_Insert]
    @Aciklama nvarchar(50),
    @Tipi int,
    @PlakaKodu nvarchar(50),
    @Sehir nvarchar(50) = NULL
AS
BEGIN
    SET NOCOUNT ON;

    INSERT INTO [dbo].[Tasit]
    ([Aciklama], [Tipi], [PlakaKodu], [Sehir])
    VALUES
    (@Aciklama, @Tipi, @PlakaKodu, @Sehir);

    SELECT SCOPE_IDENTITY() AS NewId;
END

GO

-- <auto-generated>
-- This file is generated. Do not edit manually.
-- Generated at      : 2026-02-19 17:07:06
-- Generated at (UTC): 2026-02-19 14:07:06
-- Machine: YAZILIM3
-- Generator: EntityCreator v1.0
-- Class Name: SpWriter
-- </auto-generated>

CREATE OR ALTER PROCEDURE [dbo].[sp_Tasit_Update]
    @Id int,
    @Aciklama nvarchar(50),
    @Tipi int,
    @PlakaKodu nvarchar(50),
    @Sehir nvarchar(50) = NULL
AS
BEGIN
    SET NOCOUNT ON;

    UPDATE [dbo].[Tasit]
    SET
        [Aciklama] = @Aciklama,
        [Tipi] = @Tipi,
        [PlakaKodu] = @PlakaKodu,
        [Sehir] = @Sehir
    WHERE [Id] = @Id;
END

GO

-- <auto-generated>
-- This file is generated. Do not edit manually.
-- Generated at      : 2026-02-19 17:07:06
-- Generated at (UTC): 2026-02-19 14:07:06
-- Machine: YAZILIM3
-- Generator: EntityCreator v1.0
-- Class Name: SpWriter
-- </auto-generated>

CREATE OR ALTER PROCEDURE [dbo].[sp_Tasit_Delete]
    @Id int
AS
BEGIN
    SET NOCOUNT ON;

    DELETE FROM [dbo].[Tasit]
    WHERE [Id] = @Id;
END

GO


GO

-- <auto-generated>
-- This file is generated. Do not edit manually.
-- Generated at      : 2026-02-19 17:07:06
-- Generated at (UTC): 2026-02-19 14:07:06
-- Machine: YAZILIM3
-- Generator: EntityCreator v1.0
-- Class Name: SpWriter
-- </auto-generated>

CREATE OR ALTER PROCEDURE [dbo].[sp_Tasit_GetById]
    @Id int
AS
BEGIN
    SET NOCOUNT ON;

    SELECT Id,Aciklama,Tipi,PlakaKodu,Sehir
    FROM [dbo].[Tasit]
    WHERE [Id] = @Id
END

GO

-- <auto-generated>
-- This file is generated. Do not edit manually.
-- Generated at      : 2026-02-19 17:07:06
-- Generated at (UTC): 2026-02-19 14:07:06
-- Machine: YAZILIM3
-- Generator: EntityCreator v1.0
-- Class Name: SpWriter
-- </auto-generated>

CREATE OR ALTER PROCEDURE [dbo].[sp_Tasit_List]
AS
BEGIN
    SET NOCOUNT ON;

    SELECT Id,Aciklama,Tipi,PlakaKodu,Sehir
    FROM [dbo].[Tasit]
END

GO

-- <auto-generated>
-- This file is generated. Do not edit manually.
-- Generated at      : 2026-02-19 17:07:06
-- Generated at (UTC): 2026-02-19 14:07:06
-- Machine: YAZILIM3
-- Generator: EntityCreator v1.0
-- Class Name: SpWriter
-- </auto-generated>

CREATE OR ALTER PROCEDURE [dbo].[sp_Tasit_PagedList]
    @Page INT,
    @PageSize INT
AS
BEGIN
    SET NOCOUNT ON;

    SELECT Id,Aciklama,Tipi,PlakaKodu,Sehir
    FROM [dbo].[Tasit]
    ORDER BY [Id] DESC
    OFFSET (@Page - 1) * @PageSize ROWS
    FETCH NEXT @PageSize ROWS ONLY;

    SELECT COUNT(1) AS TotalCount
    FROM [dbo].[Tasit]
END

