-- <auto-generated>
-- This file is generated. Do not edit manually.
-- Generated at      : 2026-01-24 20:57:44
-- Generated at (UTC): 2026-01-24 17:57:44
-- Machine: DESKTOP-IITN2G2
-- Generator: EntityCreator v1.0
-- Class Name: SpWriter
-- </auto-generated>

CREATE OR ALTER PROCEDURE [dbo].[sp_XEROX_Insert]
    @BigId bigint = NULL,
    @UniqueId uniqueidentifier = NULL,
    @IntValue int = NULL,
    @SmallIntValue smallint = NULL,
    @TinyIntValue tinyint = NULL,
    @BitValue bit = NULL,
    @DecimalValue decimal(18,2) = NULL,
    @NumericValue numeric(10,4) = NULL,
    @MoneyValue money = NULL,
    @SmallMoneyValue smallmoney = NULL,
    @FloatValue float = NULL,
    @RealValue real = NULL,
    @DateValue date = NULL,
    @TimeValue time = NULL,
    @DateTimeValue datetime = NULL,
    @SmallDateTimeValue smalldatetime = NULL,
    @DateTime2Value datetime2 = NULL,
    @DateTimeOffsetValue datetimeoffset = NULL,
    @CharValue char(10) = NULL,
    @VarCharValue varchar(100) = NULL,
    @VarCharMaxValue varchar(MAX) = NULL,
    @NCharValue nchar(10) = NULL,
    @NVarCharValue nvarchar(100) = NULL,
    @NVarCharMaxValue nvarchar(MAX) = NULL,
    @NTextValue ntext = NULL,
    @BinaryValue binary = NULL,
    @VarBinaryValue varbinary = NULL,
    @VarBinaryMaxValue varbinary = NULL,
    @ImageValue image = NULL,
    @XmlValue xml = NULL,
    @SqlVariantValue sql_variant = NULL,
    @RowVersionValue timestamp = NULL,
    @HierarchyIdValue hierarchyid = NULL,
    @GeographyValue geography = NULL,
    @GeometryValue geometry = NULL
AS
BEGIN
    SET NOCOUNT ON;

    INSERT INTO [dbo].[XEROX]
    ([BigId], [UniqueId], [IntValue], [SmallIntValue], [TinyIntValue], [BitValue], [DecimalValue], [NumericValue], [MoneyValue], [SmallMoneyValue], [FloatValue], [RealValue], [DateValue], [TimeValue], [DateTimeValue], [SmallDateTimeValue], [DateTime2Value], [DateTimeOffsetValue], [CharValue], [VarCharValue], [VarCharMaxValue], [NCharValue], [NVarCharValue], [NVarCharMaxValue], [NTextValue], [BinaryValue], [VarBinaryValue], [VarBinaryMaxValue], [ImageValue], [XmlValue], [SqlVariantValue], [RowVersionValue], [HierarchyIdValue], [GeographyValue], [GeometryValue], [IsActive], [InsertDate])
    VALUES
    (@BigId, @UniqueId, @IntValue, @SmallIntValue, @TinyIntValue, @BitValue, @DecimalValue, @NumericValue, @MoneyValue, @SmallMoneyValue, @FloatValue, @RealValue, @DateValue, @TimeValue, @DateTimeValue, @SmallDateTimeValue, @DateTime2Value, @DateTimeOffsetValue, @CharValue, @VarCharValue, @VarCharMaxValue, @NCharValue, @NVarCharValue, @NVarCharMaxValue, @NTextValue, @BinaryValue, @VarBinaryValue, @VarBinaryMaxValue, @ImageValue, @XmlValue, @SqlVariantValue, @RowVersionValue, @HierarchyIdValue, @GeographyValue, @GeometryValue, 1, GETDATE());

    SELECT SCOPE_IDENTITY() AS NewId;
END

GO

-- <auto-generated>
-- This file is generated. Do not edit manually.
-- Generated at      : 2026-01-24 20:57:45
-- Generated at (UTC): 2026-01-24 17:57:45
-- Machine: DESKTOP-IITN2G2
-- Generator: EntityCreator v1.0
-- Class Name: SpWriter
-- </auto-generated>

CREATE OR ALTER PROCEDURE [dbo].[sp_XEROX_Update]
    @Id int,
    @BigId bigint = NULL,
    @UniqueId uniqueidentifier = NULL,
    @IntValue int = NULL,
    @SmallIntValue smallint = NULL,
    @TinyIntValue tinyint = NULL,
    @BitValue bit = NULL,
    @DecimalValue decimal(18,2) = NULL,
    @NumericValue numeric(10,4) = NULL,
    @MoneyValue money = NULL,
    @SmallMoneyValue smallmoney = NULL,
    @FloatValue float = NULL,
    @RealValue real = NULL,
    @DateValue date = NULL,
    @TimeValue time = NULL,
    @DateTimeValue datetime = NULL,
    @SmallDateTimeValue smalldatetime = NULL,
    @DateTime2Value datetime2 = NULL,
    @DateTimeOffsetValue datetimeoffset = NULL,
    @CharValue char(10) = NULL,
    @VarCharValue varchar(100) = NULL,
    @VarCharMaxValue varchar(MAX) = NULL,
    @NCharValue nchar(10) = NULL,
    @NVarCharValue nvarchar(100) = NULL,
    @NVarCharMaxValue nvarchar(MAX) = NULL,
    @NTextValue ntext = NULL,
    @BinaryValue binary = NULL,
    @VarBinaryValue varbinary = NULL,
    @VarBinaryMaxValue varbinary = NULL,
    @ImageValue image = NULL,
    @XmlValue xml = NULL,
    @SqlVariantValue sql_variant = NULL,
    @RowVersionValue timestamp = NULL,
    @HierarchyIdValue hierarchyid = NULL,
    @GeographyValue geography = NULL,
    @GeometryValue geometry = NULL,
    @UpdateDate datetime2 = NULL
AS
BEGIN
    SET NOCOUNT ON;

    UPDATE [dbo].[XEROX]
    SET
        [BigId] = @BigId,
        [UniqueId] = @UniqueId,
        [IntValue] = @IntValue,
        [SmallIntValue] = @SmallIntValue,
        [TinyIntValue] = @TinyIntValue,
        [BitValue] = @BitValue,
        [DecimalValue] = @DecimalValue,
        [NumericValue] = @NumericValue,
        [MoneyValue] = @MoneyValue,
        [SmallMoneyValue] = @SmallMoneyValue,
        [FloatValue] = @FloatValue,
        [RealValue] = @RealValue,
        [DateValue] = @DateValue,
        [TimeValue] = @TimeValue,
        [DateTimeValue] = @DateTimeValue,
        [SmallDateTimeValue] = @SmallDateTimeValue,
        [DateTime2Value] = @DateTime2Value,
        [DateTimeOffsetValue] = @DateTimeOffsetValue,
        [CharValue] = @CharValue,
        [VarCharValue] = @VarCharValue,
        [VarCharMaxValue] = @VarCharMaxValue,
        [NCharValue] = @NCharValue,
        [NVarCharValue] = @NVarCharValue,
        [NVarCharMaxValue] = @NVarCharMaxValue,
        [NTextValue] = @NTextValue,
        [BinaryValue] = @BinaryValue,
        [VarBinaryValue] = @VarBinaryValue,
        [VarBinaryMaxValue] = @VarBinaryMaxValue,
        [ImageValue] = @ImageValue,
        [XmlValue] = @XmlValue,
        [SqlVariantValue] = @SqlVariantValue,
        [RowVersionValue] = @RowVersionValue,
        [HierarchyIdValue] = @HierarchyIdValue,
        [GeographyValue] = @GeographyValue,
        [GeometryValue] = @GeometryValue,
        [UpdateDate] = GETDATE()
    WHERE [Id] = @Id;
END

GO

-- <auto-generated>
-- This file is generated. Do not edit manually.
-- Generated at      : 2026-01-24 20:57:45
-- Generated at (UTC): 2026-01-24 17:57:45
-- Machine: DESKTOP-IITN2G2
-- Generator: EntityCreator v1.0
-- Class Name: SpWriter
-- </auto-generated>

CREATE OR ALTER PROCEDURE [dbo].[sp_XEROX_Delete]
    @Id int
AS
BEGIN
    SET NOCOUNT ON;

    DELETE FROM [dbo].[XEROX]
    WHERE [Id] = @Id;
END

GO

-- <auto-generated>
-- This file is generated. Do not edit manually.
-- Generated at      : 2026-01-24 20:57:45
-- Generated at (UTC): 2026-01-24 17:57:45
-- Machine: DESKTOP-IITN2G2
-- Generator: EntityCreator v1.0
-- Class Name: SpWriter
-- </auto-generated>

CREATE OR ALTER PROCEDURE [dbo].[sp_XEROX_DeleteSoft]
    @Id int
AS
BEGIN
    SET NOCOUNT ON;

    UPDATE [dbo].[XEROX]
    SET [IsActive] = 0
    WHERE [Id] = @Id;
END

GO

-- <auto-generated>
-- This file is generated. Do not edit manually.
-- Generated at      : 2026-01-24 20:57:45
-- Generated at (UTC): 2026-01-24 17:57:45
-- Machine: DESKTOP-IITN2G2
-- Generator: EntityCreator v1.0
-- Class Name: SpWriter
-- </auto-generated>

CREATE OR ALTER PROCEDURE [dbo].[sp_XEROX_GetById]
    @Id int
AS
BEGIN
    SET NOCOUNT ON;

    SELECT * FROM [dbo].[XEROX]
    WHERE [Id] = @Id
      AND IsActive = 1
END

GO

-- <auto-generated>
-- This file is generated. Do not edit manually.
-- Generated at      : 2026-01-24 20:57:45
-- Generated at (UTC): 2026-01-24 17:57:45
-- Machine: DESKTOP-IITN2G2
-- Generator: EntityCreator v1.0
-- Class Name: SpWriter
-- </auto-generated>

CREATE OR ALTER PROCEDURE [dbo].[sp_XEROX_List]
AS
BEGIN
    SET NOCOUNT ON;

    SELECT * FROM [dbo].[XEROX]
    WHERE IsActive = 1
END

GO

-- <auto-generated>
-- This file is generated. Do not edit manually.
-- Generated at      : 2026-01-24 20:57:45
-- Generated at (UTC): 2026-01-24 17:57:45
-- Machine: DESKTOP-IITN2G2
-- Generator: EntityCreator v1.0
-- Class Name: SpWriter
-- </auto-generated>

CREATE OR ALTER PROCEDURE [dbo].[sp_XEROX_PagedList]
    @Page INT,
    @PageSize INT
AS
BEGIN
    SET NOCOUNT ON;

    SELECT * FROM [dbo].[XEROX]
    WHERE IsActive = 1
    ORDER BY [Id] DESC
    OFFSET (@Page - 1) * @PageSize ROWS
    FETCH NEXT @PageSize ROWS ONLY;

    SELECT COUNT(1) AS TotalCount
    FROM [dbo].[XEROX]
    WHERE IsActive = 1
END

