// <auto-generated>
// This file is generated. Do not edit manually.
// Generated at      : 2026-02-05 21:32:06
// Generated at (UTC): 2026-02-05 18:32:06
// Machine: DESKTOP-IITN2G2
// Generator: EntityCreator v1.0
// Class Name: ServiceWriter
// </auto-generated>

#nullable enable

#nullable enable
using System;
using System.Data;
using Microsoft.Data.SqlClient;
using System.Collections.Generic;
using Microsoft.Extensions.Configuration;
using SeramikStore.Contracts.Cart;
using SeramikStore.Contracts.Common;
using SeramikStore.Services.DTOs;

namespace SeramikStore.Services
{
    public partial class CartService : ICartService
    {
        private readonly string _connectionString;

        public CartService(IConfiguration configuration)
        {
            _connectionString = configuration.GetConnectionString("DefaultConnection");
        }

        public int Create(CartCreateDto dto)
        {
            using var conn = new SqlConnection(_connectionString);
            using var cmd = new SqlCommand("sp_Cart_Insert", conn);
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.Parameters.AddWithValue("@ProductId", (object?)dto.ProductId ?? DBNull.Value);
            cmd.Parameters.AddWithValue("@ProductCode", (object?)dto.ProductCode ?? DBNull.Value);
            cmd.Parameters.AddWithValue("@ProductName", (object?)dto.ProductName ?? DBNull.Value);
            cmd.Parameters.AddWithValue("@UnitPrice", (object?)dto.UnitPrice ?? DBNull.Value);
            cmd.Parameters.AddWithValue("@Quantity", (object?)dto.Quantity ?? DBNull.Value);
            cmd.Parameters.AddWithValue("@TotalAmount", (object?)dto.TotalAmount ?? DBNull.Value);
            cmd.Parameters.AddWithValue("@UserId", (object?)dto.UserId ?? DBNull.Value);
            cmd.Parameters.AddWithValue("@cart_id_token", (object?)dto.cart_id_token ?? DBNull.Value);
            conn.Open();
            return Convert.ToInt32(cmd.ExecuteScalar());
        }
        

        public void Update(CartUpdateDto dto)
        {
            using var conn = new SqlConnection(_connectionString);
            using var cmd = new SqlCommand("sp_Cart_Update", conn);
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.Parameters.AddWithValue("@Id", dto.Id);
            cmd.Parameters.AddWithValue("@ProductId", (object?)dto.ProductId ?? DBNull.Value);
            cmd.Parameters.AddWithValue("@ProductCode", (object?)dto.ProductCode ?? DBNull.Value);
            cmd.Parameters.AddWithValue("@ProductName", (object?)dto.ProductName ?? DBNull.Value);
            cmd.Parameters.AddWithValue("@UnitPrice", (object?)dto.UnitPrice ?? DBNull.Value);
            cmd.Parameters.AddWithValue("@Quantity", (object?)dto.Quantity ?? DBNull.Value);
            cmd.Parameters.AddWithValue("@TotalAmount", (object?)dto.TotalAmount ?? DBNull.Value);
            cmd.Parameters.AddWithValue("@UserId", (object?)dto.UserId ?? DBNull.Value);
            cmd.Parameters.AddWithValue("@cart_id_token", (object?)dto.cart_id_token ?? DBNull.Value);
            conn.Open();
            cmd.ExecuteNonQuery();
        }
        

        public void Delete(int id)
        {
            using var conn = new SqlConnection(_connectionString);
            using var cmd = new SqlCommand("sp_Cart_Delete", conn);
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.Parameters.AddWithValue("@Id", id);
            conn.Open();
            cmd.ExecuteNonQuery();
        }

        public void DeleteSoft(int id)
        {
            using var conn = new SqlConnection(_connectionString);
            using var cmd = new SqlCommand("sp_Cart_DeleteSoft", conn);
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.Parameters.AddWithValue("@Id", id);
            conn.Open();
            cmd.ExecuteNonQuery();
        }

        public CartDto? GetById(int id)
        {
            using var conn = new SqlConnection(_connectionString);
            using var cmd = new SqlCommand("sp_Cart_GetById", conn);
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.Parameters.AddWithValue("@Id", id);
            conn.Open();
            using var rdr = cmd.ExecuteReader();
            if (!rdr.Read()) return null;
        
            return new CartDto
            {
                Id = (int)rdr["Id"],
                ProductId = (int)rdr["ProductId"],
                ProductCode = (string)rdr["ProductCode"],
                ProductName = (string)rdr["ProductName"],
                UnitPrice = (decimal)rdr["UnitPrice"],
                Quantity = (int)rdr["Quantity"],
                TotalAmount = (decimal)rdr["TotalAmount"],
                UserId = rdr["UserId"] == DBNull.Value ? (int?)null : (int)rdr["UserId"],
                cart_id_token = rdr["cart_id_token"] == DBNull.Value ? (string?)null : (string)rdr["cart_id_token"],
            };
        }
        

        public List<CartListItemDto> List()
        {
            var list = new List<CartListItemDto>();
            using var conn = new SqlConnection(_connectionString);
            using var cmd = new SqlCommand("sp_Cart_List", conn);
            cmd.CommandType = CommandType.StoredProcedure;
            conn.Open();
            using var rdr = cmd.ExecuteReader();
            while (rdr.Read())
            {
                list.Add(new CartListItemDto
                {
                    Id = (int)rdr["Id"],
                    ProductId = (int)rdr["ProductId"],
                    ProductCode = (string)rdr["ProductCode"],
                    ProductName = (string)rdr["ProductName"],
                    UnitPrice = (decimal)rdr["UnitPrice"],
                    Quantity = (int)rdr["Quantity"],
                    TotalAmount = (decimal)rdr["TotalAmount"],
                    UserId = rdr["UserId"] == DBNull.Value ? (int?)null : (int)rdr["UserId"],
                    cart_id_token = rdr["cart_id_token"] == DBNull.Value ? (string?)null : (string)rdr["cart_id_token"],
                });
            }
            return list;
        }
        

        public PagedResult<CartListItemDto> PagedList(int page, int pageSize)
        {
            var result = new PagedResult<CartListItemDto>();
            using var conn = new SqlConnection(_connectionString);
            using var cmd = new SqlCommand("sp_Cart_PagedList", conn);
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.Parameters.AddWithValue("@Page", page);
            cmd.Parameters.AddWithValue("@PageSize", pageSize);
            conn.Open();
            using var rdr = cmd.ExecuteReader();
            while (rdr.Read())
            {
                result.Items.Add(new CartListItemDto
                {
                    Id = (int)rdr["Id"],
                    ProductId = (int)rdr["ProductId"],
                    ProductCode = (string)rdr["ProductCode"],
                    ProductName = (string)rdr["ProductName"],
                    UnitPrice = (decimal)rdr["UnitPrice"],
                    Quantity = (int)rdr["Quantity"],
                    TotalAmount = (decimal)rdr["TotalAmount"],
                    UserId = rdr["UserId"] == DBNull.Value ? (int?)null : (int)rdr["UserId"],
                    cart_id_token = rdr["cart_id_token"] == DBNull.Value ? (string?)null : (string)rdr["cart_id_token"],
                });
            }
        
            if (rdr.NextResult() && rdr.Read())
                result.TotalCount = (int)rdr["TotalCount"];
        
            return result;
        }


    }
}
