// <auto-generated>
// This file is generated. Do not edit manually.
// Generated at      : 2026-01-17 22:18:19
// Generated at (UTC): 2026-01-17 19:18:19
// Machine: DESKTOP-IITN2G2
// Generator: EntityCreator v1.0
// Class Name: ServiceWriter
// </auto-generated>

using System;
using System.Data;
using Microsoft.Data.SqlClient;
using System.Collections.Generic;
using Microsoft.Extensions.Configuration;
using SeramikStore.Contracts.Cart;
using SeramikStore.Contracts.Common;

namespace SeramikStore.Services
{
    public partial class CartService : ICartService
    {
        private readonly string _connectionString;

        public CartService(IConfiguration configuration)
        {
            _connectionString = configuration.GetConnectionString("DefaultConnection");
        }

        public int Create(CartCreateDto dto)
        {
            using var conn = new SqlConnection(_connectionString);
            using var cmd = new SqlCommand("sp_Cart_Insert", conn);
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.Parameters.AddWithValue("@ProductId", dto.ProductId);
            cmd.Parameters.AddWithValue("@ProductCode", dto.ProductCode);
            cmd.Parameters.AddWithValue("@ProductName", dto.ProductName);
            cmd.Parameters.AddWithValue("@UnitPrice", dto.UnitPrice);
            cmd.Parameters.AddWithValue("@Quantity", dto.Quantity);
            cmd.Parameters.AddWithValue("@TotalAmount", dto.TotalAmount);
            cmd.Parameters.AddWithValue("@UserId", dto.UserId);
            conn.Open();
            return Convert.ToInt32(cmd.ExecuteScalar());
        }
        

        public void Update(CartUpdateDto dto)
        {
            using var conn = new SqlConnection(_connectionString);
            using var cmd = new SqlCommand("sp_Cart_Update", conn);
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.Parameters.AddWithValue("@Id", dto.Id);
            cmd.Parameters.AddWithValue("@ProductId", dto.ProductId);
            cmd.Parameters.AddWithValue("@ProductCode", dto.ProductCode);
            cmd.Parameters.AddWithValue("@ProductName", dto.ProductName);
            cmd.Parameters.AddWithValue("@UnitPrice", dto.UnitPrice);
            cmd.Parameters.AddWithValue("@Quantity", dto.Quantity);
            cmd.Parameters.AddWithValue("@TotalAmount", dto.TotalAmount);
            cmd.Parameters.AddWithValue("@UserId", dto.UserId);
            cmd.Parameters.AddWithValue("@UpdateDate", dto.UpdateDate);
            cmd.Parameters.AddWithValue("@IsActive", dto.IsActive);
            conn.Open();
            cmd.ExecuteNonQuery();
        }
        

        public void Delete(int id)
        {
            using var conn = new SqlConnection(_connectionString);
            using var cmd = new SqlCommand("sp_Cart_Delete", conn);
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.Parameters.AddWithValue("@Id", id);
            conn.Open();
            cmd.ExecuteNonQuery();
        }

        public void DeleteSoft(int id)
        {
            using var conn = new SqlConnection(_connectionString);
            using var cmd = new SqlCommand("sp_Cart_DeleteSoft", conn);
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.Parameters.AddWithValue("@Id", id);
            conn.Open();
            cmd.ExecuteNonQuery();
        }

        public CartDto? GetById(int id)
        {
            using var conn = new SqlConnection(_connectionString);
            using var cmd = new SqlCommand("sp_Cart_GetById", conn);
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.Parameters.AddWithValue("@Id", id);
            conn.Open();
            using var rdr = cmd.ExecuteReader();
            if (!rdr.Read()) return null;
        
            return new CartDto
            {
                Id = (int)rdr["Id"],
                ProductId = (int)rdr["ProductId"],
                ProductCode = (string)rdr["ProductCode"],
                ProductName = (string)rdr["ProductName"],
                UnitPrice = (decimal)rdr["UnitPrice"],
                Quantity = (int)rdr["Quantity"],
                TotalAmount = (decimal)rdr["TotalAmount"],
                UserId = (int)rdr["UserId"],
                InsertDate = (DateTime)rdr["InsertDate"],
                UpdateDate = (DateTime)rdr["UpdateDate"],
                IsActive = (bool)rdr["IsActive"],
            };
        }
        

        public List<CartListItemDto> List()
        {
            var list = new List<CartListItemDto>();
            using var conn = new SqlConnection(_connectionString);
            using var cmd = new SqlCommand("sp_Cart_List", conn);
            cmd.CommandType = CommandType.StoredProcedure;
            conn.Open();
            using var rdr = cmd.ExecuteReader();
            while (rdr.Read())
            {
                list.Add(new CartListItemDto
                {
                    Id = (int)rdr["Id"],
                    ProductId = (int)rdr["ProductId"],
                    ProductCode = (string)rdr["ProductCode"],
                    ProductName = (string)rdr["ProductName"],
                    UnitPrice = (decimal)rdr["UnitPrice"],
                    Quantity = (int)rdr["Quantity"],
                    TotalAmount = (decimal)rdr["TotalAmount"],
                    UserId = (int)rdr["UserId"],
                    InsertDate = (DateTime)rdr["InsertDate"],
                    IsActive = (bool)rdr["IsActive"],
                });
            }
            return list;
        }
        

        public PagedResult<CartListItemDto> PagedList(int page, int pageSize)
        {
            var result = new PagedResult<CartListItemDto>();
            using var conn = new SqlConnection(_connectionString);
            using var cmd = new SqlCommand("sp_Cart_PagedList", conn);
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.Parameters.AddWithValue("@Page", page);
            cmd.Parameters.AddWithValue("@PageSize", pageSize);
            conn.Open();
            using var rdr = cmd.ExecuteReader();
            while (rdr.Read())
            {
                result.Items.Add(new CartListItemDto
                {
                    Id = (int)rdr["Id"],
                    ProductId = (int)rdr["ProductId"],
                    ProductCode = (string)rdr["ProductCode"],
                    ProductName = (string)rdr["ProductName"],
                    UnitPrice = (decimal)rdr["UnitPrice"],
                    Quantity = (int)rdr["Quantity"],
                    TotalAmount = (decimal)rdr["TotalAmount"],
                    UserId = (int)rdr["UserId"],
                    InsertDate = (DateTime)rdr["InsertDate"],
                    IsActive = (bool)rdr["IsActive"],
                });
            }
        
            if (rdr.NextResult() && rdr.Read())
                result.TotalCount = (int)rdr["TotalCount"];
        
            return result;
        }
        
    }
}
