// <auto-generated>
// This file is generated. Do not edit manually.
// Generated at      : 2026-02-08 23:46:08
// Generated at (UTC): 2026-02-08 20:46:08
// Machine: DESKTOP-IITN2G2
// Generator: EntityCreator v1.0
// Class Name: ServiceWriter
// </auto-generated>

#nullable enable

using System.Collections.Generic;
using SeramikStore.Contracts.Cart;
using SeramikStore.Contracts.Common;

namespace SeramikStore.Services
{
    public partial interface ICartService
    {
        int Create(CartCreateDto dto);
        void Update(CartUpdateDto dto);
        void Delete(int id);
        void DeleteSoft(int id);
        CartDto? GetById(int id);
        List<CartListItemDto> List();
        PagedResult<CartListItemDto> PagedList(int page, int pageSize);
    }
}
