// <auto-generated>
// This file is generated. Do not edit manually.
// Generated at      : 2026-01-25 22:46:53
// Generated at (UTC): 2026-01-25 19:46:53
// Machine: DESKTOP-IITN2G2
// Generator: EntityCreator v1.0
// Class Name: DtoWriter
// </auto-generated>

#nullable enable

using System;

namespace SeramikStore.Contracts.PERON
{
    public class PERONUpdateDto
    {
        public int DOLUId { get; set; }
        public long DOLUBigId { get; set; }
        public Guid? DOLUUniqueId { get; set; }
        public int DOLUIntValue { get; set; }
        public short DOLUSmallIntValue { get; set; }
        public byte DOLUTinyIntValue { get; set; }
        public bool DOLUBitValue { get; set; }
        public decimal? DOLUDecimalValue { get; set; }
        public decimal? DOLUNumericValue { get; set; }
        public decimal DOLUMoneyValue { get; set; }
        public decimal DOLUSmallMoneyValue { get; set; }
        public double DOLUFloatValue { get; set; }
        public float DOLURealValue { get; set; }
        public DateOnly DOLUDateValue { get; set; }
        public TimeOnly? DOLUTimeValue { get; set; }
        public DateTime DOLUDateTimeValue { get; set; }
        public DateTime DOLUSmallDateTimeValue { get; set; }
        public DateTime DOLUDateTime2Value { get; set; }
        public DateTimeOffset DOLUDateTimeOffsetValue { get; set; }
        public required string DOLUCharValue { get; set; }
        public required string DOLUVarCharValue { get; set; }
        public required string DOLUVarCharMaxValue { get; set; }
        public required string DOLUNCharValue { get; set; }
        public required string DOLUNVarCharValue { get; set; }
        public required string DOLUNVarCharMaxValue { get; set; }
        public required string DOLUNTextValue { get; set; }
        public required byte[] DOLUBinaryValue { get; set; }
        public required byte[] DOLUVarBinaryValue { get; set; }
        public required byte[] DOLUVarBinaryMaxValue { get; set; }
        public required byte[] DOLUImageValue { get; set; }
        public required string DOLUXmlValue { get; set; }
        public required object DOLUSqlVariantValue { get; set; }
        public required byte[] DOLURowVersionValue { get; set; }
        public required object DOLUHierarchyIdValue { get; set; }
        public required object DOLUGeographyValue { get; set; }
        public required object DOLUGeometryValue { get; set; }
        public bool DOLUIsActive { get; set; }
        public DateTime DOLUInsertDate { get; set; }
        public DateTime DOLUUpdateDate { get; set; }
        public long? NALBigId { get; set; }
        public Guid? NALUniqueId { get; set; }
        public int? NALIntValue { get; set; }
        public short? NALSmallIntValue { get; set; }
        public byte? NALTinyIntValue { get; set; }
        public bool? NALBitValue { get; set; }
        public decimal? NALDecimalValue { get; set; }
        public decimal? NALNumericValue { get; set; }
        public decimal? NALMoneyValue { get; set; }
        public decimal? NALSmallMoneyValue { get; set; }
        public double? NALFloatValue { get; set; }
        public float? NALRealValue { get; set; }
        public DateOnly? NALDateValue { get; set; }
        public TimeOnly? NALTimeValue { get; set; }
        public DateTime? NALDateTimeValue { get; set; }
        public DateTime? NALSmallDateTimeValue { get; set; }
        public DateTime? NALDateTime2Value { get; set; }
        public DateTimeOffset? NALDateTimeOffsetValue { get; set; }
        public string? NALCharValue { get; set; }
        public string? NALVarCharValue { get; set; }
        public string? NALVarCharMaxValue { get; set; }
        public string? NALNCharValue { get; set; }
        public string? NALNVarCharValue { get; set; }
        public string? NALNVarCharMaxValue { get; set; }
        public string? NALNTextValue { get; set; }
        public byte[]? NALBinaryValue { get; set; }
        public byte[]? NALVarBinaryValue { get; set; }
        public byte[]? NALVarBinaryMaxValue { get; set; }
        public byte[]? NALImageValue { get; set; }
        public string? NALXmlValue { get; set; }
        public object? NALSqlVariantValue { get; set; }
        public object? NALHierarchyIdValue { get; set; }
        public object? NALGeographyValue { get; set; }
        public object? NALGeometryValue { get; set; }
        public bool? NALIsActive { get; set; }
        public DateTime? NALInsertDate { get; set; }
        public DateTime? NALUpdateDate { get; set; }
    }
}
