// <auto-generated>
// This file is generated. Do not edit manually.
// Generated at      : 2026-04-21 14:26:25
// Generated at (UTC): 2026-04-21 11:26:25
// Machine: YAZILIM3
// Generator: EntityCreator v1.0
// Class Name: ServiceWriter
// </auto-generated>

#nullable enable

using System.Collections.Generic;
using SeramikStore.Contracts.ProductCategory;
using SeramikStore.Contracts.Common;

namespace SeramikStore.Services
{
    public partial interface IProductCategoryService
    {
        int Create(ProductCategoryCreateDto dto);
        void Update(ProductCategoryUpdateDto dto);
        void Delete(int id);
        void DeleteSoft(int id);
        ProductCategoryDto? GetById(int id);
        List<ProductCategoryListItemDto> List();
        PagedResult<ProductCategoryListItemDto> PagedList(int page, int pageSize);
    }
}
