// <auto-generated>
// This file is generated. Do not edit manually.
// Generated at      : 2026-04-21 14:26:25
// Generated at (UTC): 2026-04-21 11:26:25
// Machine: YAZILIM3
// Generator: EntityCreator v1.0
// Class Name: ServiceWriter
// </auto-generated>

#nullable enable

#nullable enable
using System;
using System.Data;
using Microsoft.Data.SqlClient;
using System.Collections.Generic;
using Microsoft.Extensions.Configuration;
using SeramikStore.Contracts.ProductCategory;
using SeramikStore.Contracts.Common;

namespace SeramikStore.Services
{
    public partial class ProductCategoryService : IProductCategoryService
    {
        private readonly string _connectionString;

        public ProductCategoryService(IConfiguration configuration)
        {
            _connectionString = configuration.GetConnectionString("DefaultConnection");
        }

        public int Create(ProductCategoryCreateDto dto)
        {
            using var conn = new SqlConnection(_connectionString);
            using var cmd = new SqlCommand("sp_ProductCategory_Insert", conn);
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.Parameters.AddWithValue("@ProductId", (object?)dto.ProductId ?? DBNull.Value);
            cmd.Parameters.AddWithValue("@CategoryId", (object?)dto.CategoryId ?? DBNull.Value);
            conn.Open();
            return Convert.ToInt32(cmd.ExecuteScalar());
        }
        

        public void Update(ProductCategoryUpdateDto dto)
        {
            using var conn = new SqlConnection(_connectionString);
            using var cmd = new SqlCommand("sp_ProductCategory_Update", conn);
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.Parameters.AddWithValue("@Id", dto.Id);
            cmd.Parameters.AddWithValue("@ProductId", (object?)dto.ProductId ?? DBNull.Value);
            cmd.Parameters.AddWithValue("@CategoryId", (object?)dto.CategoryId ?? DBNull.Value);
            conn.Open();
            cmd.ExecuteNonQuery();
        }
        

        public void Delete(int id)
        {
            using var conn = new SqlConnection(_connectionString);
            using var cmd = new SqlCommand("sp_ProductCategory_Delete", conn);
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.Parameters.AddWithValue("@Id", id);
            conn.Open();
            cmd.ExecuteNonQuery();
        }

        public void DeleteSoft(int id)
        {
            using var conn = new SqlConnection(_connectionString);
            using var cmd = new SqlCommand("sp_ProductCategory_DeleteSoft", conn);
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.Parameters.AddWithValue("@Id", id);
            conn.Open();
            cmd.ExecuteNonQuery();
        }

        public ProductCategoryDto? GetById(int id)
        {
            using var conn = new SqlConnection(_connectionString);
            using var cmd = new SqlCommand("sp_ProductCategory_GetById", conn);
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.Parameters.AddWithValue("@Id", id);
            conn.Open();
            using var rdr = cmd.ExecuteReader();
            if (!rdr.Read()) return null;
        
            return new ProductCategoryDto
            {
                Id = (int)rdr["Id"],
                ProductId = (int)rdr["ProductId"],
                CategoryId = (int)rdr["CategoryId"],
            };
        }
        

        public List<ProductCategoryListItemDto> List()
        {
            var list = new List<ProductCategoryListItemDto>();
            using var conn = new SqlConnection(_connectionString);
            using var cmd = new SqlCommand("sp_ProductCategory_List", conn);
            cmd.CommandType = CommandType.StoredProcedure;
            conn.Open();
            using var rdr = cmd.ExecuteReader();
            while (rdr.Read())
            {
                list.Add(new ProductCategoryListItemDto
                {
                    Id = (int)rdr["Id"],
                    ProductId = (int)rdr["ProductId"],
                    CategoryId = (int)rdr["CategoryId"],
                });
            }
            return list;
        }
        

        public PagedResult<ProductCategoryListItemDto> PagedList(int page, int pageSize)
        {
            var result = new PagedResult<ProductCategoryListItemDto>();
            using var conn = new SqlConnection(_connectionString);
            using var cmd = new SqlCommand("sp_ProductCategory_PagedList", conn);
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.Parameters.AddWithValue("@Page", page);
            cmd.Parameters.AddWithValue("@PageSize", pageSize);
            conn.Open();
            using var rdr = cmd.ExecuteReader();
            while (rdr.Read())
            {
                result.Items.Add(new ProductCategoryListItemDto
                {
                    Id = (int)rdr["Id"],
                    ProductId = (int)rdr["ProductId"],
                    CategoryId = (int)rdr["CategoryId"],
                });
            }
        
            if (rdr.NextResult() && rdr.Read())
                result.TotalCount = (int)rdr["TotalCount"];
        
            return result;
        }
        
    }
}
