// <auto-generated>
// This file is generated. Do not edit manually.
// Generated at      : 2026-02-27 17:18:33
// Generated at (UTC): 2026-02-27 14:18:33
// Machine: YAZILIM3
// Generator: EntityCreator v1.0
// Class Name: ServiceWriter
// </auto-generated>

#nullable enable

#nullable enable
using System;
using System.Data;
using Microsoft.Data.SqlClient;
using System.Collections.Generic;
using Microsoft.Extensions.Configuration;
using SeramikStore.Contracts.Araba;
using SeramikStore.Contracts.Common;

namespace SeramikStore.Services
{
    public partial class ArabaService : IArabaService
    {
        private readonly string _connectionString;

        public ArabaService(IConfiguration configuration)
        {
            _connectionString = configuration.GetConnectionString("DefaultConnection");
        }

        public int Create(ArabaCreateDto dto)
        {
            using var conn = new SqlConnection(_connectionString);
            using var cmd = new SqlCommand("sp_Araba_Insert", conn);
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.Parameters.AddWithValue("@Model", (object?)dto.Model ?? DBNull.Value);
            cmd.Parameters.AddWithValue("@Marka", (object?)dto.Marka ?? DBNull.Value);
            conn.Open();
            return Convert.ToInt32(cmd.ExecuteScalar());
        }
        

        public void Update(ArabaUpdateDto dto)
        {
            using var conn = new SqlConnection(_connectionString);
            using var cmd = new SqlCommand("sp_Araba_Update", conn);
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.Parameters.AddWithValue("@Id", dto.Id);
            cmd.Parameters.AddWithValue("@Model", (object?)dto.Model ?? DBNull.Value);
            cmd.Parameters.AddWithValue("@Marka", (object?)dto.Marka ?? DBNull.Value);
            conn.Open();
            cmd.ExecuteNonQuery();
        }
        

        public void Delete(int id)
        {
            using var conn = new SqlConnection(_connectionString);
            using var cmd = new SqlCommand("sp_Araba_Delete", conn);
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.Parameters.AddWithValue("@Id", id);
            conn.Open();
            cmd.ExecuteNonQuery();
        }

        public void DeleteSoft(int id)
        {
            using var conn = new SqlConnection(_connectionString);
            using var cmd = new SqlCommand("sp_Araba_DeleteSoft", conn);
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.Parameters.AddWithValue("@Id", id);
            conn.Open();
            cmd.ExecuteNonQuery();
        }

        public ArabaDto? GetById(int id)
        {
            using var conn = new SqlConnection(_connectionString);
            using var cmd = new SqlCommand("sp_Araba_GetById", conn);
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.Parameters.AddWithValue("@Id", id);
            conn.Open();
            using var rdr = cmd.ExecuteReader();
            if (!rdr.Read()) return null;
        
            return new ArabaDto
            {
                Id = (int)rdr["Id"],
                Model = (string)rdr["Model"],
                Marka = (string)rdr["Marka"],
            };
        }
        

        public List<ArabaListItemDto> List()
        {
            var list = new List<ArabaListItemDto>();
            using var conn = new SqlConnection(_connectionString);
            using var cmd = new SqlCommand("sp_Araba_List", conn);
            cmd.CommandType = CommandType.StoredProcedure;
            conn.Open();
            using var rdr = cmd.ExecuteReader();
            while (rdr.Read())
            {
                list.Add(new ArabaListItemDto
                {
                    Id = (int)rdr["Id"],
                    Model = (string)rdr["Model"],
                    Marka = (string)rdr["Marka"],
                });
            }
            return list;
        }
        

        public PagedResult<ArabaListItemDto> PagedList(int page, int pageSize)
        {
            var result = new PagedResult<ArabaListItemDto>();
            using var conn = new SqlConnection(_connectionString);
            using var cmd = new SqlCommand("sp_Araba_PagedList", conn);
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.Parameters.AddWithValue("@Page", page);
            cmd.Parameters.AddWithValue("@PageSize", pageSize);
            conn.Open();
            using var rdr = cmd.ExecuteReader();
            while (rdr.Read())
            {
                result.Items.Add(new ArabaListItemDto
                {
                    Id = (int)rdr["Id"],
                    Model = (string)rdr["Model"],
                    Marka = (string)rdr["Marka"],
                });
            }
        
            if (rdr.NextResult() && rdr.Read())
                result.TotalCount = (int)rdr["TotalCount"];
        
            return result;
        }
        
    }
}
