// <auto-generated>
// This file is generated. Do not edit manually.
// Generated at      : 2026-02-27 17:18:33
// Generated at (UTC): 2026-02-27 14:18:33
// Machine: YAZILIM3
// Generator: EntityCreator v1.0
// Class Name: ServiceWriter
// </auto-generated>

#nullable enable

using System.Collections.Generic;
using SeramikStore.Contracts.Araba;
using SeramikStore.Contracts.Common;

namespace SeramikStore.Services
{
    public partial interface IArabaService
    {
        int Create(ArabaCreateDto dto);
        void Update(ArabaUpdateDto dto);
        void Delete(int id);
        void DeleteSoft(int id);
        ArabaDto? GetById(int id);
        List<ArabaListItemDto> List();
        PagedResult<ArabaListItemDto> PagedList(int page, int pageSize);
    }
}
