// <auto-generated>
// This file is generated. Do not edit manually.
// Generated at      : 2026-01-29 09:02:51
// Generated at (UTC): 2026-01-29 06:02:51
// Machine: YAZILIM3
// Generator: EntityCreator v1.0
// Class Name: DtoWriter
// </auto-generated>

#nullable enable

using System;

namespace SeramikStore.Contracts.Potansiyel
{
    public class PotansiyelCreateDto
    {
        public required string Name { get; set; }
        public required string SurName { get; set; }
        public required string KnownName { get; set; }
        public required string Email { get; set; }
        public required string PhoneNumber { get; set; }
        public int Adress { get; set; }
        public DateOnly? tarih { get; set; }
        public DateTime? kayıttarihi { get; set; }
        public TimeOnly? OzelSaatBilgisi { get; set; }
        public string? SatirAciklamasi { get; set; }
        public string? GenisAciklama { get; set; }
        public decimal? Fiyat { get; set; }
    }
}
