// <auto-generated>
// This file is generated. Do not edit manually.
// Generated at      : 2026-01-25 01:45:26
// Generated at (UTC): 2026-01-24 22:45:26
// Machine: DESKTOP-IITN2G2
// Generator: EntityCreator v1.0
// Class Name: DtoWriter
// </auto-generated>

#nullable enable

using System;

namespace SeramikStore.Contracts.Potansiyel
{
    public class PotansiyelListItemDto
    {
        public int Id { get; set; }
        public required string Name { get; set; }
        public required string SurName { get; set; }
        public required string KnownName { get; set; }
        public required string Email { get; set; }
        public required string PhoneNumber { get; set; }
        public bool IsActive { get; set; }
        public int Adress { get; set; }
        public DateOnly? tarih { get; set; }
    }
}
