// <auto-generated>
// This file is generated. Do not edit manually.
// Generated at      : 2026-01-25 22:37:11
// Generated at (UTC): 2026-01-25 19:37:11
// Machine: DESKTOP-IITN2G2
// Generator: EntityCreator v1.0
// Class Name: DtoWriter
// </auto-generated>

#nullable enable

using System;

namespace SeramikStore.Contracts.Potansiyel
{
    public class PotansiyelListItemDto
    {
        public int Id { get; set; }
        public required string Name { get; set; }
        public required string SurName { get; set; }
        public required string KnownName { get; set; }
        public required string Email { get; set; }
        public required string PhoneNumber { get; set; }
        public bool IsActive { get; set; }
        public int Adress { get; set; }
        public DateOnly? tarih { get; set; }
        public DateTime? kayıttarihi { get; set; }
        public TimeOnly? saat { get; set; }
        public string? satir { get; set; }
        public string? max { get; set; }
        public byte[]? resim { get; set; }
    }
}
