// <auto-generated>
// This file is generated. Do not edit manually.
// Generated at      : 2026-01-23 11:52:32
// Generated at (UTC): 2026-01-23 08:52:32
// Machine: YAZILIM3
// Generator: EntityCreator v1.0
// Class Name: DtoWriter
// </auto-generated>

using System;

namespace SeramikStore.Contracts.Potansiyel
{
    public class PotansiyelUpdateDto
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string SurName { get; set; }
        public string KnownName { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public bool IsActive { get; set; }
    }
}
