// <auto-generated>
// This file is generated. Do not edit manually.
// Generated at      : 2026-01-24 22:23:17
// Generated at (UTC): 2026-01-24 19:23:17
// Machine: DESKTOP-IITN2G2
// Generator: EntityCreator v1.0
// Class Name: DtoWriter
// </auto-generated>

#nullable enable

using System;

namespace SeramikStore.Contracts.Potansiyel
{
    public class PotansiyelListItemDto
    {
        public int Id { get; set; }
        public string? Name { get; set; }
        public string? SurName { get; set; }
        public string? KnownName { get; set; }
        public string? Email { get; set; }
        public string? PhoneNumber { get; set; }
        public bool IsActive { get; set; }
    }
}
