// <auto-generated>
// This file is generated. Do not edit manually.
// Generated at      : 2026-03-29 20:43:37
// Generated at (UTC): 2026-03-29 17:43:37
// Machine: DESKTOP-IITN2G2
// Generator: EntityCreator v1.0
// Class Name: ServiceWriter
// </auto-generated>

#nullable enable

using System.Collections.Generic;
using SeramikStore.Contracts.Reason;
using SeramikStore.Contracts.Common;

namespace SeramikStore.Services
{
    public partial interface IReasonService
    {
        int Create(ReasonCreateDto dto);
        void Update(ReasonUpdateDto dto);
        void Delete(int id);
        void DeleteSoft(int id);
        ReasonDto? GetById(int id);
        List<ReasonListItemDto> List();
        PagedResult<ReasonListItemDto> PagedList(int page, int pageSize);
    }
}
