// <auto-generated>
// This file is generated. Do not edit manually.
// Generated at      : 2026-03-29 20:43:37
// Generated at (UTC): 2026-03-29 17:43:37
// Machine: DESKTOP-IITN2G2
// Generator: EntityCreator v1.0
// Class Name: ServiceWriter
// </auto-generated>

#nullable enable

#nullable enable
using System;
using System.Data;
using Microsoft.Data.SqlClient;
using System.Collections.Generic;
using Microsoft.Extensions.Configuration;
using SeramikStore.Contracts.Reason;
using SeramikStore.Contracts.Common;

namespace SeramikStore.Services
{
    public partial class ReasonService : IReasonService
    {
        private readonly string _connectionString;

        public ReasonService(IConfiguration configuration)
        {
            _connectionString = configuration.GetConnectionString("DefaultConnection");
        }

        public int Create(ReasonCreateDto dto)
        {
            using var conn = new SqlConnection(_connectionString);
            using var cmd = new SqlCommand("sp_Reason_Insert", conn);
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.Parameters.AddWithValue("@Reasondesc", (object?)dto.Reasondesc ?? DBNull.Value);
            cmd.Parameters.AddWithValue("@IsCustom", (object?)dto.IsCustom ?? DBNull.Value);
            conn.Open();
            return Convert.ToInt32(cmd.ExecuteScalar());
        }
        

        public void Update(ReasonUpdateDto dto)
        {
            using var conn = new SqlConnection(_connectionString);
            using var cmd = new SqlCommand("sp_Reason_Update", conn);
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.Parameters.AddWithValue("@Id", dto.Id);
            cmd.Parameters.AddWithValue("@Reasondesc", (object?)dto.Reasondesc ?? DBNull.Value);
            cmd.Parameters.AddWithValue("@IsCustom", (object?)dto.IsCustom ?? DBNull.Value);
            conn.Open();
            cmd.ExecuteNonQuery();
        }
        

        public void Delete(int id)
        {
            using var conn = new SqlConnection(_connectionString);
            using var cmd = new SqlCommand("sp_Reason_Delete", conn);
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.Parameters.AddWithValue("@Id", id);
            conn.Open();
            cmd.ExecuteNonQuery();
        }

        public void DeleteSoft(int id)
        {
            using var conn = new SqlConnection(_connectionString);
            using var cmd = new SqlCommand("sp_Reason_DeleteSoft", conn);
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.Parameters.AddWithValue("@Id", id);
            conn.Open();
            cmd.ExecuteNonQuery();
        }

        public ReasonDto? GetById(int id)
        {
            using var conn = new SqlConnection(_connectionString);
            using var cmd = new SqlCommand("sp_Reason_GetById", conn);
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.Parameters.AddWithValue("@Id", id);
            conn.Open();
            using var rdr = cmd.ExecuteReader();
            if (!rdr.Read()) return null;
        
            return new ReasonDto
            {
                Id = (int)rdr["Id"],
                Reasondesc = (string)rdr["Reasondesc"],
                IsCustom = rdr["IsCustom"] == DBNull.Value ? (bool?)null : (bool)rdr["IsCustom"],
            };
        }
        

        public List<ReasonListItemDto> List()
        {
            var list = new List<ReasonListItemDto>();
            using var conn = new SqlConnection(_connectionString);
            using var cmd = new SqlCommand("sp_Reason_List", conn);
            cmd.CommandType = CommandType.StoredProcedure;
            conn.Open();
            using var rdr = cmd.ExecuteReader();
            while (rdr.Read())
            {
                list.Add(new ReasonListItemDto
                {
                    Id = (int)rdr["Id"],
                    Reasondesc = (string)rdr["Reasondesc"],
                    IsCustom = rdr["IsCustom"] == DBNull.Value ? (bool?)null : (bool)rdr["IsCustom"],
                });
            }
            return list;
        }
        

        public PagedResult<ReasonListItemDto> PagedList(int page, int pageSize)
        {
            var result = new PagedResult<ReasonListItemDto>();
            using var conn = new SqlConnection(_connectionString);
            using var cmd = new SqlCommand("sp_Reason_PagedList", conn);
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.Parameters.AddWithValue("@Page", page);
            cmd.Parameters.AddWithValue("@PageSize", pageSize);
            conn.Open();
            using var rdr = cmd.ExecuteReader();
            while (rdr.Read())
            {
                result.Items.Add(new ReasonListItemDto
                {
                    Id = (int)rdr["Id"],
                    Reasondesc = (string)rdr["Reasondesc"],
                    IsCustom = rdr["IsCustom"] == DBNull.Value ? (bool?)null : (bool)rdr["IsCustom"],
                });
            }
        
            if (rdr.NextResult() && rdr.Read())
                result.TotalCount = (int)rdr["TotalCount"];
        
            return result;
        }
        
    }
}
