// <auto-generated>
// This file is generated. Do not edit manually.
// Generated at      : 2026-01-25 01:45:27
// Generated at (UTC): 2026-01-24 22:45:27
// Machine: DESKTOP-IITN2G2
// Generator: EntityCreator v1.0
// Class Name: ServiceWriter
// </auto-generated>

#nullable enable

using System.Collections.Generic;
using SeramikStore.Contracts.Potansiyel;
using SeramikStore.Contracts.Common;

namespace SeramikStore.Services
{
    public partial interface IPotansiyelService
    {
        int Create(PotansiyelCreateDto dto);
        void Update(PotansiyelUpdateDto dto);
        void Delete(int id);
        void DeleteSoft(int id);
        PotansiyelDto? GetById(int id);
        List<PotansiyelListItemDto> List();
        PagedResult<PotansiyelListItemDto> PagedList(int page, int pageSize);
    }
}
