// <auto-generated>
// This file is generated. Do not edit manually.
// Generated at      : 2026-01-25 13:20:44
// Generated at (UTC): 2026-01-25 10:20:44
// Machine: DESKTOP-IITN2G2
// Generator: EntityCreator v1.0
// Class Name: ServiceWriter
// </auto-generated>

#nullable enable

#nullable enable
using System;
using System.Data;
using Microsoft.Data.SqlClient;
using System.Collections.Generic;
using Microsoft.Extensions.Configuration;
using SeramikStore.Contracts.Potansiyel;
using SeramikStore.Contracts.Common;

namespace SeramikStore.Services
{
    public partial class PotansiyelService : IPotansiyelService
    {
        private readonly string _connectionString;

        public PotansiyelService(IConfiguration configuration)
        {
            _connectionString = configuration.GetConnectionString("DefaultConnection");
        }

        public int Create(PotansiyelCreateDto dto)
        {
            using var conn = new SqlConnection(_connectionString);
            using var cmd = new SqlCommand("sp_Potansiyel_Insert", conn);
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.Parameters.AddWithValue("@Name", (object?)dto.Name ?? DBNull.Value);
            cmd.Parameters.AddWithValue("@SurName", (object?)dto.SurName ?? DBNull.Value);
            cmd.Parameters.AddWithValue("@KnownName", (object?)dto.KnownName ?? DBNull.Value);
            cmd.Parameters.AddWithValue("@Email", (object?)dto.Email ?? DBNull.Value);
            cmd.Parameters.AddWithValue("@PhoneNumber", (object?)dto.PhoneNumber ?? DBNull.Value);
            cmd.Parameters.AddWithValue("@Adress", (object?)dto.Adress ?? DBNull.Value);
            cmd.Parameters.AddWithValue("@tarih", (object?)dto.tarih ?? DBNull.Value);
            conn.Open();
            return Convert.ToInt32(cmd.ExecuteScalar());
        }
        

        public void Update(PotansiyelUpdateDto dto)
        {
            using var conn = new SqlConnection(_connectionString);
            using var cmd = new SqlCommand("sp_Potansiyel_Update", conn);
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.Parameters.AddWithValue("@Id", dto.Id);
            cmd.Parameters.AddWithValue("@Name", (object?)dto.Name ?? DBNull.Value);
            cmd.Parameters.AddWithValue("@SurName", (object?)dto.SurName ?? DBNull.Value);
            cmd.Parameters.AddWithValue("@KnownName", (object?)dto.KnownName ?? DBNull.Value);
            cmd.Parameters.AddWithValue("@Email", (object?)dto.Email ?? DBNull.Value);
            cmd.Parameters.AddWithValue("@PhoneNumber", (object?)dto.PhoneNumber ?? DBNull.Value);
            cmd.Parameters.AddWithValue("@Adress", (object?)dto.Adress ?? DBNull.Value);
            cmd.Parameters.AddWithValue("@tarih", (object?)dto.tarih ?? DBNull.Value);
            conn.Open();
            cmd.ExecuteNonQuery();
        }
        

        public void Delete(int id)
        {
            using var conn = new SqlConnection(_connectionString);
            using var cmd = new SqlCommand("sp_Potansiyel_Delete", conn);
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.Parameters.AddWithValue("@Id", id);
            conn.Open();
            cmd.ExecuteNonQuery();
        }

        public void DeleteSoft(int id)
        {
            using var conn = new SqlConnection(_connectionString);
            using var cmd = new SqlCommand("sp_Potansiyel_DeleteSoft", conn);
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.Parameters.AddWithValue("@Id", id);
            conn.Open();
            cmd.ExecuteNonQuery();
        }

        public PotansiyelDto? GetById(int id)
        {
            using var conn = new SqlConnection(_connectionString);
            using var cmd = new SqlCommand("sp_Potansiyel_GetById", conn);
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.Parameters.AddWithValue("@Id", id);
            conn.Open();
            using var rdr = cmd.ExecuteReader();
            if (!rdr.Read()) return null;
        
            return new PotansiyelDto
            {
                Id = (int)rdr["Id"],
                Name = (string)rdr["Name"],
                SurName = (string)rdr["SurName"],
                KnownName = (string)rdr["KnownName"],
                Email = (string)rdr["Email"],
                PhoneNumber = (string)rdr["PhoneNumber"],
                IsActive = (bool)rdr["IsActive"],
                Adress = (int)rdr["Adress"],
                tarih = rdr["tarih"] == DBNull.Value ? (DateOnly?)null : DateOnly.FromDateTime((DateTime)rdr["tarih"]),
            };
        }
        

        public List<PotansiyelListItemDto> List()
        {
            var list = new List<PotansiyelListItemDto>();
            using var conn = new SqlConnection(_connectionString);
            using var cmd = new SqlCommand("sp_Potansiyel_List", conn);
            cmd.CommandType = CommandType.StoredProcedure;
            conn.Open();
            using var rdr = cmd.ExecuteReader();
            while (rdr.Read())
            {
                list.Add(new PotansiyelListItemDto
                {
                    Id = (int)rdr["Id"],
                    Name = (string)rdr["Name"],
                    SurName = (string)rdr["SurName"],
                    KnownName = (string)rdr["KnownName"],
                    Email = (string)rdr["Email"],
                    PhoneNumber = (string)rdr["PhoneNumber"],
                    IsActive = (bool)rdr["IsActive"],
                    Adress = (int)rdr["Adress"],
                    tarih = rdr["tarih"] == DBNull.Value ? (DateOnly?)null : DateOnly.FromDateTime((DateTime)rdr["tarih"]),
                });
            }
            return list;
        }
        

        public PagedResult<PotansiyelListItemDto> PagedList(int page, int pageSize)
        {
            var result = new PagedResult<PotansiyelListItemDto>();
            using var conn = new SqlConnection(_connectionString);
            using var cmd = new SqlCommand("sp_Potansiyel_PagedList", conn);
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.Parameters.AddWithValue("@Page", page);
            cmd.Parameters.AddWithValue("@PageSize", pageSize);
            conn.Open();
            using var rdr = cmd.ExecuteReader();
            while (rdr.Read())
            {
                result.Items.Add(new PotansiyelListItemDto
                {
                    Id = (int)rdr["Id"],
                    Name = (string)rdr["Name"],
                    SurName = (string)rdr["SurName"],
                    KnownName = (string)rdr["KnownName"],
                    Email = (string)rdr["Email"],
                    PhoneNumber = (string)rdr["PhoneNumber"],
                    IsActive = (bool)rdr["IsActive"],
                    Adress = (int)rdr["Adress"],
                    tarih = rdr["tarih"] == DBNull.Value ? (DateOnly?)null : DateOnly.FromDateTime((DateTime)rdr["tarih"]),
                });
            }
        
            if (rdr.NextResult() && rdr.Read())
                result.TotalCount = (int)rdr["TotalCount"];
        
            return result;
        }
        
    }
}
