// <auto-generated>
// This file is generated. Do not edit manually.
// Generated at      : 2026-02-27 17:18:33
// Generated at (UTC): 2026-02-27 14:18:33
// Machine: YAZILIM3
// Generator: EntityCreator v1.0
// Class Name: ControllerWriter
// </auto-generated>

#nullable enable

using Microsoft.AspNetCore.Mvc;
using System.Linq;
using SeramikStore.Services;
using SeramikStore.Contracts.Araba;
using SeramikStore.Web.ViewModels.Araba;

namespace SeramikStore.Web.Controllers
{
    public partial class ArabaController : Controller
    {

        public IActionResult Index()
        {
            var list = _arabaService.List();
            var vm = list.Select(x => new ArabaListViewModel
            {
                Id = x.Id,
                Model = x.Model,
                Marka = x.Marka,
            }).ToList();

            return View(vm);
        }

        public IActionResult Detail(int id)
        {
            var dto = _arabaService.GetById(id);
            if (dto == null)
                return NotFound();

            var vm = new ArabaViewModel
            {
                Id = dto.Id,
                Model = dto.Model,
                Marka = dto.Marka,
            };

            return View(vm);
        }

        public IActionResult Create()
        {
            return View(new ArabaCreateViewModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ArabaCreateViewModel vm)
        {
            if (!ModelState.IsValid)
                return View(vm);

            _arabaService.Create(new ArabaCreateDto
            {
                Model = vm.Model!,
                Marka = vm.Marka!,
            });

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Edit(int id)
        {
            var dto = _arabaService.GetById(id);
            if (dto == null)
                return NotFound();

            return View(new ArabaUpdateViewModel
            {
                Id = dto.Id,
                Model = dto.Model,
                Marka = dto.Marka,
            });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(ArabaUpdateViewModel vm)
        {
            if (!ModelState.IsValid)
                return View(vm);

            _arabaService.Update(new ArabaUpdateDto
            {
                Id = vm.Id!.Value,
                Model = vm.Model!,
                Marka = vm.Marka!,
            });

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Delete(int id)
        {
            var dto = _arabaService.GetById(id);
            if (dto == null)
                return NotFound();

            var vm = new ArabaViewModel
            {
                Id = dto.Id,
                Model = dto.Model,
                Marka = dto.Marka,
            };

            return View(vm);
        }

        [HttpPost, ActionName("DeleteConfirmed")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            _arabaService.Delete(id);
            return RedirectToAction(nameof(Index));
        }

    }
}
