// <auto-generated>
// This file is generated. Do not edit manually.
// Generated at      : 2026-02-13 16:12:55
// Generated at (UTC): 2026-02-13 13:12:55
// Machine: YAZILIM3
// Generator: EntityCreator v1.0
// Class Name: ControllerWriter
// </auto-generated>

#nullable enable

using Microsoft.AspNetCore.Mvc;
using System.Linq;
using SeramikStore.Services;
using SeramikStore.Contracts.Cart;
using SeramikStore.Web.ViewModels.Cart;

namespace SeramikStore.Web.Controllers
{
    public partial class CartController : Controller
    {

        public IActionResult Index()
        {
            var list = _cartService.List();
            var vm = list.Select(x => new CartListViewModel
            {
                Id = x.Id,
                ProductId = x.ProductId,
                ProductCode = x.ProductCode,
                ProductName = x.ProductName,
                UnitPrice = x.UnitPrice,
                Quantity = x.Quantity,
                TotalAmount = x.TotalAmount,
                UserId = x.UserId,
                cart_id_token = x.cart_id_token,
                CurrencyCode = x.CurrencyCode,
            }).ToList();

            return View(vm);
        }

        public IActionResult Detail(int id)
        {
            var dto = _cartService.GetById(id);
            if (dto == null)
                return NotFound();

            var vm = new CartViewModel
            {
                Id = dto.Id,
                ProductId = dto.ProductId,
                ProductCode = dto.ProductCode,
                ProductName = dto.ProductName,
                UnitPrice = dto.UnitPrice,
                Quantity = dto.Quantity,
                TotalAmount = dto.TotalAmount,
                UserId = dto.UserId,
                cart_id_token = dto.cart_id_token,
                CurrencyCode = dto.CurrencyCode,
            };

            return View(vm);
        }

        public IActionResult Create()
        {
            return View(new CartCreateViewModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CartCreateViewModel vm)
        {
            if (!ModelState.IsValid)
                return View(vm);

            _cartService.Create(new CartCreateDto
            {
                ProductId = vm.ProductId!.Value,
                ProductCode = vm.ProductCode!,
                ProductName = vm.ProductName!,
                UnitPrice = vm.UnitPrice!.Value,
                Quantity = vm.Quantity!.Value,
                TotalAmount = vm.TotalAmount!.Value,
                UserId = vm.UserId,
                cart_id_token = vm.cart_id_token,
                CurrencyCode = vm.CurrencyCode!,
            });

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Edit(int id)
        {
            var dto = _cartService.GetById(id);
            if (dto == null)
                return NotFound();

            return View(new CartUpdateViewModel
            {
                Id = dto.Id,
                ProductId = dto.ProductId,
                ProductCode = dto.ProductCode,
                ProductName = dto.ProductName,
                UnitPrice = dto.UnitPrice,
                Quantity = dto.Quantity,
                TotalAmount = dto.TotalAmount,
                UserId = dto.UserId,
                cart_id_token = dto.cart_id_token,
                CurrencyCode = dto.CurrencyCode,
            });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(CartUpdateViewModel vm)
        {
            if (!ModelState.IsValid)
                return View(vm);

            _cartService.Update(new CartUpdateDto
            {
                Id = vm.Id!.Value,
                ProductId = vm.ProductId!.Value,
                ProductCode = vm.ProductCode!,
                ProductName = vm.ProductName!,
                UnitPrice = vm.UnitPrice!.Value,
                Quantity = vm.Quantity!.Value,
                TotalAmount = vm.TotalAmount!.Value,
                UserId = vm.UserId,
                cart_id_token = vm.cart_id_token,
                CurrencyCode = vm.CurrencyCode!,
            });

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Delete(int id)
        {
            var dto = _cartService.GetById(id);
            if (dto == null)
                return NotFound();

            var vm = new CartViewModel
            {
                Id = dto.Id,
                ProductId = dto.ProductId,
                ProductCode = dto.ProductCode,
                ProductName = dto.ProductName,
                UnitPrice = dto.UnitPrice,
                Quantity = dto.Quantity,
                TotalAmount = dto.TotalAmount,
                UserId = dto.UserId,
                cart_id_token = dto.cart_id_token,
                CurrencyCode = dto.CurrencyCode,
            };

            return View(vm);
        }

        [HttpPost, ActionName("DeleteConfirmed")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            _cartService.Delete(id);
            return RedirectToAction(nameof(Index));
        }

    }
}
