// <auto-generated>
// This file is generated. Do not edit manually.
// Generated at      : 2026-02-08 21:59:33
// Generated at (UTC): 2026-02-08 18:59:33
// Machine: DESKTOP-IITN2G2
// Generator: EntityCreator v1.0
// Class Name: ControllerWriter
// </auto-generated>

#nullable enable

using Microsoft.AspNetCore.Mvc;
using SeramikStore.Contracts.Cart;
using SeramikStore.Entities;
using SeramikStore.Services;
using SeramikStore.Services.DTOs;
using SeramikStore.Web.ViewModels;
using SeramikStore.Web.ViewModels.Cart;
using System.Linq;

namespace SeramikStore.Web.Controllers
{
    public partial class CartController : Controller
    {
        private readonly IUserAddressService _userAddressService;
        private readonly ICartService _cartService;

        public CartController(
            IUserAddressService userAddressService,
            ICartService cartService)
        {
            _userAddressService = userAddressService;
            _cartService = cartService;
        }
        private CartResultDto GetCurrentCart()
        {
            var userId = HttpContext.Session.GetInt32("userId");
            CartResultDto cartResult;

            if (userId.HasValue)
            {
                // 👤 Login olmuş kullanıcı
                cartResult = _cartService.CartListByUserId(userId.Value);
            }
            else
            {
                // 🛒 Anon kullanıcı

                if (Request.Cookies.TryGetValue("cart_id", out var cartTokend))
                {
                    cartResult = _cartService.CartListByCartToken(cartTokend);
                }
                else
                {
                    cartResult = new CartResultDto();
                    cartResult.Summary = new CartSummaryDto();
                }


            }
             return cartResult;
        }

        public IActionResult EmptyCart()
        {
            return View();
        }
        public IActionResult Summary()
        {
            CartResultDto cartResult = GetCurrentCart();
            if (cartResult == null || !cartResult.Items.Any())
            {
               return RedirectToAction("EmptyCart");
            }
            return View(cartResult);
        }


        [HttpGet]
        public IActionResult DeleteCartItem(int id)
        {


            var cart = _cartService.Cart_GetById_withImage(id);
            if (cart == null)
                return RedirectToAction("Summary");

            var userId = HttpContext.Session.GetInt32("userId");

            if (userId.HasValue)
            {
                if (cart.UserId != userId.Value)
                    return RedirectToAction("Summary");
            }
            else
            {
                var cartId = Request.Cookies["cart_id"];
                if (cart.cart_id_token != cartId)
                    return RedirectToAction("Summary");
            }


            return View(cart);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteCartItem(Cart cart)
        {

            var dbCart = _cartService.CartGetById(cart.Id);
            if (dbCart == null)
                return RedirectToAction("Summary");

            var userId = HttpContext.Session.GetInt32("userId");
            if (userId.HasValue)
            {
                if (dbCart.UserId != userId.Value)
                    return Unauthorized();
            }
            else
            {
                var cartId = Request.Cookies["cart_id"];
                if (dbCart.cart_id_token != cartId)
                    return Unauthorized();
            }

            int result = _cartService.CartDeleteById(cart.Id);
            if (result > 0)
            {
                return RedirectToAction("Summary");
            }
            return RedirectToAction("Summary");



        }


        public IActionResult Increase(int id)
        {

            var cart = _cartService.CartGetById(id);
            if (cart == null)
                return RedirectToAction("Summary");

            var userId = HttpContext.Session.GetInt32("userId");

            if (userId.HasValue)
            {
                if (cart.UserId != userId.Value)
                    return Unauthorized();
            }
            else
            {
                var cartId = Request.Cookies["cart_id"];
                if (cart.cart_id_token != cartId)
                    return Unauthorized();
            }

            _cartService.IncreaseQuantity(id);
            return RedirectToAction("Summary");
        }

        public IActionResult Decrease(int id)
        {

            var cart = _cartService.CartGetById(id);


            if (cart == null)
                return RedirectToAction("Summary");

            var userId = HttpContext.Session.GetInt32("userId");

            if (userId.HasValue)
            {
                if (cart.UserId != userId.Value)
                    return Unauthorized();
            }
            else
            {
                var cartId = Request.Cookies["cart_id"];
                if (cart.cart_id_token != cartId)
                    return Unauthorized();
            }

            if (cart.Quantity == 1)
            {
                return RedirectToAction(nameof(DeleteCartItem), new { id });
            }

            if (cart.Quantity < 1)
            {
                return RedirectToAction("Summary");
            }

            _cartService.DecreaseQuantity(id);
            return RedirectToAction("Summary");
        }

        [HttpGet]
        public IActionResult AddressDetail()
        {
   


            CartResultDto cartResult = GetCurrentCart();
            if (cartResult == null || !cartResult.Items.Any())
            {
                return RedirectToAction("EmptyCart");
            }

            var userId = HttpContext.Session.GetInt32("userId");
            if (!userId.HasValue)
            {
                return RedirectToAction("Login", "Account",
                    new { returnUrl = Url.Action("AddressDetail", "Cart") });
            }

            var addresses = _userAddressService.GetByUserId((int)userId);

            var vm = new AddressSelectViewModel
            {
                Addresses = addresses.Select(a => new UserAddressViewModel
                {
                    Id = a.Id,
                    Ad = a.Ad,
                    Soyad = a.Soyad,
                    Telefon = a.Telefon,
                    Il = a.Il,
                    Ilce = a.Ilce,
                    Mahalle = a.Mahalle,
                    Adres = a.Adres,
                    Baslik = a.Baslik,
                    IsDefault = a.IsDefault
                }).ToList(),

                SelectedAddressId = addresses
                    .FirstOrDefault(x => x.IsDefault)?.Id ?? 0,


                TotalAmount = cartResult.Summary.TotalAmount,
                CargoAmount = cartResult.Summary.CargoAmount,
                GrandTotal = cartResult.Summary.GrandTotal,
                CurrencyCode = cartResult.Summary.CurrencyCode
            };

            return View(vm);
        }



    }
}
