// <auto-generated>
// This file is generated. Do not edit manually.
// Generated at      : 2026-01-19 17:47:50
// Generated at (UTC): 2026-01-19 14:47:50
// Machine: YAZILIM3
// Generator: EntityCreator v1.0
// Class Name: ControllerWriter
// </auto-generated>

using Microsoft.AspNetCore.Mvc;
using SeramikStore.Services;
using SeramikStore.Contracts.Category;
using SeramikStore.Web.ViewModels.Category;

namespace SeramikStore.Web.Controllers
{
    public partial class CategoryController : Controller
    {
        private readonly ICategoryService _categoryService;

        public CategoryController(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }

        // LIST
        public IActionResult Index()
        {
            var list = _categoryService.List();
            var vm = list.Select(x => new CategoryListViewModel
            {
                Id = x.Id,
                Name = x.Name,
                IsActive = x.IsActive
            }).ToList();

            return View(vm);
        }

        // CREATE (GET)
        public IActionResult Create()
        {
            return View(new CategoryCreateViewModel());
        }

        // CREATE (POST)
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CategoryCreateViewModel vm)
        {
            if (!ModelState.IsValid)
                return View(vm);

            _categoryService.Create(new CategoryCreateDto
            {
                Name = vm.Name
            });

            return RedirectToAction(nameof(Index));
        }

        // EDIT (GET)
        public IActionResult Edit(int id)
        {
            var item = _categoryService.GetById(id);
            if (item == null)
                return NotFound();

            return View(new CategoryUpdateViewModel
            {
                Id = item.Id,
                Name = item.Name,
                IsActive = item.IsActive
            });
        }

        // EDIT (POST)
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(CategoryUpdateViewModel vm)
        {
            if (!ModelState.IsValid)
                return View(vm);

            _categoryService.Update(new CategoryUpdateDto
            {
                Id = vm.Id,
                Name = vm.Name,
                IsActive = vm.IsActive
            });

            return RedirectToAction(nameof(Index));
        }

        // DELETE (GET)
        public IActionResult Delete(int id)
        {
            var dto = _categoryService.GetById(id);
            if (dto == null)
                return NotFound();

            var vm = new CategoryViewModel
            {
                Id = dto.Id,
                Name = dto.Name,
                IsActive = dto.IsActive
            };

            return View(vm);
        }

        // DELETE (POST)
        [HttpPost, ActionName("DeleteConfirmed")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            _categoryService.Delete(id);
            return RedirectToAction(nameof(Index));
        }

    }
}
