// <auto-generated>
// This file is generated. Do not edit manually.
// Generated at      : 2026-01-17 23:10:00
// Generated at (UTC): 2026-01-17 20:10:00
// Generator: EntityCreator v1.0
// Class Name: ControllerWriter
// </auto-generated>

using Microsoft.AspNetCore.Mvc;
using SeramikStore.Contracts.Category;
using SeramikStore.Services;

namespace SeramikStore.Web.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ICategoryService _categoryService;

        public CategoryController(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }

        // LIST
        public IActionResult Index()
        {
            var list = _categoryService.List();
            return View(list);
        }

        // DETAILS
        public IActionResult Details(int id)
        {
            var item = _categoryService.GetById(id);
            if (item == null)
                return NotFound();

            return View(item);
        }

        // CREATE (GET)
        public IActionResult Create()
        {
            return View();
        }

        // CREATE (POST)
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CategoryCreateDto dto)
        {
            if (!ModelState.IsValid)
                return View(dto);

            _categoryService.Create(dto);
            return RedirectToAction(nameof(Index));
        }

        // UPDATE (GET)
        public IActionResult Edit(int id)
        {
            var item = _categoryService.GetById(id);
            if (item == null)
                return NotFound();

            var dto = new CategoryUpdateDto
            {
                Id = item.Id,
                Name = item.Name,
                IsActive = item.IsActive
            };

            return View(dto);
        }

        // UPDATE (POST)
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(CategoryUpdateDto dto)
        {
            if (!ModelState.IsValid)
                return View(dto);

            _categoryService.Update(dto);
            return RedirectToAction(nameof(Index));
        }

        // DELETE (GET)
        public IActionResult Delete(int id)
        {
            var item = _categoryService.GetById(id);
            if (item == null)
                return NotFound();

            return View(item);
        }

        // DELETE (POST)
        [HttpPost, ActionName("DeleteConfirmed")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            _categoryService.Delete(id);
            return RedirectToAction(nameof(Index));
        }
    }
}
