// <auto-generated>
// This file is generated. Do not edit manually.
// Generated at      : 2026-01-23 11:52:32
// Generated at (UTC): 2026-01-23 08:52:32
// Machine: YAZILIM3
// Generator: EntityCreator v1.0
// Class Name: ControllerWriter
// </auto-generated>

using Microsoft.AspNetCore.Mvc;
using SeramikStore.Services;
using SeramikStore.Contracts.Potansiyel;
using SeramikStore.Web.ViewModels.Potansiyel;

namespace SeramikStore.Web.Controllers
{
    public partial class PotansiyelController : Controller
    {
        private readonly IPotansiyelService _potansiyelService;

        public PotansiyelController(IPotansiyelService potansiyelService)
        {
            _potansiyelService = potansiyelService;
        }

        // LIST
        public IActionResult Index()
        {
            var list = _potansiyelService.List();
            var vm = list.Select(x => new PotansiyelListViewModel
            {
                Id = x.Id,
                Name = x.Name,
                IsActive = x.IsActive
            }).ToList();

            return View(vm);
        }

        // CREATE (GET)
        public IActionResult Create()
        {
            return View(new PotansiyelCreateViewModel());
        }

        // CREATE (POST)
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(PotansiyelCreateViewModel vm)
        {
            if (!ModelState.IsValid)
                return View(vm);

            _potansiyelService.Create(new PotansiyelCreateDto
            {
                Name = vm.Name
            });

            return RedirectToAction(nameof(Index));
        }

        // EDIT (GET)
        public IActionResult Edit(int id)
        {
            var item = _potansiyelService.GetById(id);
            if (item == null)
                return NotFound();

            return View(new PotansiyelUpdateViewModel
            {
                Id = item.Id,
                Name = item.Name,
                IsActive = item.IsActive
            });
        }

        // EDIT (POST)
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(PotansiyelUpdateViewModel vm)
        {
            if (!ModelState.IsValid)
                return View(vm);

            _potansiyelService.Update(new PotansiyelUpdateDto
            {
                Id = vm.Id,
                Name = vm.Name,
                IsActive = vm.IsActive
            });

            return RedirectToAction(nameof(Index));
        }

        // DELETE (GET)
        public IActionResult Delete(int id)
        {
            var dto = _potansiyelService.GetById(id);
            if (dto == null)
                return NotFound();

            var vm = new PotansiyelViewModel
            {
                Id = dto.Id,
                Name = dto.Name,
                IsActive = dto.IsActive
            };

            return View(vm);
        }

        // DELETE (POST)
        [HttpPost, ActionName("DeleteConfirmed")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            _potansiyelService.Delete(id);
            return RedirectToAction(nameof(Index));
        }

    }
}
