// <auto-generated>
// This file is generated. Do not edit manually.
// Generated at      : 2026-01-25 13:20:44
// Generated at (UTC): 2026-01-25 10:20:44
// Machine: DESKTOP-IITN2G2
// Generator: EntityCreator v1.0
// Class Name: ControllerWriter
// </auto-generated>

#nullable enable

using Microsoft.AspNetCore.Mvc;
using System.Linq;
using SeramikStore.Services;
using SeramikStore.Contracts.Potansiyel;
using SeramikStore.Web.ViewModels.Potansiyel;

namespace SeramikStore.Web.Controllers
{
    public partial class PotansiyelController : Controller
    {
        private readonly IPotansiyelService _potansiyelService;

        public PotansiyelController(IPotansiyelService service)
        {
            _potansiyelService = service;
        }

        public IActionResult Index()
        {
            var list = _potansiyelService.List();
            var vm = list.Select(x => new PotansiyelListViewModel
            {
                Id = x.Id,
                Name = x.Name,
                SurName = x.SurName,
                KnownName = x.KnownName,
                Email = x.Email,
                PhoneNumber = x.PhoneNumber,
                IsActive = x.IsActive,
                Adress = x.Adress,
                tarih = x.tarih,
            }).ToList();

            return View(vm);
        }

        public IActionResult Detail(int id)
        {
            var dto = _potansiyelService.GetById(id);
            if (dto == null)
                return NotFound();

            var vm = new PotansiyelViewModel
            {
                Id = dto.Id,
                Name = dto.Name,
                SurName = dto.SurName,
                KnownName = dto.KnownName,
                Email = dto.Email,
                PhoneNumber = dto.PhoneNumber,
                IsActive = dto.IsActive,
                Adress = dto.Adress,
                tarih = dto.tarih,
            };

            return View(vm);
        }

        public IActionResult Create()
        {
            return View(new PotansiyelCreateViewModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(PotansiyelCreateViewModel vm)
        {
            if (!ModelState.IsValid)
                return View(vm);

            _potansiyelService.Create(new PotansiyelCreateDto
            {
                Name = vm.Name,
                SurName = vm.SurName,
                KnownName = vm.KnownName,
                Email = vm.Email,
                PhoneNumber = vm.PhoneNumber,
                Adress = vm.Adress,
                tarih = vm.tarih,
            });

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Edit(int id)
        {
            var dto = _potansiyelService.GetById(id);
            if (dto == null)
                return NotFound();

            return View(new PotansiyelUpdateViewModel
            {
                Id = dto.Id,
                Name = dto.Name,
                SurName = dto.SurName,
                KnownName = dto.KnownName,
                Email = dto.Email,
                PhoneNumber = dto.PhoneNumber,
                IsActive = dto.IsActive,
                Adress = dto.Adress,
                tarih = dto.tarih,
            });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(PotansiyelUpdateViewModel vm)
        {
            if (!ModelState.IsValid)
                return View(vm);

            _potansiyelService.Update(new PotansiyelUpdateDto
            {
                Id = vm.Id,
                Name = vm.Name,
                SurName = vm.SurName,
                KnownName = vm.KnownName,
                Email = vm.Email,
                PhoneNumber = vm.PhoneNumber,
                IsActive = vm.IsActive,
                Adress = vm.Adress,
                tarih = vm.tarih,
            });

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Delete(int id)
        {
            var dto = _potansiyelService.GetById(id);
            if (dto == null)
                return NotFound();

            var vm = new PotansiyelViewModel
            {
                Id = dto.Id,
                Name = dto.Name,
                SurName = dto.SurName,
                KnownName = dto.KnownName,
                Email = dto.Email,
                PhoneNumber = dto.PhoneNumber,
                IsActive = dto.IsActive,
                Adress = dto.Adress,
                tarih = dto.tarih,
            };

            return View(vm);
        }

        [HttpPost, ActionName("DeleteConfirmed")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            _potansiyelService.Delete(id);
            return RedirectToAction(nameof(Index));
        }

    }
}
