// <auto-generated>
// This file is generated. Do not edit manually.
// Generated at      : 2026-01-29 09:02:51
// Generated at (UTC): 2026-01-29 06:02:51
// Machine: YAZILIM3
// Generator: EntityCreator v1.0
// Class Name: ControllerWriter
// </auto-generated>

#nullable enable

using Microsoft.AspNetCore.Mvc;
using System.Linq;
using SeramikStore.Services;
using SeramikStore.Contracts.Potansiyel;
using SeramikStore.Web.ViewModels.Potansiyel;

namespace SeramikStore.Web.Controllers
{
    public partial class PotansiyelController : Controller
    {
        private readonly IPotansiyelService _potansiyelService;

        public PotansiyelController(IPotansiyelService service)
        {
            _potansiyelService = service;
        }

        public IActionResult Index()
        {
            var list = _potansiyelService.List();
            var vm = list.Select(x => new PotansiyelListViewModel
            {
                Id = x.Id,
                Name = x.Name,
                SurName = x.SurName,
                KnownName = x.KnownName,
                Email = x.Email,
                PhoneNumber = x.PhoneNumber,
                Adress = x.Adress,
                tarih = x.tarih,
                kayıttarihi = x.kayıttarihi,
                OzelSaatBilgisi = x.OzelSaatBilgisi,
                SatirAciklamasi = x.SatirAciklamasi,
                GenisAciklama = x.GenisAciklama,
                Fiyat = x.Fiyat,
            }).ToList();

            return View(vm);
        }

        public IActionResult Detail(int id)
        {
            var dto = _potansiyelService.GetById(id);
            if (dto == null)
                return NotFound();

            var vm = new PotansiyelViewModel
            {
                Id = dto.Id,
                Name = dto.Name,
                SurName = dto.SurName,
                KnownName = dto.KnownName,
                Email = dto.Email,
                PhoneNumber = dto.PhoneNumber,
                Adress = dto.Adress,
                tarih = dto.tarih,
                kayıttarihi = dto.kayıttarihi,
                OzelSaatBilgisi = dto.OzelSaatBilgisi,
                SatirAciklamasi = dto.SatirAciklamasi,
                GenisAciklama = dto.GenisAciklama,
                Fiyat = dto.Fiyat,
            };

            return View(vm);
        }

        public IActionResult Create()
        {
            return View(new PotansiyelCreateViewModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(PotansiyelCreateViewModel vm)
        {
            if (!ModelState.IsValid)
                return View(vm);

            _potansiyelService.Create(new PotansiyelCreateDto
            {
                Name = vm.Name!,
                SurName = vm.SurName!,
                KnownName = vm.KnownName!,
                Email = vm.Email!,
                PhoneNumber = vm.PhoneNumber!,
                Adress = vm.Adress!.Value,
                tarih = vm.tarih,
                kayıttarihi = vm.kayıttarihi,
                OzelSaatBilgisi = vm.OzelSaatBilgisi,
                SatirAciklamasi = vm.SatirAciklamasi,
                GenisAciklama = vm.GenisAciklama,
                Fiyat = vm.Fiyat,
            });

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Edit(int id)
        {
            var dto = _potansiyelService.GetById(id);
            if (dto == null)
                return NotFound();

            return View(new PotansiyelUpdateViewModel
            {
                Id = dto.Id,
                Name = dto.Name,
                SurName = dto.SurName,
                KnownName = dto.KnownName,
                Email = dto.Email,
                PhoneNumber = dto.PhoneNumber,
                Adress = dto.Adress,
                tarih = dto.tarih,
                kayıttarihi = dto.kayıttarihi,
                OzelSaatBilgisi = dto.OzelSaatBilgisi,
                SatirAciklamasi = dto.SatirAciklamasi,
                GenisAciklama = dto.GenisAciklama,
                Fiyat = dto.Fiyat,
            });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(PotansiyelUpdateViewModel vm)
        {
            if (!ModelState.IsValid)
                return View(vm);

            _potansiyelService.Update(new PotansiyelUpdateDto
            {
                Id = vm.Id!.Value,
                Name = vm.Name!,
                SurName = vm.SurName!,
                KnownName = vm.KnownName!,
                Email = vm.Email!,
                PhoneNumber = vm.PhoneNumber!,
                Adress = vm.Adress!.Value,
                tarih = vm.tarih,
                kayıttarihi = vm.kayıttarihi,
                OzelSaatBilgisi = vm.OzelSaatBilgisi,
                SatirAciklamasi = vm.SatirAciklamasi,
                GenisAciklama = vm.GenisAciklama,
                Fiyat = vm.Fiyat,
            });

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Delete(int id)
        {
            var dto = _potansiyelService.GetById(id);
            if (dto == null)
                return NotFound();

            var vm = new PotansiyelViewModel
            {
                Id = dto.Id,
                Name = dto.Name,
                SurName = dto.SurName,
                KnownName = dto.KnownName,
                Email = dto.Email,
                PhoneNumber = dto.PhoneNumber,
                Adress = dto.Adress,
                tarih = dto.tarih,
                kayıttarihi = dto.kayıttarihi,
                OzelSaatBilgisi = dto.OzelSaatBilgisi,
                SatirAciklamasi = dto.SatirAciklamasi,
                GenisAciklama = dto.GenisAciklama,
                Fiyat = dto.Fiyat,
            };

            return View(vm);
        }

        [HttpPost, ActionName("DeleteConfirmed")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            _potansiyelService.Delete(id);
            return RedirectToAction(nameof(Index));
        }

    }
}
