// <auto-generated>
// This file is generated. Do not edit manually.
// Generated at      : 2026-04-21 14:26:25
// Generated at (UTC): 2026-04-21 11:26:25
// Machine: YAZILIM3
// Generator: EntityCreator v1.0
// Class Name: ControllerWriter
// </auto-generated>

#nullable enable

using Microsoft.AspNetCore.Mvc;
using System.Linq;
using SeramikStore.Services;
using SeramikStore.Contracts.ProductCategory;
using SeramikStore.Web.ViewModels.ProductCategory;

namespace SeramikStore.Web.Controllers
{
    public partial class ProductCategoryController : Controller
    {
        private readonly IProductCategoryService _productCategoryService;

        public ProductCategoryController(IProductCategoryService service)
        {
            _productCategoryService = service;
        }

        public IActionResult Index()
        {
            var list = _productCategoryService.List();
            var vm = list.Select(x => new ProductCategoryListViewModel
            {
                Id = x.Id,
                ProductId = x.ProductId,
                CategoryId = x.CategoryId,
            }).ToList();

            return View(vm);
        }

        public IActionResult Detail(int id)
        {
            var dto = _productCategoryService.GetById(id);
            if (dto == null)
                return NotFound();

            var vm = new ProductCategoryViewModel
            {
                Id = dto.Id,
                ProductId = dto.ProductId,
                CategoryId = dto.CategoryId,
            };

            return View(vm);
        }

        public IActionResult Create()
        {
            return View(new ProductCategoryCreateViewModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ProductCategoryCreateViewModel vm)
        {
            if (!ModelState.IsValid)
                return View(vm);

            _productCategoryService.Create(new ProductCategoryCreateDto
            {
                ProductId = (int)vm.ProductId,
                CategoryId = (int)vm.CategoryId,
            });

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Edit(int id)
        {
            var dto = _productCategoryService.GetById(id);
            if (dto == null)
                return NotFound();

            return View(new ProductCategoryUpdateViewModel
            {
                Id = dto.Id,
                ProductId = dto.ProductId,
                CategoryId = dto.CategoryId,
            });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(ProductCategoryUpdateViewModel vm)
        {
            if (!ModelState.IsValid)
                return View(vm);

            _productCategoryService.Update(new ProductCategoryUpdateDto
            {
                Id = vm.Id!.Value,
                ProductId = vm.ProductId!.Value,
                CategoryId = vm.CategoryId!.Value,
            });

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Delete(int id)
        {
            var dto = _productCategoryService.GetById(id);
            if (dto == null)
                return NotFound();

            var vm = new ProductCategoryViewModel
            {
                Id = dto.Id,
                ProductId = dto.ProductId,
                CategoryId = dto.CategoryId,
            };

            return View(vm);
        }

        [HttpPost, ActionName("DeleteConfirmed")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            _productCategoryService.Delete(id);
            return RedirectToAction(nameof(Index));
        }

    }
}
