// <auto-generated>
// This file is generated. Do not edit manually.
// Generated at      : 2026-03-29 20:43:37
// Generated at (UTC): 2026-03-29 17:43:37
// Machine: DESKTOP-IITN2G2
// Generator: EntityCreator v1.0
// Class Name: ControllerWriter
// </auto-generated>

#nullable enable

using Microsoft.AspNetCore.Mvc;
using System.Linq;
using SeramikStore.Services;
using SeramikStore.Contracts.Reason;
using SeramikStore.Web.ViewModels.Reason;

namespace SeramikStore.Web.Controllers
{
    public partial class ReasonController : Controller
    {
        private readonly IReasonService _reasonService;

        public ReasonController(IReasonService service)
        {
            _reasonService = service;
        }

        public IActionResult Index()
        {
            var list = _reasonService.List();
            var vm = list.Select(x => new ReasonListViewModel
            {
                Id = x.Id,
                Reasondesc = x.Reasondesc,
                IsCustom = x.IsCustom,
            }).ToList();

            return View(vm);
        }

        public IActionResult Detail(int id)
        {
            var dto = _reasonService.GetById(id);
            if (dto == null)
                return NotFound();

            var vm = new ReasonViewModel
            {
                Id = dto.Id,
                Reasondesc = dto.Reasondesc,
                IsCustom = dto.IsCustom,
            };

            return View(vm);
        }

        public IActionResult Create()
        {
            return View(new ReasonCreateViewModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ReasonCreateViewModel vm)
        {
            if (!ModelState.IsValid)
                return View(vm);

            _reasonService.Create(new ReasonCreateDto
            {
                Reasondesc = vm.Reasondesc!,
                IsCustom = vm.IsCustom,
            });

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Edit(int id)
        {
            var dto = _reasonService.GetById(id);
            if (dto == null)
                return NotFound();

            return View(new ReasonUpdateViewModel
            {
                Id = dto.Id,
                Reasondesc = dto.Reasondesc,
                IsCustom = dto.IsCustom,
            });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(ReasonUpdateViewModel vm)
        {
            if (!ModelState.IsValid)
                return View(vm);

            _reasonService.Update(new ReasonUpdateDto
            {
                Id = vm.Id!.Value,
                Reasondesc = vm.Reasondesc!,
                IsCustom = vm.IsCustom,
            });

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Delete(int id)
        {
            var dto = _reasonService.GetById(id);
            if (dto == null)
                return NotFound();

            var vm = new ReasonViewModel
            {
                Id = dto.Id,
                Reasondesc = dto.Reasondesc,
                IsCustom = dto.IsCustom,
            };

            return View(vm);
        }

        [HttpPost, ActionName("DeleteConfirmed")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            _reasonService.DeleteSoft(id);
            return RedirectToAction(nameof(Index));
        }

    }
}
