// <auto-generated>
// This file is generated. Do not edit manually.
// Generated at      : 2026-01-29 09:02:51
// Generated at (UTC): 2026-01-29 06:02:51
// Machine: YAZILIM3
// Generator: EntityCreator v1.0
// Class Name: ViewModelWriter
// </auto-generated>

#nullable enable

using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using Microsoft.AspNetCore.Mvc.Rendering;
using SeramikStore.Contracts.Reason;
using SeramikStore.Contracts.Return;
using SeramikStore.Entities.Enums;
using System;
using System.ComponentModel.DataAnnotations;

namespace SeramikStore.Web.ViewModels.Return
{
    public class ReturnCreateViewModel
    {
        [ValidateNever]
        public int OrderId { get; set; }

        [ValidateNever]
        public int ReasonId { get; set; }

        [ValidateNever]
        public string Reasondesc { get; set; }

        [ValidateNever]
        public List<ReturnCreateItemDto> Items { get; set; }

        [ValidateNever]
        public List<SelectListItem> Reasons { get; set; }


    }
}
