// <auto-generated>
// This file is generated. Do not edit manually.
// Generated at      : 2026-01-17 22:18:18
// Generated at (UTC): 2026-01-17 19:18:18
// Machine: DESKTOP-IITN2G2
// Generator: EntityCreator v1.0
// Class Name: DtoWriter
// </auto-generated>

using System;

namespace SeramikStore.Contracts.Cart
{
    public class CartCreateDto
    {
        public int ProductId { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public decimal UnitPrice { get; set; }
        public int Quantity { get; set; }
        public decimal TotalAmount { get; set; }
        public int UserId { get; set; }
    }
}
