// <auto-generated>
// This file is generated. Do not edit manually.
// Generated at      : 2026-02-13 16:12:55
// Generated at (UTC): 2026-02-13 13:12:55
// Machine: YAZILIM3
// Generator: EntityCreator v1.0
// Class Name: DtoWriter
// </auto-generated>

#nullable enable

using System;

namespace SeramikStore.Contracts.Cart
{
    public class CartDto
    {
        public int Id { get; set; }
        public int ProductId { get; set; }
        public required string ProductCode { get; set; }
        public required string ProductName { get; set; }
        public decimal UnitPrice { get; set; }
        public int Quantity { get; set; }
        public decimal TotalAmount { get; set; }
        public int? UserId { get; set; }
        public string? cart_id_token { get; set; }
        public required string CurrencyCode { get; set; }
    }
}
