// <auto-generated>
// This file is generated. Do not edit manually.
// Generated at      : 2026-02-27 17:18:33
// Generated at (UTC): 2026-02-27 14:18:33
// Machine: YAZILIM3
// Generator: EntityCreator v1.0
// Class Name: ViewModelWriter
// </auto-generated>

#nullable enable

using System;
using System.ComponentModel.DataAnnotations;

namespace SeramikStore.Web.ViewModels.Araba
{
    public class ArabaViewModel
    {
        [Required]
        [Display(Name = "Id")]
        public int? Id { get; set; }

        [Required]
        [Display(Name = "Model")]
        public string? Model { get; set; }

        [Required]
        [Display(Name = "Marka")]
        public string? Marka { get; set; }

    }
}
