// <auto-generated>
// This file is generated. Do not edit manually.
// Generated at      : 2026-02-19 17:07:06
// Generated at (UTC): 2026-02-19 14:07:06
// Machine: YAZILIM3
// Generator: EntityCreator v1.0
// Class Name: ViewModelWriter
// </auto-generated>

#nullable enable

using System;
using System.ComponentModel.DataAnnotations;

namespace SeramikStore.Web.ViewModels.Tasit
{
    public class TasitCreateViewModel
    {
        [Required]
        [Display(Name = "Aciklama")]
        public string? Aciklama { get; set; }

        [Required]
        [Display(Name = "Tipi")]
        public int? Tipi { get; set; }

        [Required]
        [Display(Name = "PlakaKodu")]
        public string? PlakaKodu { get; set; }

        [Display(Name = "Sehir")]
        public string? Sehir { get; set; }

    }
}
