// <auto-generated>
// This file is generated. Do not edit manually.
// Generated at      : 2026-01-25 01:45:27
// Generated at (UTC): 2026-01-24 22:45:27
// Machine: DESKTOP-IITN2G2
// Generator: EntityCreator v1.0
// Class Name: ViewModelWriter
// </auto-generated>

#nullable enable

using System;
using System.ComponentModel.DataAnnotations;

namespace SeramikStore.Web.ViewModels.Potansiyel
{
    public class PotansiyelListViewModel
    {
        [Required]
        [Display(Name = "Id")]
        public int Id { get; set; }

        [Required]
        [Display(Name = "Name")]
        public string Name { get; set; }

        [Required]
        [Display(Name = "SurName")]
        public string SurName { get; set; }

        [Required]
        [Display(Name = "KnownName")]
        public string KnownName { get; set; }

        [Required]
        [Display(Name = "Email")]
        public string Email { get; set; }

        [Required]
        [Display(Name = "PhoneNumber")]
        public string PhoneNumber { get; set; }

        [Required]
        [Display(Name = "IsActive")]
        public bool IsActive { get; set; }

        [Required]
        [Display(Name = "Adress")]
        public int Adress { get; set; }

        [Display(Name = "tarih")]
        public DateOnly? tarih { get; set; }

    }
}
