// <auto-generated>
// This file is generated. Do not edit manually.
// Generated at      : 2026-01-26 18:51:00
// Generated at (UTC): 2026-01-26 15:51:00
// Machine: YAZILIM3
// Generator: EntityCreator v1.0
// Class Name: ViewModelWriter
// </auto-generated>

#nullable enable

using System;
using System.ComponentModel.DataAnnotations;

namespace SeramikStore.Web.ViewModels.Potansiyel
{
    public class PotansiyelViewModel
    {
        [Required]
        [Display(Name = "Id")]
        public int? Id { get; set; }

        [Required]
        [Display(Name = "Name")]
        public string? Name { get; set; }

        [Required]
        [Display(Name = "SurName")]
        public string? SurName { get; set; }

        [Required]
        [Display(Name = "KnownName")]
        public string? KnownName { get; set; }

        [Required]
        [Display(Name = "Email")]
        public string? Email { get; set; }

        [Required]
        [Display(Name = "PhoneNumber")]
        public string? PhoneNumber { get; set; }

        [Required]
        [Display(Name = "IsActive")]
        public bool? IsActive { get; set; }

        [Required]
        [Display(Name = "Adress")]
        public int? Adress { get; set; }

        [Display(Name = "tarih")]
        public DateOnly? tarih { get; set; }

        [Display(Name = "kayıttarihi")]
        public DateTime? kayıttarihi { get; set; }

        [Display(Name = "saat")]
        public TimeOnly? saat { get; set; }

        [Display(Name = "satir")]
        public string? satir { get; set; }

        [Display(Name = "max")]
        public string? max { get; set; }

        [Display(Name = "resim")]
        public byte[]? resim { get; set; }

    }
}
