// <auto-generated>
// This file is generated. Do not edit manually.
// Generated at      : 2026-01-24 22:23:17
// Generated at (UTC): 2026-01-24 19:23:17
// Machine: DESKTOP-IITN2G2
// Generator: EntityCreator v1.0
// Class Name: ViewModelWriter
// </auto-generated>

#nullable enable

using System;
using System.ComponentModel.DataAnnotations;

namespace SeramikStore.Web.ViewModels.Potansiyel
{
    public class PotansiyelCreateViewModel
    {
        [Display(Name = "Name")]
        public string? Name { get; set; }

        [Display(Name = "SurName")]
        public string? SurName { get; set; }

        [Display(Name = "KnownName")]
        public string? KnownName { get; set; }

        [Display(Name = "Email")]
        public string? Email { get; set; }

        [Display(Name = "PhoneNumber")]
        public string? PhoneNumber { get; set; }

    }
}
