// <auto-generated>
// This file is generated. Do not edit manually.
// Generated at      : 2026-01-23 11:52:32
// Generated at (UTC): 2026-01-23 08:52:32
// Machine: YAZILIM3
// Generator: EntityCreator v1.0
// Class Name: ViewModelWriter
// </auto-generated>

using System;
using System.ComponentModel.DataAnnotations;

namespace SeramikStore.Web.ViewModels.Potansiyel
{
    public class PotansiyelListViewModel
    {
        [Display(Name = "Id")]
        public int Id { get; set; }

        [Display(Name = "Name")]
        public string Name { get; set; }

        [Display(Name = "SurName")]
        public string SurName { get; set; }

        [Display(Name = "KnownName")]
        public string KnownName { get; set; }

        [Display(Name = "Email")]
        public string Email { get; set; }

        [Display(Name = "PhoneNumber")]
        public string PhoneNumber { get; set; }

        [Display(Name = "IsActive")]
        public bool IsActive { get; set; }

    }
}
