// <auto-generated>
// This file is generated. Do not edit manually.
// Generated at      : 2026-03-29 20:43:37
// Generated at (UTC): 2026-03-29 17:43:37
// Machine: DESKTOP-IITN2G2
// Generator: EntityCreator v1.0
// Class Name: DtoWriter
// </auto-generated>

#nullable enable

using System;

namespace SeramikStore.Contracts.Reason
{
    public class ReasonCreateDto
    {
        public required string Reasondesc { get; set; }
        public bool? IsCustom { get; set; }
    }
}
