// <auto-generated>
// This file is generated. Do not edit manually.
// Generated at      : 2026-01-18 15:11:40
// Generated at (UTC): 2026-01-18 12:11:40
// Machine: DESKTOP-IITN2G2
// Generator: EntityCreator v1.0
// Class Name: DtoWriter
// </auto-generated>

using System;

namespace SeramikStore.Web.ViewModels.Category
{
    public class CategoryListItemDto
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public bool IsActive { get; set; }
    }
}
